const DATA="data/normalized/",RELEASE="20260722-player-top15-compact-controls";
const labels={scheduled:"Programmata",live:"In corso",finished:"Conclusa",postponed:"Rinviata"};
const esc=v=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
async function load(name){const r=await fetch(`${DATA}${name}?v=${RELEASE}`);if(!r.ok)throw new Error(`${name}: ${r.status}`);return r.json()}
async function loadGenerated(path){const r=await fetch(`data/generated/${path}?v=${RELEASE}`);if(!r.ok)throw new Error(`${path}: ${r.status}`);return r.json()}
async function loadTeamDirectory(){const r=await fetch(`data/teams/index.json?v=${RELEASE}`);if(!r.ok)throw new Error(`data/teams/index.json: ${r.status}`);return r.json()}
async function loadPlayerLeaderboards(){const r=await fetch(`data/teams/player-leaderboards.json?v=${RELEASE}`);if(!r.ok)throw new Error(`data/teams/player-leaderboards.json: ${r.status}`);return r.json()}
async function loadObjectiveProfiles(){const r=await fetch(`data/team-objectives.json?v=${RELEASE}`);if(!r.ok)throw new Error(`data/team-objectives.json: ${r.status}`);return r.json()}
const dateOnly=v=>{if(!v)return null;const [year,month,day]=String(v).slice(0,10).split("-");const months=["gen","feb","mar","apr","mag","giu","lug","ago","set","ott","nov","dic"];return `${Number(day)} ${months[Number(month)-1]} ${year}`};
const sourceBanner=()=>`<aside class="source-banner"><strong>Fonti tracciate per ogni dataset.</strong> Calendario dal C.U. n. 205; date e orari delle prime cinque giornate dal C.U. n. 208.</aside>`;
const hero=(eyebrow,title,text,aside="")=>`${sourceBanner()}<section class="hero"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="lead">${text}</p></div>${aside}</section>`;
function scheduleLabel(m){
  if(!m.date)return `Data da definire · giornata di riferimento ${dateOnly(m.matchdayDate)}`;
  return `${dateOnly(m.date)} · ${m.kickoff||"orario da definire"}${m.dateStatus==="provisional"?" · programmazione provvisoria UEFA":""}`;
}
function teamLogo(team){return `<span class="team-with-logo"><span class="team-logo"><img src="${team.logo}" alt="Stemma ${esc(team.name)}" onerror="this.hidden=true;this.parentElement.classList.add('fallback')"><b>${esc(team.shortName.slice(0,2).toUpperCase())}</b></span><span class="team-name">${esc(team.name)}</span></span>`}
function matchCard(m,teams){
  const home=teams.find(x=>x.id===m.homeTeam),away=teams.find(x=>x.id===m.awayTeam),score=m.score?`${m.score.home} – ${m.score.away}`:"VS";
  const scoreContent=m.score?esc(score):'<img class="versus-image" src="assets/images/vs-gold.png" alt="VS">';
  const [homeColor1="#174fa5",homeColor2="#081d48"]=home.colors||[],[awayColor1="#174fa5",awayColor2="#081d48"]=away.colors||[];
  const teamColorStyle=`--home-color-1:${homeColor1};--home-color-2:${homeColor2};--away-color-1:${awayColor1};--away-color-2:${awayColor2}`;
  const eventText=(items,formatter)=>items?.length?items.map(formatter).join(" · "):"—";
  const scorers=eventText(m.scorers,s=>`${esc(s.player)}${s.minute?` ${s.minute}’`:""}`);
  const bookings=eventText(m.bookings||m.bookedPlayers||m.ammoniti,b=>typeof b==="string"?esc(b):`${esc(b.player||b.name)}${b.minute?` ${b.minute}’`:""}`);
  return `<article class="card match fixture-card" style="${teamColorStyle}"><header class="match-head"><div class="match-badges"><span class="matchday-chip">Giornata ${m.matchday}</span><span class="status ${m.status}">${labels[m.status]||m.status}</span>${m.dateStatus==="provisional"?'<span class="status provisional">Provvisoria UEFA</span>':''}</div><div class="match-date">${scheduleLabel(m)}</div></header><div class="fixture-teams"><div class="fixture-team fixture-team-home">${teamLogo(home)}</div><div class="fixture-score"><strong class="score ${m.score?'score-result':'score-versus'}">${scoreContent}</strong></div><div class="fixture-team fixture-team-away">${teamLogo(away)}</div></div><div class="match-events" aria-label="Eventi partita"><div><span>Marcatori</span><small>${scorers}</small></div><div><span>Ammoniti</span><small>${bookings}</small></div></div><div class="actions"><a class="button" href="lettura.html?match=${m.id}">Lettura</a><a class="button" href="statistiche-squadre.html?team=${m.homeTeam}">Statistiche</a></div></article>`
}
function standingsTable(rows,teams){const teamFor=r=>teams.find(t=>t.id===r.team),name=r=>r.teamName||teamFor(r)?.name||r.team,teamCell=r=>{const team=teamFor(r);return `<span class="standing-team">${team?.logo?`<span class="standing-logo"><img src="${team.logo}" alt="" onerror="this.hidden=true"></span>`:'<span class="standing-logo fallback"></span>'}<span>${esc(name(r))}</span></span>`};return `<div class="table-wrap"><table class="standings-table"><thead><tr><th>#</th><th>Squadra</th><th>PT</th><th>PG</th><th>V</th><th>N</th><th>P</th><th>GF</th><th>GS</th><th>DR</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${r.position||i+1}</td><td>${teamCell(r)}</td><td><strong>${r.points}</strong></td><td>${r.played}</td><td>${r.won}</td><td>${r.drawn}</td><td>${r.lost}</td><td>${r.goalsFor}</td><td>${r.goalsAgainst}</td><td>${r.goalDifference>0?'+':''}${r.goalDifference}</td></tr>`).join("")}</tbody></table></div>`}
const signed=value=>`${value>0?"+":""}${value}%`;
function objectiveStatusSection(dataset,rows,teams){
  const profilesById=new Map(dataset.teams.map(profile=>[profile.teamId,profile])),positioned=rows.map((row,index)=>({...row,position:index+1}));
  const cards=teams.map(team=>{const profile=profilesById.get(team.id),row=positioned.find(item=>item.team===team.id);if(!profile)return `<article class="objective-card objective-missing"><header>${teamLogo(team)}<span>Profilo da completare</span></header><p>I valori iniziali per questa squadra non erano presenti nel dataset ricevuto.</p></article>`;const metrics=ObjectiveMetrics.calculateObjectiveMetrics(profile,row,row?.played||0),preseason=metrics.status==="preseason",metric=(label,value,tone="")=>`<div class="objective-metric ${tone}"><span>${label}</span><strong>${value}</strong></div>`;return `<article class="objective-card"><header>${teamLogo(team)}<span>${preseason?"Valori iniziali":"Aggiornato automaticamente"}</span></header><div class="objective-title"><small>Obiettivo iniziale</small><h3>🏆 ${esc(profile.primaryObjective)}</h3><p>Secondario: ${esc(profile.secondaryObjective)} · posizione obiettivo ${profile.targetPosition}ª</p></div><div class="objective-metrics">${metric("Progresso obiettivo",`${metrics.objectiveProgress}%`)}${metric("Rendimento sulle attese",signed(metrics.seasonOverperformance),metrics.seasonOverperformance>0?"positive":metrics.seasonOverperformance<0?"negative":"")}${metric("Motivazione",`${metrics.motivationCurrent}/100`)}${metric("Pressione",`${metrics.pressureCurrent}/100`)}${metric("Urgenza punti",`${metrics.urgency}/100`,metrics.urgency>=80?"urgent":"")}</div></article>`}).join("");
  const unused=dataset.teams.filter(profile=>!teams.some(team=>team.id===profile.teamId)).map(profile=>profile.team).join(" · ");
  return `<section class="section objective-section" id="stato-obiettivi"><header class="objective-section-head"><div><p class="eyebrow">Motore dinamico · stagione 2026/27</p><h2>Stato degli obiettivi</h2></div><p>Progresso, rendimento, motivazione, pressione e urgenza vengono ricalcolati dai risultati conclusi. Sono fattori contestuali per la lettura delle partite, non pronostici autonomi.</p></header>${unused?`<aside class="objective-data-note"><strong>Copertura del dataset ricevuto: 17/20 squadre del calendario corrente.</strong> I profili di ${esc(unused)} sono conservati nei dati sorgente ma non appartengono al calendario caricato; Frosinone, Monza e Venezia restano da configurare.</aside>`:""}<div class="objective-grid">${cards}</div><p class="objective-method">A inizio stagione il progresso e lo scostamento sono neutrali; motivazione e pressione coincidono con i valori iniziali. Dopo ogni giornata il calcolo usa posizione, punti, proiezione a 38 gare e distanza dall'obiettivo.</p></section>`;
}
const verdictsPanel=(verdicts,teams,rows)=>{const teamName=id=>teams.find(t=>t.id===id)?.name||rows.find(r=>r.team===id)?.teamName||id;const item=(type,title,ids)=>`<li class="verdict-item ${type}"><span>${title}</span><strong>${ids.map(id=>esc(teamName(id))).join(" · ")}</strong></li>`;return `<ul class="verdict-list">${item("champion","Campione d'Italia",verdicts.champion)}${item("champions","Champions League",verdicts.championsLeague)}${item("europa","Europa League",verdicts.europaLeague)}${item("conference","Conference League",verdicts.conferenceLeague)}${item("relegated","Retrocesse in Serie B",verdicts.relegated)}${item("promoted","Promosse in Serie A 2026/27",verdicts.promoted)}</ul>`};
const dayNav=()=>`<nav class="day-nav" aria-label="Selezione rapida giornata"><span>Vai alla giornata</span><div>${Array.from({length:38},(_,i)=>{const day=i+1;return `<a class="day-link" href="#giornata-${day}" aria-label="Giornata ${day}">${day}</a>`}).join("")}</div></nav>`;
const teamDirectoryGrid=data=>`<section class="team-directory-grid">${data.teams.map(team=>{const logo=String(team.logo||"").replace(/^\.\.\//,"");return `<a class="team-directory-card" href="statistiche-squadra/${team.id}.html"><img src="${esc(logo)}" alt="Stemma ${esc(team.name)}"><div><span class="competition-chip">${esc(team.previousSeason.competition)} 2025/26</span><h2>${esc(team.name)}</h2><p>${team.previousSeason.position?`${team.previousSeason.position}ª posizione · ${team.previousSeason.points} punti`:"Posizione N/D"}</p><small>Città: ${esc(team.city||"N/D")} · Stadio: ${esc(team.stadium||"N/D")}</small><small>Allenatore: ${esc(team.coach||"N/D")} · Rosa disponibile: ${team.playerCount}</small></div><strong aria-hidden="true">→</strong></a>`}).join("")}</section>`;
const globalLeaderboardValue=value=>Number.isInteger(value)?String(value):Number(value).toFixed(2);
function globalPlayerLeaderboardTable(data,metricId){
  const ranking=data.rankings[metricId];
  if(!ranking)return `<div class="data-warning"><strong>Classifica non disponibile</strong><p>La statistica selezionata non è presente nel dataset.</p></div>`;
  const valueHeaders=ranking.hasPer90?`<th>${esc(ranking.label)} totali</th><th>${esc(ranking.label)} / 90</th>`:"";
  return `<div class="global-leaderboard-caption"><strong>Top 15 · ${esc(ranking.label)}</strong><span>${ranking.availablePlayers} calciatori con dato disponibile</span></div><div class="table-wrap"><table class="global-player-table"><thead><tr><th>#</th><th>Calciatore</th><th>Squadra 2026/27</th><th>Squadra 2025/26</th><th>PG</th><th>Min</th>${valueHeaders}</tr></thead><tbody>${ranking.players.map((player,index)=>{const serieB=player.competition==="Serie B"?'<span class="serie-b-marker" title="Dato prodotto in Serie B 2025/26">* Serie B</span>':"",previousTeam=player.sameClub?'<span class="same-club-marker" title="Stessa squadra della stagione 2026/27">Stesso club</span>':esc(player.previousTeam||"N/D"),valueCells=ranking.hasPer90?`<td><strong class="global-leader-value">${globalLeaderboardValue(player.totalValue)}</strong></td><td><strong class="global-leader-rate">${player.per90Value===null?"N/D":globalLeaderboardValue(player.per90Value)}</strong></td>`:"";return `<tr><td><span class="global-leader-rank">${index+1}</span></td><td><a class="global-leader-player" href="statistiche-squadra/${esc(player.currentTeamId)}.html#squad-results"><span><strong>${esc(player.name)}</strong>${serieB}</span><small>${esc(player.role)}</small></a></td><td>${esc(player.currentTeam)}</td><td>${previousTeam}</td><td>${player.appearances??"N/D"}</td><td>${player.minutes??"N/D"}</td>${valueCells}</tr>`}).join("")}</tbody></table></div>`;
}
function globalPlayerLeaderboards(data){
  const rankings=Object.values(data.rankings),buttons=rankings.map(ranking=>`<button type="button" data-player-stat="${esc(ranking.id)}" class="global-stat-button${ranking.id==="goals"?' active':''}" aria-pressed="${ranking.id==="goals"}">${esc(ranking.label)}</button>`).join("");
  return `<section class="section global-player-leaders" id="top-15-calciatori"><header class="global-player-leaders-heading"><div><p class="eyebrow">Classifiche individuali 2025/26</p><h2>Top 15 calciatori per statistica</h2></div><p>Confronto tra i giocatori presenti nelle 20 rose 2026/27. Il contrassegno “* Serie B” identifica i dati prodotti nel campionato cadetto 2025/26.</p></header><div class="global-leaderboard-controls" aria-label="Seleziona la classifica"><div class="global-stat-group"><strong>Statistiche</strong><div>${buttons}</div></div></div><div id="global-player-leaderboard" aria-live="polite">${globalPlayerLeaderboardTable(data,"goals")}</div><p class="global-leaderboard-note">Le classifiche sono ordinate per valore totale; la relativa media ogni 90 minuti è mostrata nella stessa riga. I valori N/D sono esclusi e la colonna Min aiuta a valutare la dimensione del campione.</p></section>`;
}
const teamNav=(teams,selected="")=>`<nav class="team-nav" aria-label="Calendari delle squadre"><span>Calendario per squadra</span><div>${teams.map(team=>`<a class="team-nav-link ${team.id===selected?'active':''}" href="squadra.html?team=${team.id}" aria-label="Calendario ${esc(team.name)}" title="${esc(team.name)}"><img src="${team.logo}" alt="" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><b hidden>${esc(team.shortName.slice(0,2).toUpperCase())}</b></a>`).join("")}</div></nav>`;
const calendarDays=(league,teams)=>Array.from({length:38},(_,i)=>{const day=i+1,matches=league.filter(m=>m.matchday===day);return `<section class="calendar-day" id="giornata-${day}"><header class="calendar-day-head"><div><p class="eyebrow">Serie A 2026/27</p><h2>Giornata ${day}</h2></div><span>${dateOnly(matches[0]?.matchdayDate)||"Data di riferimento da definire"}</span></header><div class="day-matches">${matches.map(m=>matchCard(m,teams)).join("")}</div></section>`}).join("");
function empty(text){return `<div class="empty">${text}</div>`}
const sampleLabel=matches=>matches<5?"Campione insufficiente":matches<10?"Indicazione moderata":"Confronto più significativo";
function refereeStatsTable(rows,competition){
  const isSerieA=competition==="serieA";
  return `<div class="table-wrap"><table class="referee-stats-table"><thead><tr><th>Arbitro</th><th>Partite</th>${isSerieA?"<th>Gialli</th>":"<th>Falli / gara</th>"}<th>Gialli / gara</th>${isSerieA?"<th>Rossi</th>":""}<th>Rossi / gara</th><th>Campione</th></tr></thead><tbody>${rows.map(row=>{const s=row[competition];return `<tr><td><strong>${esc(row.name)}</strong></td><td>${s.matches}</td>${isSerieA?`<td>${s.yellowCards}</td>`:`<td>${s.foulsPerMatch.toFixed(2)}</td>`}<td>${s.yellowCardsPerMatch.toFixed(2)}</td>${isSerieA?`<td>${s.redCards}</td>`:""}<td>${s.redCardsPerMatch.toFixed(2)}</td><td><span class="sample-label sample-${s.matches<5?'low':s.matches<10?'medium':'strong'}">${sampleLabel(s.matches)}</span></td></tr>`}).join("")}</tbody></table></div>`;
}
function refereeRankings(rows,competition){
  const eligible=rows.filter(row=>row[competition].matches>=5),top=(field,ascending=false)=>[...eligible].sort((a,b)=>(ascending?a[competition][field]-b[competition][field]:b[competition][field]-a[competition][field])||a.name.localeCompare(b.name,"it")).slice(0,5),card=(title,field,ascending=false)=>`<article class="card ranking-card"><h3>${title}</h3><ol>${top(field,ascending).map(row=>`<li><span>${esc(row.name)}</span><strong>${row[competition][field].toFixed(2)}</strong></li>`).join("")}</ol></article>`;return `<div class="ranking-grid">${card("Più gialli / gara","yellowCardsPerMatch")}${card("Meno gialli / gara","yellowCardsPerMatch",true)}${competition==="serieA"?card("Più espulsioni / gara","redCardsPerMatch"):card("Più falli / gara","foulsPerMatch")}</div>`;
}
const competitionLabel=value=>value==="serie-a"?"Serie A":"Serie B";
function pilotRefereeTable(rows){return `<div class="table-wrap"><table class="pilot-referee-table"><thead><tr><th>Competizione</th><th>Arbitro</th><th>Partite</th><th>Falli / gara</th><th>Gialli / gara</th><th>2° gialli</th><th>Rossi diretti</th><th>Rigori / gara</th><th>Attendibilità</th><th>Fonte</th></tr></thead><tbody>${[...rows].sort((a,b)=>a.competition.localeCompare(b.competition)||a.referee.localeCompare(b.referee,"it")).map(row=>`<tr><td><span class="competition-chip">${competitionLabel(row.competition)}</span></td><td><strong>${esc(row.referee)}</strong></td><td>${row.matches}</td><td>${row.foulsPerMatch?.toFixed(2)??"—"}</td><td>${row.yellowCardsPerMatch?.toFixed(2)??"—"}</td><td>${row.secondYellowCards}</td><td>${row.straightRedCards}</td><td>${row.penaltiesPerMatch?.toFixed(2)??"—"}</td><td><span class="sample-label sample-low">${esc(row.reliability)}</span></td><td>${row.fixtureIds.map(id=>`<a class="source-id" href="https://www.espn.com/soccer/match/_/gameId/${esc(id)}" target="_blank" rel="noreferrer">${esc(id)}</a>`).join(" ")}</td></tr>`).join("")}</tbody></table></div>`}
function pilotTeamTable(rows){return `<div class="table-wrap"><table class="pilot-team-table"><thead><tr><th>Competizione</th><th>Arbitro</th><th>Squadra</th><th>Partite</th><th>Falli / gara</th><th>Gialli / gara</th><th>Media altri arbitri</th><th>Confronto</th></tr></thead><tbody>${[...rows].sort((a,b)=>a.competition.localeCompare(b.competition)||a.referee.localeCompare(b.referee,"it")||a.teamName.localeCompare(b.teamName,"it")).map(row=>`<tr><td>${competitionLabel(row.competition)}</td><td><strong>${esc(row.referee)}</strong></td><td>${esc(row.teamName)}</td><td>${row.matches}</td><td>${row.foulsPerMatch?.toFixed(2)??"—"}</td><td>${row.yellowCardsPerMatch?.toFixed(2)??"—"}</td><td>${row.comparison.teamAverageWithOtherReferees?.toFixed(2)??"—"}</td><td><span class="sample-label sample-${row.reliability==="campione insufficiente"?'low':'medium'}">${esc(row.comparison.severity)}</span></td></tr>`).join("")}</tbody></table></div>`}
function pilotSection(aggregates,report){const serieA=report.competitions.find(item=>item.competition==="serie-a"),serieB=report.competitions.find(item=>item.competition==="serie-b"),missing=Object.entries(report.missingFields);return `<section class="section referee-section pilot-section" id="pilot-espn"><p class="eyebrow">Importatore automatico · ESPN</p><h2>Pilot statistiche arbitrali</h2><p class="lead-small">Primo controllo su 10 partite di Serie A e 10 di Serie B 2025/26. I risultati sportivi non sono usati per formulare giudizi di favoritismo.</p><div class="pilot-summary"><article><span>Serie A importate</span><strong>${serieA?.imported??0}/${serieA?.requested??0}</strong></article><article><span>Serie B importate</span><strong>${serieB?.imported??0}/${serieB?.requested??0}</strong></article><article><span>Arbitri analizzati</span><strong>${aggregates.referees.length}</strong></article><article class="${missing.length?'pilot-warning':''}"><span>Campi mancanti</span><strong>${missing.reduce((sum,[,count])=>sum+count,0)}</strong></article></div>${missing.length?`<aside class="pilot-missing"><strong>Copertura del provider</strong><p>${missing.map(([field,count])=>`${esc(field)}: assente in ${count} partite`).join(" · ")}. Gli altri campi richiesti risultano disponibili nel pilot.</p></aside>`:""}<h3 class="pilot-subtitle">Statistiche per arbitro</h3>${pilotRefereeTable(aggregates.referees)}<h3 class="pilot-subtitle">Confronto arbitro-squadra</h3><p class="muted">Con una sola gara per coppia, il confronto resta correttamente classificato come campione insufficiente.</p>${pilotTeamTable(aggregates.refereeTeams)}<p class="referee-note">Dati recuperati ${new Date(report.retrievedAt).toLocaleString("it-IT")} · Provider ESPN · Fixture e fonti consultabili nella tabella.</p></section>`}

const numberCell=value=>value===null||value===undefined?"—":Number(value).toFixed(2);
function fullRefereeTable(rows){return `<div class="table-wrap"><table class="pilot-referee-table"><thead><tr><th>Competizione</th><th>Arbitro</th><th>Partite</th><th>Falli / gara</th><th>Gialli / gara</th><th>2ª ammonizioni</th><th>Rossi diretti</th><th>Rigori</th><th>Campione</th></tr></thead><tbody>${rows.map(row=>`<tr><td>${competitionLabel(row.competition)}</td><td><strong>${esc(row.referee)}</strong></td><td>${row.matches}</td><td>${numberCell(row.foulsPerMatch)}</td><td>${numberCell(row.yellowCardsPerMatch)}</td><td>${row.secondYellowCards}</td><td>${row.straightRedCards}</td><td>${row.penalties}</td><td><span class="sample-label sample-${row.matches<5?'low':row.matches<10?'medium':'strong'}">${esc(row.reliability)}</span></td></tr>`).join("")}</tbody></table></div>`}
function fullTeamTable(rows){return `<div class="table-wrap"><table class="pilot-team-table"><thead><tr><th>Competizione</th><th>Arbitro</th><th>Squadra</th><th>Partite</th><th>Falli / gara</th><th>Gialli / gara</th><th>Media altri arbitri</th><th>Confronto</th><th>Attendibilità</th></tr></thead><tbody>${rows.map(row=>`<tr><td>${competitionLabel(row.competition)}</td><td><strong>${esc(row.referee)}</strong></td><td>${esc(row.teamName)}</td><td>${row.matches}</td><td>${numberCell(row.foulsPerMatch)}</td><td>${numberCell(row.yellowCardsPerMatch)}</td><td>${numberCell(row.comparison.teamAverageWithOtherReferees)}</td><td>${esc(row.comparison.severity)}</td><td><span class="sample-label sample-${row.matches<5?'low':row.matches<10?'medium':'strong'}">${esc(row.reliability)}</span></td></tr>`).join("")}</tbody></table></div>`}
function sourceDifferences(validation){const rows=validation.sourceComparison.rows.filter(row=>row.espn&&Object.values(row.differences).some(value=>value!==0&&value!==null)),totals=validation.sourceComparison.totals||[];return `<section class="section referee-section" id="differenze-fonti"><p class="eyebrow">Riconciliazione</p><h2>Differenze fra le fonti</h2><p class="muted">ESPN, Soccerbase e lo snapshot Serie B restano separati. Le differenze non vengono sovrascritte.</p><h3 class="pilot-subtitle">Totali aggregati di confronto</h3><div class="table-wrap"><table><thead><tr><th>Competizione</th><th>Partite ESPN</th><th>Partite snapshot</th><th>Δ partite</th><th>Δ falli / gara</th><th>Δ gialli / gara</th><th>Δ rossi / gara</th></tr></thead><tbody>${totals.map(row=>`<tr><td>${competitionLabel(row.competition)}</td><td>${row.espn.matches}</td><td>${row.snapshot.matches}</td><td>${row.differences.matches}</td><td>${numberCell(row.differences.foulsPerMatch)}</td><td>${numberCell(row.differences.yellowCardsPerMatch)}</td><td>${numberCell(row.differences.redCardsPerMatch)}</td></tr>`).join("")}</tbody></table></div><p class="muted">Il confronto usa soltanto gli arbitri dell’organico CAN 2026/27 presenti negli snapshot; per questo il totale non coincide necessariamente con tutte le gare.</p><details><summary>Mostra ${rows.length} confronti per arbitro con differenze</summary><div class="table-wrap"><table><thead><tr><th>Competizione</th><th>Arbitro</th><th>Partite ESPN</th><th>Partite snapshot</th><th>Δ gialli / gara</th><th>Δ rossi / gara</th></tr></thead><tbody>${rows.map(row=>`<tr><td>${competitionLabel(row.competition)}</td><td>${esc(row.referee)}</td><td>${row.espn.matches}</td><td>${row.snapshot.matches}</td><td>${numberCell(row.differences.yellowCardsPerMatch)}</td><td>${numberCell(row.differences.redCardsPerMatch)}</td></tr>`).join("")}</tbody></table></div></details><aside class="pilot-missing"><strong>Copertura ESPN</strong><p>${validation.missingFields.referee} partite di Serie A (giornate 35–38) non espongono l’arbitro nell’endpoint ESPN; falli, cartellini e rigori restano disponibili. La lacuna è conservata nel report.</p></aside></section>`}
function fullRefereeSection(aggregates,report,validation){const regular=aggregates.referees.filter(row=>row.stage==="regular-season"&&row.refereeSlug&&row.referee!=="provider:unknown"),current=regular.filter(row=>row.currentCan2026_27),historical=regular.filter(row=>!row.currentCan2026_27),teamRows=aggregates.refereeTeams.filter(row=>row.stage==="regular-season"&&row.referee!=="provider:unknown"),a=report.competitions.find(row=>row.competition==="serie-a"),b=report.competitions.find(row=>row.competition==="serie-b"),stageNames={"playoff-preliminary":"Playoff · preliminare","playoff-semifinal":"Playoff · semifinale","playoff-final":"Playoff · finale",playout:"Playout"};return `<section class="section referee-section" id="statistiche-2025-26"><p class="eyebrow">Importazione completa · ESPN</p><h2>Statistiche arbitrali 2025/26</h2><p class="lead-small">Stagioni regolari complete. Vittorie e sconfitte non sono usate come prova di favoritismi.</p><div class="pilot-summary"><article><span>Serie A regolare</span><strong>${a.regularSeason}/380</strong></article><article><span>Serie B regolare</span><strong>${b.regularSeason}/380</strong></article><article><span>Playoff / playout B separati</span><strong>${b.postseason}</strong></article><article><span>Partite senza giornata associata</span><strong>${validation.missingFields.matchday}</strong></article></div><aside class="pilot-missing"><strong>Campo interessato: matchday</strong><p>Tutte le ${a.regularSeason+b.regularSeason} gare regolari sono associate a una delle 38 giornate.</p></aside><h3 class="pilot-subtitle">Arbitri dell’organico CAN 2026/27</h3>${fullRefereeTable(current)}<h3 class="pilot-subtitle">Arbitri storici non presenti nell’organico 2026/27</h3><p class="muted">Restano nei dati storici con <code>currentCan2026_27: false</code>.</p>${fullRefereeTable(historical)}<h3 class="pilot-subtitle">Confronto arbitro–squadra</h3><p class="muted">0–4 gare: campione insufficiente · 5–9: indicazione moderata · 10 o più: confronto più significativo.</p><details><summary>Mostra tutti i confronti (${teamRows.length})</summary>${fullTeamTable(teamRows)}</details><h3 class="pilot-subtitle">Stage Serie B separati</h3><div class="pilot-summary">${Object.entries(report.stages).filter(([key])=>key.startsWith("serie-b:")&&!key.endsWith("regular-season")).map(([key,count])=>`<article><span>${esc(stageNames[key.split(":")[1]])}</span><strong>${count}</strong></article>`).join("")}</div><p class="referee-note">Dati recuperati ${new Date(report.retrievedAt).toLocaleString("it-IT")} · Fixture ID, URL fonte e retrievedAt registrati in ogni partita.</p></section>${sourceDifferences(validation)}`}

async function render(){
  const page=document.body.dataset.page,[teams,matches,readings,previousStandings,objectiveProfiles]=await Promise.all([load("teams.json"),load("matches.json"),load("readings.json"),load("standings-2025-26.json"),loadObjectiveProfiles()]);let refs=[],refereeFull=null,refereeFullReport=null,refereeValidation=null;if(page==="referees")[refs,refereeFull,refereeFullReport,refereeValidation]=await Promise.all([load("referees.json"),loadGenerated("referee-stats/2025-26/aggregates.json"),loadGenerated("referee-stats/2025-26/import-report.json"),loadGenerated("referee-stats/2025-26/validation-report.json")]);
  let teamDirectory=null,playerLeaderboards=null;if(page==="team-stats")[teamDirectory,playerLeaderboards]=await Promise.all([loadTeamDirectory(),loadPlayerLeaderboards()]);
  const league=matches.filter(m=>m.competition==="serie-a"),cup=matches.filter(m=>m.competition==="coppa-italia"),standings=calculateStandings(teams,matches),standingsTeams=[...teams,...previousStandings.historicalTeams];let html="";
  if(page==="home")html=hero("Stagione ufficiale","Il calcio italiano, giornata dopo giornata.","Tutte le 380 partite della Serie A Enilive 2026/27, con programmazione aggiornata senza inventare date ancora da definire.")+`<section class="section"><h2>Esplora la stagione</h2><div class="grid">${[["calendario.html","Calendario","Tutti gli accoppiamenti delle 38 giornate."],["classifica.html","Classifica","Calcolata automaticamente dai risultati conclusi."],["statistiche-squadre.html","Statistiche squadre","Rendimento generale aggiornato dai risultati ufficiali."]].map(x=>`<a class="card card-link" href="${x[0]}"><h3>${x[1]}</h3><p class="muted">${x[2]}</p></a>`).join("")}</div></section>`;
  if(page==="calendar"){
    html=hero("Serie A","Calendario 2026/27","Tutte le 38 giornate in un'unica pagina. Usa le barre rapide per cercare una giornata o il calendario di una squadra.")+dayNav()+teamNav(teams)+`<div class="calendar-list">${calendarDays(league,teams)}</div>`;
    document.querySelector("#app").innerHTML=html;return;
  }
  if(page==="team"){
    const teamId=new URLSearchParams(location.search).get("team"),team=teams.find(t=>t.id===teamId)||teams[0],teamMatches=league.filter(m=>m.homeTeam===team.id||m.awayTeam===team.id).sort((a,b)=>a.matchday-b.matchday);
    html=hero("Calendario squadra",team.name,`Tutte le 38 partite di ${esc(team.name)}, dalla prima all'ultima giornata.`,`<div class="team-hero-logo"><img src="${team.logo}" alt="Stemma ${esc(team.name)}"></div>`)+teamNav(teams,team.id)+`<section class="section team-schedule"><div class="team-schedule-head"><h2>Le 38 giornate</h2><a class="button" href="calendario.html">Calendario completo</a></div><div class="team-match-list">${teamMatches.map(m=>`<section class="team-matchday">${matchCard(m,teams)}</section>`).join("")}</div></section>`;
    document.title=`${team.name} | Calendario Serie A 2026/27`;document.querySelector("#app").innerHTML=html;return;
  }
  if(page==="standings")html=hero("Serie A","Classifiche","Consulta la stagione in corso, lo stato dinamico degli obiettivi oppure apri l'archivio completo 2025/26.")+`<nav class="standings-switch" aria-label="Selezione stagione"><button type="button" data-standings-tab="current">Classifica 2026/27</button><button type="button" data-standings-tab="archive">Classifica 2025/26</button></nav><div data-standings-panel="current"><section class="section"><p class="eyebrow">Stagione in corso</p><h2>Serie A 2026/27</h2>${standingsTable(standings,standingsTeams)}</section>${objectiveStatusSection(objectiveProfiles,standings,teams)}</div><div data-standings-panel="archive"><section class="section historical-standings"><p class="eyebrow">Archivio</p><h2>Classifica finale 2025/26</h2><p class="muted">Dati forniti dall'utente.</p>${standingsTable(previousStandings.rows,standingsTeams)}<div class="verdicts"><p class="eyebrow">Esito della stagione</p><h2>Verdetti 2025/26</h2>${verdictsPanel(previousStandings.summary.verdicts,standingsTeams,previousStandings.rows)}</div></section><section class="section historical-home-standings"><p class="eyebrow">Archivio · rendimento</p><h2>Serie A 2025/26 · In casa</h2><p class="muted">Classifica calcolata esclusivamente sulle 19 partite casalinghe.</p>${standingsTable(previousStandings.homeRows,standingsTeams)}</section><section class="section historical-away-standings"><p class="eyebrow">Archivio · rendimento</p><h2>Serie A 2025/26 · In trasferta</h2><p class="muted">Classifica calcolata esclusivamente sulle 19 partite in trasferta.</p>${standingsTable(previousStandings.awayRows,standingsTeams)}</section></div>`;
  if(page==="team-stats")html=hero("Serie A 2026/27","Statistiche squadre","Consulta le rose, le statistiche individuali, i valori per 90 minuti e le classifiche dei migliori calciatori.")+`<section class="section team-pages-entry"><p class="eyebrow">Rose 2026/27</p><h2>Scegli la squadra</h2><p>Apri direttamente la scheda con rosa, dati 2025/26, valori per 90 minuti e Top 3.</p></section>${teamDirectoryGrid(teamDirectory)}${globalPlayerLeaderboards(playerLeaderboards)}`;
  if(page==="readings")html=hero("Analisi prepartita","Lettura","Le letture verranno pubblicate senza inventare quote o pronostici.")+`<section class="section">${readings.length?`<div class="grid">${readings.map(r=>`<article class="card"><h3>${esc(r.title)}</h3><p>${esc(r.summary)}</p></article>`).join("")}</div>`:empty("Nessuna lettura pubblicata per la stagione 2026/27.")}</section>`;
  if(page==="cup")html=hero("Eliminazione diretta","Coppa Italia","Il tabellone userà la stessa scheda partita condivisa quando verranno importati gli incontri ufficiali.")+`<section class="section bracket">${cup.length?cup.map(m=>matchCard(m,teams)).join(""):empty("Calendario Coppa Italia non ancora importato.")}</section>`;
  if(page==="referees")html=hero("Organico CAN · stagione 2026/27","Arbitri",`${refs.length} arbitri nell'organico attuale, seguiti dai dati completi 2025/26 e dagli arbitri storici separati.`,`<div class="hero-stat"><strong>${refs.length}</strong><span>arbitri censiti</span></div>`)+`<nav class="referee-nav" aria-label="Sezioni pagina arbitri"><a href="#organico-2026-27"><strong>42</strong><span>Organico 2026/27</span></a><a href="#statistiche-2025-26"><strong>760</strong><span>Gare regolari 2025/26</span></a><a href="#differenze-fonti"><strong>≠</strong><span>Differenze fonti</span></a></nav><section class="section referee-section" id="organico-2026-27"><p class="eyebrow">Nome · Sezione AIA</p><h2>Organico 2026/27</h2><div class="referee-grid">${refs.map((ref,index)=>`<article class="card referee-card" id="${esc(ref.slug)}"><span class="referee-number">${index+1}</span><div><h3>${esc(ref.name)}</h3><p>${esc(ref.section)}</p></div><span class="status">${esc(ref.role)}</span></article>`).join("")}</div></section>${fullRefereeSection(refereeFull,refereeFullReport,refereeValidation)}<aside class="method-note"><strong>Linguaggio neutrale</strong><p>I risultati non sono usati come prova di favoritismi. I confronti descrivono soltanto severità relativa, media e dimensione del campione.</p></aside>`;
  document.querySelector("#app").innerHTML=html;
  if(page==="team-stats"){const controls=document.querySelector(".global-leaderboard-controls"),target=document.querySelector("#global-player-leaderboard");controls.addEventListener("click",event=>{const button=event.target.closest("[data-player-stat]");if(!button)return;controls.querySelectorAll("[data-player-stat]").forEach(item=>{const active=item===button;item.classList.toggle("active",active);item.setAttribute("aria-pressed",String(active))});target.innerHTML=globalPlayerLeaderboardTable(playerLeaderboards,button.dataset.playerStat)})}
  if(page==="standings"){const activate=value=>{document.querySelectorAll("[data-standings-panel]").forEach(panel=>panel.hidden=panel.dataset.standingsPanel!==value);document.querySelectorAll("[data-standings-tab]").forEach(button=>button.classList.toggle("active",button.dataset.standingsTab===value));history.replaceState(null,"",value==="archive"?"#classifica-2025-26":location.pathname)};document.querySelectorAll("[data-standings-tab]").forEach(button=>button.addEventListener("click",()=>activate(button.dataset.standingsTab)));activate(location.hash==="#classifica-2025-26"?"archive":"current")}
}
document.querySelectorAll("[data-page-link]").forEach(a=>a.classList.toggle("active",a.dataset.pageLink===document.body.dataset.page));
const btn=document.querySelector(".menu-button"),nav=document.querySelector(".site-nav");btn.addEventListener("click",()=>{const open=nav.classList.toggle("open");btn.setAttribute("aria-expanded",open)});
render().catch(e=>{document.querySelector("#app").innerHTML=`<section class="empty"><h1>Dati non disponibili</h1><p>${esc(e.message)}</p></section>`;console.error(e)});
