const DATA="data/normalized/";
const labels={scheduled:"Programmata",live:"In corso",finished:"Conclusa",postponed:"Rinviata"};
const esc=v=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
async function load(name){const r=await fetch(DATA+name);if(!r.ok)throw new Error(`${name}: ${r.status}`);return r.json()}
const date=v=>v?new Intl.DateTimeFormat("it-IT",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"Data e ora da definire";
const banner=()=>`<aside class="demo-banner"><strong>Ambiente dimostrativo.</strong> Squadre, date, risultati, arbitri e letture qui presenti sono fittizi e servono soltanto a validare il sistema.</aside>`;
const hero=(eyebrow,title,text,aside="")=>`${banner()}<section class="hero"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="lead">${text}</p></div>${aside}</section>`;
function matchCard(m,teams){const t=id=>teams.find(x=>x.id===id)?.name||id;const score=m.score?`${m.score.home} – ${m.score.away}`:"–";const scorers=m.scorers?.length?`<small class="muted">${m.scorers.map(s=>`${esc(s.player)} ${s.minute}’`).join(" · ")}</small>`:"";return `<article class="card match"><div><span class="status ${m.status}">${labels[m.status]||m.status}</span><div class="muted">${date(m.date)}</div></div><div><div class="match-teams"><span>${esc(t(m.homeTeam))}</span><strong class="score">${score}</strong><span>${esc(t(m.awayTeam))}</span></div>${scorers}</div><div class="actions"><a class="button" href="lettura.html?match=${m.id}">Lettura</a><a class="button" href="statistiche-squadre.html?team=${m.homeTeam}">Statistiche</a></div></article>`}
function table(rows,teams){const name=id=>teams.find(t=>t.id===id)?.name||id;return `<div class="table-wrap"><table><thead><tr><th>#</th><th>Squadra</th><th>PG</th><th>V</th><th>N</th><th>P</th><th>GF</th><th>GS</th><th>DR</th><th>Pt</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(name(r.team))}</td><td>${r.played}</td><td>${r.won}</td><td>${r.drawn}</td><td>${r.lost}</td><td>${r.goalsFor}</td><td>${r.goalsAgainst}</td><td>${r.goalDifference}</td><td><strong>${r.points}</strong></td></tr>`).join("")}</tbody></table></div>`}
async function render(){const page=document.body.dataset.page;const [teams,matches,players,readings,refs]=await Promise.all([load("teams.json"),load("matches.json"),load("players.json"),load("readings.json"),load("referees.json")]);const league=matches.filter(m=>m.competition==="serie-a"),cup=matches.filter(m=>m.competition==="coppa-italia"),standings=calculateStandings(teams,matches);let html="";
 if(page==="home")html=hero("Nuovo progetto autonomo","Il calcio italiano, giornata dopo giornata.","Calendario, classifica, statistiche, arbitri e letture in un sistema statico pensato per aggiornarsi dopo ogni partita.",`<div class="hero-stat"><strong>38</strong><span>giornate previste dal modello</span></div>`)+`<section class="section"><h2>Esplora il prototipo</h2><div class="grid">${[["giornata.html","Giornata","Il centro operativo con gare e classifica parziale."],["classifica.html","Classifica","Calcolata automaticamente dai risultati conclusi."],["coppa-italia.html","Coppa Italia","Turni a eliminazione diretta sullo stesso modello partita."]].map(x=>`<a class="card card-link" href="${x[0]}"><h3>${x[1]}</h3><p class="muted">${x[2]}</p></a>`).join("")}</div></section>`;
 if(page==="matchday")html=hero("Serie A","Giornata 1","Partite concluse, live, programmate e rinviate convivono nello stesso aggiornamento.")+`<section class="section"><div class="selector"><label for="day">Giornata</label><select id="day">${Array.from({length:38},(_,i)=>`<option ${i?'disabled':''}>${i+1}${i?' · dati non importati':''}</option>`).join("")}</select></div>${league.map(m=>matchCard(m,teams)).join("")}</section><section class="section"><h2>Classifica aggiornata</h2>${table(standings,teams)}</section>`;
 if(page==="calendar")html=hero("Serie A","Calendario 2026/27","La struttura supporta anticipi, posticipi, rinvii e orari da definire.")+`<section class="section"><h2>Giornata dimostrativa</h2>${league.map(m=>matchCard(m,teams)).join("")}</section>`;
 if(page==="standings")html=hero("Serie A","Classifica","Generata esclusivamente dalle partite con stato conclusa; può cambiare anche a giornata incompleta.")+`<section class="section">${table(standings,teams)}</section>`;
 if(page==="team-stats")html=hero("Numeri cumulativi","Statistiche squadre","Rendimento generale; casa, trasferta e forma ultime 5/10 saranno alimentati dai dati ufficiali.")+`<section class="section"><h2>Rendimento disponibile</h2>${table(standings,teams)}</section>`;
 if(page==="player-stats")html=hero("Numeri cumulativi","Statistiche giocatori","Presenze, gol, assist e disciplina in una vista condivisa.")+`<section class="section"><div class="table-wrap"><table><thead><tr><th>#</th><th>Giocatore</th><th>Squadra</th><th>Pres.</th><th>Gol</th><th>Assist</th><th>Gialli</th><th>Rossi</th></tr></thead><tbody>${players.map((p,i)=>`<tr><td>${i+1}</td><td>${esc(p.name)}</td><td>${esc(teams.find(t=>t.id===p.team)?.name)}</td><td>${p.appearances}</td><td>${p.goals}</td><td>${p.assists}</td><td>${p.yellowCards}</td><td>${p.redCards}</td></tr>`).join("")}</tbody></table></div></section>`;
 if(page==="readings")html=hero("Analisi prepartita","Lettura","Archivio editoriale distinto per pubblicazione e verifica, senza quote o pronostici reali nel prototipo.")+`<section class="section"><div class="grid">${readings.map(r=>{const m=matches.find(x=>x.id===r.matchId);return `<article class="card"><span class="status ${r.status==='verified'?'finished':'scheduled'}">${r.status==='verified'?'Risultato verificato':'Pubblicata'}</span><h3>${esc(r.title)}</h3><p>${esc(r.summary)}</p><p class="muted">${m?date(m.date):''}</p>${r.predictions.map(p=>`<span class="status ${p.outcome}">${p.outcome==='won'?'Centrato':'Perso'} · ${esc(p.label)}</span>`).join('')}</article>`}).join("")}</div></section>`;
 if(page==="cup")html=hero("Eliminazione diretta","Coppa Italia","Un tabellone dedicato, alimentato dalla stessa scheda partita usata per il campionato.")+`<section class="section bracket">${cup.map(m=>matchCard(m,teams)).join("")}</section>`;
 if(page==="referees")html=hero("Direzione gara","Arbitri","Statistiche aggregate con tracciamento della fonte e distinzione netta dei dati demo.")+`<section class="section"><div class="grid">${refs.map(r=>`<article class="card"><h3>${esc(r.name)}</h3><p>${r.matches} gara · ${r.yellowCards} ammonizioni · ${r.redCards} espulsioni · ${r.penalties} rigori</p><small class="muted">Fonte: ${esc(r.source.label)}</small></article>`).join("")}</div></section>`;
 if(page==="sources")html=hero("Trasparenza","Metodo e fonti","Ogni record importato deve conservare provenienza e data di acquisizione.")+`<section class="section"><div class="grid"><article class="card"><h3>1. Acquisizione</h3><p>Snapshot immutabile in <code>data/raw</code>, preferibilmente da Lega Serie A.</p></article><article class="card"><h3>2. Normalizzazione</h3><p>Campi comuni per campionato e coppa; matchday o stage secondo la competizione.</p></article><article class="card"><h3>3. Generazione</h3><p>Validazione, calcoli e pagine passano da script e sorgenti condivise.</p></article></div><h2 class="section">Fonti del prototipo</h2><ul class="source-list"><li>Dataset dimostrativo interno, creato il 18 luglio 2026. Nessun valore è ufficiale.</li><li>Il progetto Mondiale 2026 è stato consultato soltanto come riferimento visivo e funzionale.</li></ul></section>`;
 document.querySelector("#app").innerHTML=html;}
document.querySelectorAll("[data-page-link]").forEach(a=>a.classList.toggle("active",a.dataset.pageLink===document.body.dataset.page));const btn=document.querySelector(".menu-button"),nav=document.querySelector(".site-nav");btn.addEventListener("click",()=>{const open=nav.classList.toggle("open");btn.setAttribute("aria-expanded",open)});render().catch(e=>{document.querySelector("#app").innerHTML=`<section class="empty"><h1>Dati non disponibili</h1><p>Avvia il sito con un server locale. ${esc(e.message)}</p></section>`;console.error(e)});
