const DATA="data/normalized/",RELEASE="20260804-h2h-readings";
const labels={scheduled:"Programmata",live:"In corso",finished:"Conclusa",postponed:"Rinviata"};
const esc=v=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const contrastInk=color=>{const hex=String(color||"").replace("#","");const value=hex.length===3?hex.split("").map(char=>char+char).join(""):hex;if(!/^[0-9a-f]{6}$/i.test(value))return"#fff";const channels=[0,2,4].map(index=>parseInt(value.slice(index,index+2),16)/255).map(channel=>channel<=.03928?channel/12.92:((channel+.055)/1.055)**2.4);return channels[0]*.2126+channels[1]*.7152+channels[2]*.0722>.42?"#0b1320":"#fff"};
const playerRoleAbbreviations={Portiere:"POR",Difensore:"DC","Difensore centrale":"DC","Difensore centrale destro":"DC","Difensore centrale sinistro":"DC","Terzino destro":"TD","Terzino sinistro":"TS",Centrocampista:"CC","Centrocampista centrale":"CC","Centrocampista centrale destro":"CC","Centrocampista centrale sinistro":"CC",Mediano:"CDC","Mediano / regista":"CDC","Esterno destro":"ED","Esterno sinistro":"ES",Trequartista:"COC","Trequartista destro":"COC","Trequartista sinistro":"COC","Trequartista / ala":"COC",Regista:"COC",Attaccante:"ATT","Seconda punta":"ATT",Centravanti:"ATT","Ala destra":"AD","Ala sinistra":"AS"};
const playerRoleLabel=role=>playerRoleAbbreviations[role]||role||"N/D";
async function load(name){const r=await fetch(`${DATA}${name}?v=${RELEASE}`);if(!r.ok)throw new Error(`${name}: ${r.status}`);return r.json()}
async function loadGenerated(path){const r=await fetch(`data/generated/${path}?v=${RELEASE}`);if(!r.ok)throw new Error(`${path}: ${r.status}`);return r.json()}
async function loadTeamDirectory(){const r=await fetch(`data/teams/index.json?v=${RELEASE}`);if(!r.ok)throw new Error(`data/teams/index.json: ${r.status}`);return r.json()}
async function loadPlayerLeaderboards(){const r=await fetch(`data/teams/player-leaderboards.json?v=${RELEASE}`);if(!r.ok)throw new Error(`data/teams/player-leaderboards.json: ${r.status}`);return r.json()}
async function loadObjectiveProfiles(){const r=await fetch(`data/team-objectives.json?v=${RELEASE}`);if(!r.ok)throw new Error(`data/team-objectives.json: ${r.status}`);return r.json()}
const dateOnly=v=>{if(!v)return null;const [year,month,day]=String(v).slice(0,10).split("-");const months=["gen","feb","mar","apr","mag","giu","lug","ago","set","ott","nov","dic"];return `${Number(day)} ${months[Number(month)-1]} ${year}`};
const scheduleChronology=(left,right)=>{
  const leftDate=String(left.date||left.matchdayDate||"9999-12-31"),rightDate=String(right.date||right.matchdayDate||"9999-12-31");
  return leftDate.localeCompare(rightDate)||String(left.kickoff||"99:99").localeCompare(String(right.kickoff||"99:99"));
};
const matchdayChronology=(left,right)=>(Number(left.matchday)||0)-(Number(right.matchday)||0)||scheduleChronology(left,right);
const hero=(eyebrow,title,text,aside="")=>`<section class="hero"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="lead">${text}</p></div>${document.body.dataset.page==="home"?"":aside}</section>`;
function scheduleLabel(m){
  if(!m.date)return "Data da definire";
  return `${dateOnly(m.date)} · ${m.kickoff||"orario da definire"}${m.dateStatus==="provisional"?" · programmazione provvisoria UEFA":""}`;
}
function teamLogo(team){return `<span class="team-with-logo"><span class="team-logo"><img src="${team.logo}" alt="Stemma ${esc(team.name)}" onerror="this.hidden=true;this.parentElement.classList.add('fallback')"><b>${esc(team.shortName.slice(0,2).toUpperCase())}</b></span><span class="team-name">${esc(team.name)}</span></span>`}
function matchCard(m,teams){
  const home=teams.find(x=>x.id===m.homeTeam),away=teams.find(x=>x.id===m.awayTeam),score=m.score?`${m.score.home} – ${m.score.away}`:"VS";
  const scoreContent=m.score?esc(score):"vs";
  const [homeColor1="#174fa5",homeColor2="#081d48"]=home.colors||[],[awayColor1="#174fa5",awayColor2="#081d48"]=away.colors||[];
  const teamColorStyle=`--home-color-1:${homeColor1};--home-color-2:${homeColor2};--away-color-1:${awayColor1};--away-color-2:${awayColor2}`;
  const status=m.status!=="scheduled"?`<span class="status ${m.status}">${labels[m.status]||m.status}</span>`:"";
  return `<a class="card match fixture-card fixture-card-link" href="lettura.html?match=${esc(m.id)}" aria-label="Apri la lettura di ${esc(home.name)} - ${esc(away.name)}" style="${teamColorStyle}"><header class="match-head"><div class="match-badges"><span class="matchday-chip">Giornata ${m.matchday}</span>${status}${m.dateStatus==="provisional"?'<span class="status provisional">Provvisoria UEFA</span>':''}</div><div class="match-date">${scheduleLabel(m)}</div></header><div class="fixture-teams"><div class="fixture-team fixture-team-home">${teamLogo(home)}</div><div class="fixture-score"><strong class="score ${m.score?'score-result':'score-versus'}">${scoreContent}</strong></div><div class="fixture-team fixture-team-away">${teamLogo(away)}</div></div></a>`
}
function homeMatchListItem(m,teams){
  const home=teams.find(team=>team.id===m.homeTeam),away=teams.find(team=>team.id===m.awayTeam);
  return `<li class="home-match-row"><div class="home-match-meta"><time>${scheduleLabel(m)}</time></div><div class="home-match-teams">${teamLogo(home)}<b aria-hidden="true">–</b>${teamLogo(away)}</div></li>`
}
const standingsColumns=[
  {key:"position",label:"#",title:"Posizione",type:"number",direction:"asc"},
  {key:"teamName",label:"Squadra",title:"Squadra",type:"text",direction:"asc"},
  {key:"points",label:"PT",title:"Punti",type:"number",direction:"desc"},
  {key:"played",label:"PG",title:"Partite giocate",type:"number",direction:"desc"},
  {key:"won",label:"V",title:"Vittorie",type:"number",direction:"desc"},
  {key:"drawn",label:"N",title:"Pareggi",type:"number",direction:"desc"},
  {key:"lost",label:"P",title:"Sconfitte",type:"number",direction:"desc"},
  {key:"goalsFor",label:"GF",title:"Gol fatti",type:"number",direction:"desc"},
  {key:"goalsAgainst",label:"GS",title:"Gol subiti",type:"number",direction:"desc"},
  {key:"goalDifference",label:"DR",title:"Differenza reti",type:"number",direction:"desc"},
  {key:"penaltiesFor",label:"R+",title:"Rigori assegnati a favore",type:"number",direction:"desc"},
  {key:"penaltiesAgainst",label:"R-",title:"Rigori subiti contro",type:"number",direction:"desc"},
  {key:"cardsFor",label:"C+",title:"Cartellini assegnati agli avversari",type:"number",direction:"desc"},
  {key:"cardsAgainst",label:"C-",title:"Cartellini ricevuti dalla squadra",type:"number",direction:"desc"}
];
function standingsTable(rows,teams){
  const teamFor=row=>teams.find(team=>team.id===row.team),name=row=>row.teamName||teamFor(row)?.name||row.team;
  const teamCell=row=>{const team=teamFor(row);return `<span class="standing-team">${team?.logo?`<span class="standing-logo"><img src="${team.logo}" alt="" onerror="this.hidden=true"></span>`:'<span class="standing-logo fallback"></span>'}<span>${esc(name(row))}</span></span>`};
  const value=(row,key,index)=>key==="position"?(row.position||index+1):key==="teamName"?name(row):row[key];
  const display=(key,current)=>current===null||current===undefined?"N/D":key==="goalDifference"&&current>0?`+${current}`:current;
  const head=standingsColumns.map((column,index)=>`<th aria-sort="none"><button class="standings-sort" type="button" data-standings-sort="${column.key}" data-column-index="${index}" data-sort-type="${column.type}" data-default-direction="${column.direction}" title="${column.title}" aria-label="Ordina per ${column.title}">${column.label}</button></th>`).join("");
  const body=rows.map((row,index)=>{const originalPosition=row.position||index+1,zone=originalPosition===1?"standing-zone-champion":originalPosition<=4?"standing-zone-top":originalPosition<=6?"standing-zone-europa":originalPosition===7?"standing-zone-conference":originalPosition>rows.length-3?"standing-zone-bottom":"";return `<tr class="${zone}" data-original-order="${index}">${standingsColumns.map(column=>{const current=value(row,column.key,index),sortValue=current===null||current===undefined?"":current,content=column.key==="teamName"?teamCell(row):column.key==="points"?`<strong>${display(column.key,current)}</strong>`:display(column.key,current);return `<td data-sort-value="${esc(sortValue)}">${content}</td>`}).join("")}</tr>`}).join("");
  return `<div class="table-wrap"><table class="standings-table" data-sortable-standings><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table></div>`;
}
function configureStandingsTables(){
  document.querySelectorAll("[data-sortable-standings]").forEach(table=>{
    const tbody=table.querySelector("tbody"),buttons=[...table.querySelectorAll("[data-standings-sort]")];
    buttons.forEach(button=>button.addEventListener("click",()=>{
      const header=button.closest("th"),active=header.getAttribute("aria-sort"),direction=active==="ascending"?"desc":active==="descending"?"asc":button.dataset.defaultDirection,index=Number(button.dataset.columnIndex),numeric=button.dataset.sortType==="number";
      const rows=[...tbody.querySelectorAll("tr")];
      rows.sort((left,right)=>{const leftValue=left.children[index].dataset.sortValue,rightValue=right.children[index].dataset.sortValue,leftMissing=leftValue==="",rightMissing=rightValue==="";if(leftMissing||rightMissing)return leftMissing===rightMissing?Number(left.dataset.originalOrder)-Number(right.dataset.originalOrder):leftMissing?1:-1;const comparison=numeric?Number(leftValue)-Number(rightValue):leftValue.localeCompare(rightValue,"it",{sensitivity:"base"});return (direction==="asc"?comparison:-comparison)||Number(left.dataset.originalOrder)-Number(right.dataset.originalOrder)});
      buttons.forEach(item=>item.closest("th").setAttribute("aria-sort","none"));
      header.setAttribute("aria-sort",direction==="asc"?"ascending":"descending");
      rows.forEach((row,rowIndex)=>{row.children[0].textContent=String(rowIndex+1);tbody.appendChild(row)});
    }));
  });
}
const signed=value=>`${value>0?"+":""}${value}%`;
function objectiveStatusSection(dataset,rows,teams){
  const profilesById=new Map(dataset.teams.map(profile=>[profile.teamId,profile])),positioned=rows.map((row,index)=>({...row,position:index+1}));
  const cards=teams.map(team=>{const profile=profilesById.get(team.id),row=positioned.find(item=>item.team===team.id);if(!profile)return `<article class="objective-card objective-missing"><header>${teamLogo(team)}<span>Profilo da completare</span></header><p>I valori iniziali per questa squadra non erano presenti nel dataset ricevuto.</p></article>`;const metrics=ObjectiveMetrics.calculateObjectiveMetrics(profile,row,row?.played||0),preseason=metrics.status==="preseason",metric=(label,value,numeric=null,tone="")=>`<div class="objective-metric ${tone}"><span>${label}</span><strong>${value}</strong>${numeric===null?"":`<i class="metric-track" aria-hidden="true"><b style="width:${Math.max(0,Math.min(100,numeric))}%"></b></i>`}</div>`;return `<article class="objective-card"><header>${teamLogo(team)}<span>${preseason?"Valori iniziali":"Aggiornato automaticamente"}</span></header><div class="objective-title"><small>Obiettivo iniziale</small><h3>🏆 ${esc(profile.primaryObjective)}</h3><p>Secondario: ${esc(profile.secondaryObjective)} · posizione obiettivo ${profile.targetPosition}ª</p></div><div class="objective-metrics">${metric("Progresso obiettivo",`${metrics.objectiveProgress}%`,metrics.objectiveProgress)}${metric("Rendimento sulle attese",signed(metrics.seasonOverperformance),null,metrics.seasonOverperformance>0?"positive":metrics.seasonOverperformance<0?"negative":"")}${metric("Motivazione",`${metrics.motivationCurrent}/100`,metrics.motivationCurrent)}${metric("Pressione",`${metrics.pressureCurrent}/100`,metrics.pressureCurrent)}${metric("Urgenza punti",`${metrics.urgency}/100`,metrics.urgency,metrics.urgency>=80?"urgent":"")}</div></article>`}).join("");
  const unused=dataset.teams.filter(profile=>!teams.some(team=>team.id===profile.teamId)).map(profile=>profile.team).join(" · ");
  return `<section class="section objective-section" id="stato-obiettivi"><header class="objective-section-head"><div><p class="eyebrow">Motore dinamico · stagione 2026/27</p><h2>Stato degli obiettivi</h2></div><p>Progresso, rendimento, motivazione, pressione e urgenza vengono ricalcolati dai risultati conclusi. Sono fattori contestuali per la lettura delle partite, non pronostici autonomi.</p></header>${unused?`<aside class="objective-data-note"><strong>Copertura del dataset ricevuto: 17/20 squadre del calendario corrente.</strong> I profili di ${esc(unused)} sono conservati nei dati sorgente ma non appartengono al calendario caricato; Frosinone, Monza e Venezia restano da configurare.</aside>`:""}<div class="objective-grid">${cards}</div><p class="objective-method">A inizio stagione il progresso e lo scostamento sono neutrali; motivazione e pressione coincidono con i valori iniziali. Dopo ogni giornata il calcolo usa posizione, punti, proiezione a 38 gare e distanza dall'obiettivo.</p></section>`;
}
const verdictsPanel=(verdicts,teams,rows)=>{const teamName=id=>teams.find(t=>t.id===id)?.name||rows.find(r=>r.team===id)?.teamName||id;const item=(type,title,ids)=>`<li class="verdict-item ${type}"><span>${title}</span><strong>${ids.map(id=>esc(teamName(id))).join(" · ")}</strong></li>`;return `<ul class="verdict-list">${item("champion","Campione d'Italia",verdicts.champion)}${item("champions","Champions League",verdicts.championsLeague)}${item("europa","Europa League",verdicts.europaLeague)}${item("conference","Conference League",verdicts.conferenceLeague)}${item("relegated","Retrocesse in Serie B",verdicts.relegated)}${item("promoted","Promosse in Serie A 2026/27",verdicts.promoted)}</ul>`};
function homeStandings(standings,previousStandings,objectiveProfiles,teams,standingsTeams){
  return `<section class="section home-standings" id="classifiche"><header class="section-heading"><div><p class="eyebrow">Serie A · classifiche</p><h2>La situazione del campionato</h2></div><p>La stagione in corso e l'archivio completo 2025/26, ora consultabili direttamente dalla Home.</p></header><nav class="standings-switch" aria-label="Selezione stagione"><button type="button" data-standings-tab="current">Classifica 2026/27</button><button type="button" data-standings-tab="archive">Classifica 2025/26</button></nav><div data-standings-panel="current"><section class="section"><p class="eyebrow">Stagione in corso</p><h2>Serie A 2026/27</h2>${standingsTable(standings,standingsTeams)}</section></div><div data-standings-panel="archive"><section class="section historical-standings"><p class="eyebrow">Archivio</p><h2>Classifica finale 2025/26</h2><p class="muted">Dati forniti dall'utente.</p>${standingsTable(previousStandings.rows,standingsTeams)}<div class="verdicts"><p class="eyebrow">Esito della stagione</p><h2>Verdetti 2025/26</h2>${verdictsPanel(previousStandings.summary.verdicts,standingsTeams,previousStandings.rows)}</div></section><section class="section historical-home-standings"><p class="eyebrow">Archivio · rendimento</p><h2>Serie A 2025/26 · In casa</h2><p class="muted">Classifica calcolata esclusivamente sulle 19 partite casalinghe.</p>${standingsTable(previousStandings.homeRows,standingsTeams)}</section><section class="section historical-away-standings"><p class="eyebrow">Archivio · rendimento</p><h2>Serie A 2025/26 · In trasferta</h2><p class="muted">Classifica calcolata esclusivamente sulle 19 partite in trasferta.</p>${standingsTable(previousStandings.awayRows,standingsTeams)}</section></div></section>`;
}
const dayNav=()=>`<nav class="day-nav" aria-label="Selezione rapida giornata"><span>Vai alla giornata</span><div>${Array.from({length:38},(_,i)=>{const day=i+1;return `<a class="day-link" href="#giornata-${day}" aria-label="Giornata ${day}">${day}</a>`}).join("")}</div></nav>`;
const teamDirectoryGrid=data=>`<section class="team-directory-grid team-flip-grid" aria-label="Le 20 squadre">${data.teams.map(team=>{const logo=String(team.monochromeLogo||team.logo||"").replace(/^\.\.\//,""),[primary="#174fa5",secondary="#081d48"]=team.colors||[];return `<a class="team-directory-card team-flip-card" href="statistiche-squadra/${team.id}.html" style="--team-primary:${primary};--team-secondary:${secondary}" aria-label="${esc(team.name)}: apri rosa e statistiche"><span class="team-flip-inner"><span class="team-flip-face team-flip-front"><img src="${esc(logo)}" alt=""></span><span class="team-flip-face team-flip-back"><strong>${esc(team.name)}</strong><span>${team.previousSeason.position?`${team.previousSeason.position}ª posizione · ${team.previousSeason.points} punti`:"Posizione N/D"}</span><span>${esc(team.stadium||"Stadio N/D")}</span><span>Allenatore: ${esc(team.coach||"N/D")}</span><span>Modulo: ${esc(team.preferredFormation||"N/D")}</span><b>Apri scheda</b></span></span></a>`}).join("")}</section>`;
const globalLeaderboardValue=value=>Number.isInteger(value)?String(value):Number(value).toFixed(2);
function globalPlayerLeaderboardTable(data,metricId){
  const ranking=data.rankings[metricId];
  if(!ranking)return `<div class="data-warning"><strong>Classifica non disponibile</strong><p>La statistica selezionata non è presente nel dataset.</p></div>`;
  const valueHeaders=ranking.hasPer90?`<th>${esc(ranking.label)} totali</th><th>${esc(ranking.label)} / 90</th>`:"";
  return `<div class="global-leaderboard-caption"><strong>Top 15 · ${esc(ranking.label)}</strong><span>${ranking.availablePlayers} calciatori con dato disponibile</span></div><div class="table-wrap"><table class="global-player-table"><thead><tr><th>#</th><th>Calciatore</th><th>Squadra 2026/27</th><th>Squadra 2025/26</th><th>PG</th><th>Min</th>${valueHeaders}</tr></thead><tbody>${ranking.players.map((player,index)=>{const serieB=player.competition==="Serie B"?'<span class="serie-b-marker" title="Dato prodotto in Serie B 2025/26">* Serie B</span>':"",previousTeam=player.sameClub?'<span class="same-club-marker" title="Stessa squadra della stagione 2026/27">Stesso club</span>':esc(player.previousTeam||"N/D"),valueCells=ranking.hasPer90?`<td><strong class="global-leader-value">${globalLeaderboardValue(player.totalValue)}</strong></td><td><strong class="global-leader-rate">${player.per90Value===null?"N/D":globalLeaderboardValue(player.per90Value)}</strong></td>`:"";return `<tr><td><span class="global-leader-rank">${index+1}</span></td><td><a class="global-leader-player" href="statistiche-squadra/${esc(player.currentTeamId)}.html#squad-results"><span><strong>${esc(player.name)}</strong>${serieB}</span><small>${esc(playerRoleLabel(player.role))}</small></a></td><td>${esc(player.currentTeam)}</td><td>${previousTeam}</td><td>${player.appearances??"N/D"}</td><td>${player.minutes??"N/D"}</td>${valueCells}</tr>`}).join("")}</tbody></table></div>`;
}
function globalPlayerLeaderboards(data){
  const rankings=Object.values(data.rankings),buttons=rankings.map(ranking=>`<button type="button" data-player-stat="${esc(ranking.id)}" class="global-stat-button${ranking.id==="goals"?' active':''}" aria-pressed="${ranking.id==="goals"}">${esc(ranking.label)}</button>`).join("");
  return `<section class="section global-player-leaders" id="top-15-calciatori"><header class="global-player-leaders-heading"><div><p class="eyebrow">Classifiche individuali 2025/26</p><h2>Top 15 calciatori per statistica</h2></div><p>Confronto tra i giocatori presenti nelle 20 rose 2026/27. Il contrassegno “* Serie B” identifica i dati prodotti nel campionato cadetto 2025/26.</p></header><div class="global-leaderboard-controls" aria-label="Seleziona la classifica"><div class="global-stat-group"><strong>Statistiche</strong><div>${buttons}</div></div></div><div id="global-player-leaderboard" aria-live="polite">${globalPlayerLeaderboardTable(data,"goals")}</div><p class="global-leaderboard-note">Le classifiche sono ordinate per valore totale; la relativa media ogni 90 minuti è mostrata nella stessa riga. I valori N/D sono esclusi e la colonna Min aiuta a valutare la dimensione del campione.</p></section>`;
}
const teamNav=(teams,selected="")=>`<nav class="team-nav" aria-label="Calendari delle squadre"><span>Calendario per squadra</span><div>${teams.map(team=>`<a class="team-nav-link ${team.id===selected?'active':''}" data-team="${team.id}" href="squadra.html?team=${team.id}" aria-label="Calendario ${esc(team.name)}" title="${esc(team.name)}"><img src="${esc(team.logo)}" alt="" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><b hidden>${esc(team.shortName.slice(0,2).toUpperCase())}</b></a>`).join("")}</div></nav>`;
const calendarDays=(league,teams)=>Array.from({length:38},(_,i)=>{const day=i+1,matches=league.filter(m=>m.matchday===day).sort(scheduleChronology);return `<section class="calendar-day" id="giornata-${day}" data-calendar-day="${day}"><header class="calendar-day-head"><div><p class="eyebrow">Serie A 2026/27</p><h2>Giornata ${day}</h2></div><span>${dateOnly(matches[0]?.matchdayDate)||"Data di riferimento da definire"}</span></header><div class="day-matches">${matches.map(m=>`<div data-calendar-teams="${m.homeTeam} ${m.awayTeam}">${matchCard(m,teams)}</div>`).join("")}</div></section>`}).join("");
function empty(text){return `<div class="empty">${text}</div>`}
const readingModules=[
  ["context","01","Contesto e posta in gioco","Classifica, obiettivi stagionali, momento e peso della partita."],
  ["form","02","Forma e numeri","Rendimento recente, casa/trasferta e indicatori con campione dichiarato."],
  ["availability","03","Disponibilita e probabili scelte","Assenze, rientri, rotazioni e formazioni soltanto se verificati."],
  ["tactics","04","Chiavi tattiche","Strutture, duelli, spazi e possibili adattamenti delle due squadre."],
  ["referee","05","Arbitro e disciplina","Designazione, profilo disciplinare e compatibilita con il tipo di gara."],
  ["market","06","Mercato e quote","Movimenti delle quote e mercati utili, sempre con orario e fonte."],
  ["synthesis","07","Sintesi e scenari","Segnali favorevoli, contrari e condizioni che possono cambiare la lettura."]
];
const readingField=section=>section?.content?`<div class="reading-content"><p>${esc(section.content)}</p>${section.signals?.length?`<ul>${section.signals.map(signal=>`<li>${esc(signal)}</li>`).join("")}</ul>`:""}</div>`:`<div class="reading-missing"><strong>N/D</strong><span>Sezione da compilare con dati verificati.</span></div>`;
function readingFixtureLink(match,teams,reading,prediction,history){
  const home=teams.find(team=>team.id===match.homeTeam),away=teams.find(team=>team.id===match.awayTeam);
  const likelyScore=prediction?.exactScores?.[0]?.score;
  const preview=prediction?`<span class="reading-fixture-preview" aria-label="Anteprima della lettura"><span><small>Verdetto</small><strong>${esc(prediction.verdict.label)}</strong></span><span><small>Risultato</small><strong>${esc(likelyScore||"N/D")}</strong></span><span><small>Confidenza</small><strong>${prediction.confidence.value}/100</strong></span></span>`:reading?.summary?`<span class="reading-fixture-preview reading-fixture-preview-text"><span><small>Anteprima</small><strong>${esc(reading.summary)}</strong></span></span>`:"";
  const historyState=history?`<span class="reading-fixture-history ${history.coverage.available<5?"is-limited":""}">Precedenti ${history.coverage.available}/5</span>`:"";
  return `<a class="reading-fixture" href="lettura.html?match=${esc(match.id)}"><span class="reading-fixture-meta">Giornata ${match.matchday} · ${scheduleLabel(match)}</span><span class="reading-fixture-teams">${teamLogo(home)}<b>VS</b>${teamLogo(away)}</span>${preview}<span class="reading-fixture-state ${prediction?"prediction-ready":reading?.status||"structure"}">${prediction?`Pronostico preliminare · sorpresa ${prediction.surprise.value}/100`:reading?.status==="published"?"Pubblicata":reading?.status==="draft"?"Bozza":"Struttura pronta"}</span>${historyState}</a>`;
}
function readingIndex(readings,matches,teams,predictions=[],headToHeadData){
  const scheduled=matches.filter(match=>match.competition==="serie-a"&&match.status!=="finished").sort((a,b)=>a.matchday-b.matchday||String(a.date||a.matchdayDate).localeCompare(String(b.date||b.matchdayDate)));
  const nextDay=scheduled[0]?.matchday,nextMatches=scheduled.filter(match=>match.matchday===nextDay),byMatch=new Map(readings.map(reading=>[reading.matchId,reading])),predictionByMatch=new Map(predictions.map(prediction=>[prediction.matchId,prediction])),historyByMatch=new Map((headToHeadData?.fixtures||[]).map(fixture=>[fixture.fixtureId,fixture]));
  const firstLeg=scheduled.filter(match=>match.matchday<=19),matchdays=[...new Set(firstLeg.map(match=>match.matchday))];
  const directory=matchdays.map(matchday=>`<details class="reading-h2h-matchday"${matchday===nextDay?" open":""}><summary><span>Giornata ${matchday}</span><small>10 partite · storico H2H collegato</small></summary><div class="reading-fixture-grid">${firstLeg.filter(match=>match.matchday===matchday).map(match=>readingFixtureLink(match,teams,byMatch.get(match.id),predictionByMatch.get(match.id),historyByMatch.get(match.id))).join("")}</div></details>`).join("");
  return hero("Analisi prepartita","Letture","Il modello stima prima le probabilità da storico, rendimento e matchup tattico. Le quote vengono confrontate soltanto dopo, per misurare prezzo ed eventuale valore.")+`<section class="section"><header class="section-heading"><div><p class="eyebrow">Prossimo turno</p><h2>Giornata ${nextDay||"N/D"}</h2></div><p>Apri una partita per probabilità, quote eque, scenari e mercati disponibili.</p></header>${nextMatches.length?`<div class="reading-fixture-grid">${nextMatches.map(match=>readingFixtureLink(match,teams,byMatch.get(match.id),predictionByMatch.get(match.id),historyByMatch.get(match.id))).join("")}</div>`:empty("Nessuna partita programmata.")}</section><section class="section reading-h2h-directory"><header class="section-heading"><div><p class="eyebrow">Girone d'andata completo</p><h2>Precedenti per tutte le 190 partite</h2></div><p>Apri una giornata e poi la singola lettura per marcatori e ammoniti degli ultimi cinque confronti disponibili.</p></header><div class="reading-h2h-matchdays">${directory}</div></section>`;
}
function readingDetail(match,reading,teams){
  const home=teams.find(team=>team.id===match.homeTeam),away=teams.find(team=>team.id===match.awayTeam),sections=reading?.sections||{},completed=readingModules.filter(([key])=>sections[key]?.content).length;
  const title=reading?.title||`${home.name} - ${away.name}`;
  return `<nav class="reading-back"><a href="lettura.html">← Tutte le letture</a><a href="calendario.html#giornata-${match.matchday}">Giornata ${match.matchday}</a></nav><section class="reading-match-hero"><div><p class="eyebrow">Serie A · Giornata ${match.matchday}</p><h1>${esc(title)}</h1><p>${scheduleLabel(match)}</p><span class="reading-progress">${completed}/7 sezioni compilate</span></div><div class="reading-matchup">${teamLogo(home)}<b>VS</b>${teamLogo(away)}</div></section>${reading?.summary?`<aside class="reading-summary"><span>Sintesi editoriale</span><p>${esc(reading.summary)}</p></aside>`:""}<section class="section reading-detail"><header class="section-heading"><div><p class="eyebrow">Scheda di lavoro</p><h2>Struttura della lettura</h2></div><p>I campi non ancora verificati restano N/D.</p></header><div class="reading-module-grid">${readingModules.map(([key,number,moduleTitle,description])=>`<article class="reading-module" id="lettura-${key}"><header><span>${number}</span><div><h3>${moduleTitle}</h3><p>${description}</p></div></header>${readingField(sections[key])}${sections[key]?.sources?.length?`<footer>${sections[key].sources.map(source=>`<a href="${esc(source.url)}" target="_blank" rel="noreferrer">${esc(source.label||"Fonte")}</a>`).join(" · ")}</footer>`:""}</article>`).join("")}</div></section>`;
}
function headToHeadPanel(history,prediction){
  if(!history)return `<section class="section reading-h2h-section"><aside class="data-warning"><strong>Precedenti N/D</strong><p>Nessun dataset storico collegato a questa partita.</p></aside></section>`;
  const meetings=history.previousMeetings||[],available=history.coverage?.available??meetings.length;
  const eventList=(items,emptyLabel)=>items?.length?`<ul>${items.map(item=>`<li><strong>${esc(item.player)}</strong><small>${esc(item.team)} · ${esc(item.minute||"minuto N/D")}${item.ownGoal?" · autogol":""}</small></li>`).join("")}</ul>`:`<p class="reading-h2h-empty">${emptyLabel}</p>`;
  const cards=meeting=>{const gap=meeting.coverage?.missingFields?.includes("bookingEvents");if(!meeting.bookings?.length)return `<p class="reading-h2h-empty">${gap?"Dettaglio ammoniti N/D":"Nessun ammonito registrato"}</p>`;return `${eventList(meeting.bookings,"Nessun ammonito registrato")}${gap?'<small class="reading-h2h-warning">Conteggio ESPN non riconciliato: sono mostrati soltanto gli eventi nominativi disponibili.</small>':""}`};
  const goals=meeting=>{const gap=meeting.coverage?.missingFields?.includes("goalEvents");if(!meeting.goals?.length)return `<p class="reading-h2h-empty">${gap?"Dettaglio marcatori N/D":"Nessun gol"}</p>`;return eventList(meeting.goals,"Nessun gol")};
  const rows=meetings.map((meeting,index)=>`<details class="reading-h2h-match"${index===0?" open":""}><summary><span>${dateOnly(meeting.date)} · ${esc(meeting.competition)}</span><strong>${esc(meeting.homeTeam.name)} ${meeting.score.home}-${meeting.score.away} ${esc(meeting.awayTeam.name)}</strong></summary><div class="reading-h2h-events"><section><h3>Marcatori</h3>${goals(meeting)}</section><section><h3>Ammoniti</h3>${cards(meeting)}</section></div><a href="${esc(meeting.source.url)}" target="_blank" rel="noreferrer">Fonte ESPN</a></details>`).join("");
  const model=prediction?.headToHead?.usedInModel?`<aside class="reading-h2h-model"><strong>Uso nel modello</strong><p>Correttivo leggero sui gol attesi: fattore casa ${prediction.headToHead.home.toFixed(3)}, fattore ospite ${prediction.headToHead.away.toFixed(3)}. L'effetto è limitato al 5% per lato e non sostituisce forma, rendimento o matchup tattico.</p></aside>`:"";
  return `<section class="section reading-h2h-section"><header class="section-heading"><div><p class="eyebrow">Storico ufficiale · ESPN</p><h2>Ultimi ${available} scontri diretti disponibili</h2></div><p>${available}/5 precedenti · Serie A, Serie B e Coppa Italia</p></header>${available<5?`<aside class="data-warning"><strong>Campione storico limitato</strong><p>Il provider espone ${available} confronti per questa coppia; quelli mancanti non vengono ricostruiti.</p></aside>`:""}<div class="reading-h2h-list">${rows}</div>${model}</section>`;
}
const sampleLabel=matches=>matches<5?"Campione insufficiente":matches<10?"Indicazione moderata":"Confronto più significativo";
function readingPrototypeDetail(match,reading,teams,teamDirectory,objectiveProfiles,prediction,history){
  const home=teams.find(team=>team.id===match.homeTeam),away=teams.find(team=>team.id===match.awayTeam);
  const directoryTeams=teamDirectory?.teams||[],homeMeta=directoryTeams.find(team=>team.id===home.id)||{},awayMeta=directoryTeams.find(team=>team.id===away.id)||{};
  const objectives=objectiveProfiles?.teams||[],homeObjective=objectives.find(profile=>profile.teamId===home.id),awayObjective=objectives.find(profile=>profile.teamId===away.id);
  const previousCard=(team,meta,objective)=>`<article class="reading-evidence-card">${teamLogo(team)}<dl><div><dt>Stagione 2025/26</dt><dd>${meta.previousSeason?.position?`${meta.previousSeason.position}ª · ${esc(meta.previousSeason.competition)} · ${meta.previousSeason.points} pt`:"N/D"}</dd></div><div><dt>Obiettivo 2026/27</dt><dd>${esc(objective?.primaryObjective||"N/D")}${objective?.targetPosition?` · target ${objective.targetPosition}ª`:""}</dd></div><div><dt>Sistema di riferimento</dt><dd>${esc(meta.preferredFormation||"N/D")}</dd></div></dl></article>`;
  const unavailable=(label,note)=>`<div class="reading-unavailable"><span>${label}</span><strong>N/D</strong><small>${note}</small></div>`;
  const duplicatePanels=new Set(["Campo","Dati disponibili"]);
  const dataPanel=(label,body,className="")=>duplicatePanels.has(label)?"":`<section class="reading-data-panel ${className}"><span>${label}</span>${body}</section>`;
  const missingRisks=prediction?.dataQuality?.missing?.map(item=>`${item}: N/D`)||["Dati prepartita non disponibili: N/D"];
  const probability=outcome=>prediction?.probabilities?.final?.[outcome]??"N/D",scores=prediction?.exactScores||[],orderedScores=scores;
  const dominantBand=prediction?.scoreProfile?.bands?.find(band=>band.id===prediction.scoreProfile.dominantBand);
  const summary=prediction?`<section class="reading-summary reading-summary-prototype prediction-summary"><div class="reading-exact-scores"><span>Punteggi modali · non risultato certo</span><div class="reading-score-list">${orderedScores.map((item,index)=>`<div class="${index===0?"is-central":""}"><strong>${esc(item.score)}</strong><small>${index===0?"Moda":"Alternativa"} · ${item.probabilityPct}%</small></div>`).join("")}</div><small class="reading-score-coverage">I primi tre coprono ${prediction.scoreProfile.topThreeCoveragePct}% · fascia prevalente ${esc(dominantBand?.label||"N/D")} (${dominantBand?.probabilityPct??"N/D"}%).</small></div><div class="reading-final-verdict"><span>Verdetto preliminare</span><strong>${esc(prediction.verdict.outcome)} · ${esc(prediction.verdict.label)}</strong><small>Doppia chance ${esc(prediction.verdict.doubleChance)} · confidenza ${prediction.confidence.value}/100</small></div></section>`:`<section class="reading-summary reading-summary-prototype"><div><span>Pronostico</span><strong>N/D</strong><small>Calcolo non disponibile</small></div></section>`;
  const validation=prediction?.modelValidation;
  const enginePanel=prediction?`<section class="section prediction-engine-panel"><header class="section-heading"><div><p class="eyebrow">Modello indipendente · versione ${esc(prediction.engineVersion)}</p><h2>Probabilità 1X2 e gol attesi</h2></div><p>Aggiornato al ${esc(prediction.dataQuality.updatedAt)} · quote escluse dalla stima.</p></header><div class="prediction-metrics"><article><span>1</span><strong>${probability("1")}%</strong></article><article><span>X</span><strong>${probability("X")}%</strong></article><article><span>2</span><strong>${probability("2")}%</strong></article><article><span>xG ${esc(home.name)}</span><strong>${prediction.expectedGoals.home}</strong><small>Totale ${prediction.expectedGoals.total}</small></article><article><span>xG ${esc(away.name)}</span><strong>${prediction.expectedGoals.away}</strong><small>Matrice punteggi calibrata</small></article><article class="prediction-surprise"><span>Fattore sorpresa · ${esc(prediction.surprise.level)}</span><strong>${prediction.surprise.value}/100</strong><small>Esito sorpresa ${esc(prediction.surprise.upsetOutcome)} · ${prediction.surprise.upsetProbabilityPct}%</small></article><article><span>Confidenza · ${esc(prediction.confidence.level)}</span><strong>${prediction.confidence.value}/100</strong><small>Completezza dati ${prediction.dataQuality.completenessPct}%</small></article></div><p class="objective-method">Forze relative casa/trasferta, ultime otto gare corrette per avversario, matchup e probabili XI determinano le λ. La frequenza empirica 2025/26 corregge l'eccesso Poisson dei punteggi bassi; obiettivi e motivazioni restano marginali.</p>${validation?`<p class="objective-method"><strong>Verifica fuori campione:</strong> ${validation.matches} gare del girone di ritorno 2025/26 · log-loss 1X2 ${validation.oneXTwoLogLoss} · accuratezza ${validation.oneXTwoAccuracyPct}%. È un controllo del nucleo statistico, non una garanzia sul singolo incontro.</p>`:""}</section>`:"";
  const quoteBody=prediction?`<dl class="reading-stat-list">${["1","X","2"].map(outcome=>`<div><dt>${outcome}</dt><dd>${prediction.market.selections[outcome].odds.toFixed(2)} <small>mercato ${prediction.probabilities.marketNoMargin[outcome]}%</small></dd></div>`).join("")}</dl><small><a href="${esc(prediction.market.sourceUrl)}" target="_blank" rel="noreferrer">Quote Sisal</a> · snapshot ${esc(prediction.market.retrievedAt.slice(0,10))} · overround 1X2 ${prediction.market.overroundPct}%.</small>`:`<div class="reading-panel-empty"><strong>N/D</strong><p>Nessun mercato importato.</p></div>`;
  const rangeText=metric=>metric?`${metric.central} <small>${metric.min}–${metric.max}</small>`:"N/D",channelLabel=channel=>channel==="left"?"Fascia sinistra":channel==="right"?"Fascia destra":"Zona centrale";
  const projectionCard=projection=>{const team=teams.find(item=>item.id===projection.teamId);return `<article class="prediction-team-volume">${teamLogo(team)}<div class="prediction-volume-metrics"><div><span>Gol attesi</span><strong>${projection.expectedGoals}</strong></div><div><span>Tiri totali</span><strong>${rangeText(projection.shotsTotal)}</strong></div><div><span>Tiri nello specchio</span><strong>${rangeText(projection.shotsOnTarget)}</strong></div><div><span>Corner</span><strong>${rangeText(projection.corners)}</strong></div><div><span>Falli</span><strong>${rangeText(projection.fouls)}</strong></div><div><span>Cartellini</span><strong>${rangeText(projection.cards)}</strong></div></div><div class="prediction-channels"><span>Direzioni d'attacco</span>${[["left","Sinistra"],["central","Centro"],["right","Destra"]].map(([key,label])=>`<div><small>${label}</small><i><b style="width:${projection.attackChannels[key]}%"></b></i><strong>${projection.attackChannels[key]}%</strong></div>`).join("")}<em>Canale prevalente: ${channelLabel(projection.attackChannels.dominant)}</em></div></article>`};
  const bookedPanel=prediction?`<section class="prediction-booked-panel"><header><div><p class="eyebrow">Gerarchia disciplinare</p><h2>5 probabili ammoniti</h2></div><p>Graduatoria unica: entrambe le squadre possono essere rappresentate senza quote giocatore.</p></header><ol>${prediction.likelyBooked.map(candidate=>{const team=teams.find(item=>item.id===candidate.teamId);return `<li class="${candidate.possibleFirstBooked?"possible-first-booked":""}"><span>${candidate.rank}</span><div><strong>${esc(candidate.name)}</strong><small>${esc(team?.name||candidate.teamId)} · ${esc(candidate.role)}${candidate.possibleFirstBooked?" · possibile primo ammonito":""}</small><em>${candidate.evidence.map(esc).join(" · ")}</em></div><b>${candidate.riskScore}/100</b></li>`}).join("")}</ol></section>`:"";
  const mvpPanel=prediction?`<aside class="prediction-mvp"><p class="eyebrow">Candidato MVP</p><strong>${esc(prediction.mvpCandidate.name)}</strong><span>${esc(teams.find(item=>item.id===prediction.mvpCandidate.teamId)?.name||prediction.mvpCandidate.teamId)} · ${esc(prediction.mvpCandidate.role)}</span><ul>${prediction.mvpCandidate.evidence.map(item=>`<li>${esc(item)}</li>`).join("")}</ul><small>Confidenza ${esc(prediction.mvpCandidate.confidence)} · valutazione preliminare</small></aside>`:"";
  const extendedPanel=prediction?`<section class="section reading-projection-prototype prediction-volume-section"><header class="section-heading"><div><p class="eyebrow">Proiezione per squadra</p><h2>Gol, tiri, specchio, corner, falli e cartellini</h2></div><p>Valore centrale con intervallo prudenziale.</p></header><div class="prediction-volume-grid">${prediction.teamProjections.map(projectionCard).join("")}</div><p class="objective-method">I cartellini hanno intervallo più ampio perché l'arbitro non è ancora designato. Dove la base storica non è disponibile il valore resta N/D.</p><div class="prediction-players-grid">${bookedPanel}${mvpPanel}</div></section>`:`<section class="section reading-projection-prototype"><h2>Proiezioni in preparazione</h2></section>`;
  const marketRow=row=>`<tr><td><strong>${esc(row.market)}</strong><small>${row.tier?`${esc(row.tier)} · `:""}${esc(row.selection)}</small></td><td>${row.odds.toFixed(2)}</td><td>${row.modelProbabilityPct}%</td><td>${row.fairOdds.toFixed(2)}</td><td>${row.marketNoMarginPct}%</td><td class="${row.edgePct>0?"positive":"negative"}">${row.edgePct>0?"+":""}${row.edgePct}%</td><td class="${row.expectedValuePct>0?"positive":"negative"}">${row.expectedValuePct>0?"+":""}${row.expectedValuePct}%</td><td>${esc(row.confidence)}</td></tr>`;
  const selectedMarkets=prediction?[...(prediction.recommendations.primary||[]).map(row=>({...row,tier:"Principale"})),...(prediction.recommendations.secondary||[]).map(row=>({...row,tier:"Secondario"}))]:[];
  const recommendationPanel=prediction?`<section class="section prediction-market-section"><header class="section-heading"><div><p class="eyebrow">Confronto con le quote</p><h2>Pronostici principali e secondari</h2></div><p>Value solo se l'EV prudenziale resta positivo.</p></header>${selectedMarkets.length?`<div class="table-wrap"><table class="prediction-market-table"><thead><tr><th>Mercato</th><th>Quota</th><th>Modello</th><th>Quota equa</th><th>Mercato no-margin</th><th>Edge</th><th>EV</th><th>Confidenza</th></tr></thead><tbody>${selectedMarkets.map(marketRow).join("")}</tbody></table></div>`:`<aside class="method-note"><strong>Nessun value principale robusto</strong><p>Le quote disponibili non superano contemporaneamente controllo prudenziale, completezza dei dati e stabilità alle variazioni del modello.</p></aside>`}<details><summary>Mostra il confronto completo di ${prediction.marketComparison.length} selezioni quotate</summary><div class="table-wrap"><table class="prediction-market-table"><thead><tr><th>Mercato</th><th>Quota</th><th>Modello</th><th>Quota equa</th><th>Mercato no-margin</th><th>Edge</th><th>EV</th><th>Confidenza</th></tr></thead><tbody>${prediction.marketComparison.map(marketRow).join("")}</tbody></table></div></details><aside class="prediction-player-market"><strong>Mercati giocatore · ${esc(prediction.playerMarkets.status)}</strong><p>${esc(prediction.playerMarkets.reason)}</p></aside></section>`:"";
  const scenariosPanel=prediction?`<section class="section prediction-scenarios"><header class="section-heading"><div><p class="eyebrow">Tre sviluppi possibili</p><h2>Scenari della partita</h2></div><p>Gli eventi correlati cambiano insieme.</p></header><div class="prediction-scenario-grid">${prediction.scenarios.map(scenario=>`<article><span>${esc(scenario.id)}</span><h3>${esc(scenario.label)}</h3><p>${esc(scenario.description)}</p><dl><div><dt>Migliorano</dt><dd>${esc(scenario.improves)}</dd></div><div><dt>Peggiorano</dt><dd>${esc(scenario.worsens)}</dd></div></dl></article>`).join("")}</div></section>`:"";
  const myComboBody=prediction?.combinations?.length?`<div class="prediction-combos">${prediction.combinations.map(combo=>`<article><span>${esc(combo.tier)} · rischio ${esc(combo.risk)}</span><strong>${esc(combo.selection)} @ ${combo.odds.toFixed(2)}</strong><small>Probabilità prudenziale ${combo.prudentProbabilityPct}% · EV prudenziale ${combo.prudentExpectedValuePct>0?"+":""}${combo.prudentExpectedValuePct}%</small><p>${esc(combo.logic)}</p></article>`).join("")}</div>`:`<div class="reading-panel-empty"><strong>N/D</strong><p>Nessuna combinazione supera il controllo prudenziale con le quote disponibili.</p></div>`;
  return `<nav class="reading-back"><a href="lettura.html">← Tutte le letture</a><a href="calendario.html#giornata-${match.matchday}">Giornata ${match.matchday}</a></nav><section class="reading-match-hero"><div><p class="eyebrow">Serie A · Giornata ${match.matchday} · preliminare</p><h1>${esc(home.name)} - ${esc(away.name)}</h1><p>${scheduleLabel(match)} · ${esc(homeMeta.stadium||"Stadio N/D")}</p><span class="reading-progress">Analisi aggiornata al ${esc(prediction?.dataQuality?.updatedAt||"N/D")}</span></div><div class="reading-matchup">${teamLogo(home)}<b>VS</b>${teamLogo(away)}</div></section>${summary}${enginePanel}${headToHeadPanel(history,prediction)}<aside class="reading-prototype-banner"><strong>Pronostico preliminare, non garanzia</strong><p>Le quote sono un controllo esterno. Formazioni, indisponibili, arbitro e meteo saranno ricalcolati quando verificabili vicino alla gara.</p></aside><section class="section reading-info-grid"><article class="round16-info-box round16-formations"><span>1</span><h2>Sistemi di riferimento</h2><div class="reading-base-shape"><strong>${esc(home.name)} · ${esc(homeMeta.preferredFormation||"N/D")}</strong><p>Allenatore: ${esc(homeMeta.coach||"N/D")}</p></div><div class="reading-base-shape"><strong>${esc(away.name)} · ${esc(awayMeta.preferredFormation||"N/D")}</strong><p>Allenatore: ${esc(awayMeta.coach||"N/D")}</p></div></article><div class="reading-context-rail" aria-label="Contesto squadre">${previousCard(home,homeMeta,homeObjective)}${previousCard(away,awayMeta,awayObjective)}</div></section>${extendedPanel}${recommendationPanel}${scenariosPanel}<section class="section reading-panel-grid">${dataPanel("Quote 1X2",quoteBody)}${dataPanel("MyCombo",myComboBody)}${dataPanel("Dati mancanti",`<ul class="reading-picks">${missingRisks.map(risk=>`<li>${esc(risk)}</li>`).join("")}</ul>`,"reading-data-panel-wide")}</section><section class="section reading-verdict-prototype"><p class="eyebrow">Verdetto preliminare</p><h2>${prediction?esc(prediction.verdict.label):"In attesa del calcolo"}</h2><p>${prediction?`Esito ${esc(prediction.verdict.outcome)} al ${probability(prediction.verdict.outcome)}%. La confidenza misura robustezza (${prediction.confidence.value}/100), non certezza.`:"Dati insufficienti."}</p></section>`;
}
function renderProbableLineups(match,teamDirectory,prediction){
  if(!match||!teamDirectory)return;
  const meta=id=>teamDirectory.teams.find(team=>team.id===id),home=meta(match.homeTeam),away=meta(match.awayTeam);
  const card=team=>{const lineup=team?.probableLineup;if(!lineup)return"";const shape=lineup.formation.split("-").map(Number),units=[1,...shape];let offset=0;const rows=units.map(size=>{const players=lineup.players.slice(offset,offset+size);offset+=size;return `<div class="reading-lineup-row" style="--reading-lineup-count:${size}">${players.map(player=>`<strong>${esc(player)}</strong>`).join("")}</div>`}).reverse().join("");const [primary="#174fa5",secondary="#081d48"]=team.colors||[];return `<article class="reading-lineup-card" style="--reading-lineup-primary:${esc(primary)};--reading-lineup-secondary:${esc(secondary)};--reading-lineup-head-ink:${contrastInk(secondary)}"><header><span>${esc(team.name)}</span><strong>${esc(lineup.formation)}</strong></header><div class="reading-lineup-field" aria-label="Probabile formazione ${esc(team.name)} con modulo ${esc(lineup.formation)}"><i class="reading-lineup-centre" aria-hidden="true"></i>${rows}</div><footer>Allenatore: ${esc(team.coach||"N/D")}</footer></article>`};
  const target=document.querySelector(".round16-formations");
  if(target)target.innerHTML=`<span>1</span><h2>Probabili formazioni</h2><div class="reading-lineup-grid">${card(home)}${card(away)}</div><small>Proiezione della prima giornata, aggiornata il 3 agosto 2026. Non è una distinta ufficiale. <a href="${esc(home?.probableLineup?.source?.url||away?.probableLineup?.source?.url||"#")}" target="_blank" rel="noreferrer">Fonte Calciomercato.com</a></small>`;
  const banner=document.querySelector(".reading-prototype-banner p");if(banner)banner.textContent="La scheda include ora le probabili formazioni indicate dalla fonte editoriale; indisponibilità e scelte definitive restano da verificare vicino alla partita.";
  document.querySelectorAll(".reading-picks li").forEach(item=>{if(item.textContent.includes("Rose e sistemi"))item.textContent="Rose, sistemi e probabili formazioni";if(item.textContent.includes("Le formazioni probabili"))item.textContent="Le probabili formazioni sono proiezioni editoriali e vanno riconfermate vicino alla partita."});
  if(!prediction){const summary=document.querySelector(".reading-summary-prototype");if(summary)summary.innerHTML='<div class="reading-exact-scores"><span>Risultati esatti probabili</span><div class="reading-score-list"><div><strong>N/D</strong><small>Alternativa</small></div><div class="is-central"><strong>N/D</strong><small>Centrale</small></div><div><strong>N/D</strong><small>Alternativa</small></div></div></div><div class="reading-final-verdict"><span>Verdetto finale</span><strong>In preparazione</strong><small>Nessuna previsione senza dati sufficienti</small></div>';}
}
function renderReadingPilotEvidence(reading){
  if(!reading)return;
  const completed=readingModules.filter(([key])=>reading.sections?.[key]?.content).length,available=[["form","Base storica 2025/26"]].filter(([key])=>reading.sections?.[key]?.content);
  document.querySelector(".reading-progress").textContent=`Analisi 3.0.0 · ${completed}/7 fonti editoriali`;
  const banner=document.querySelector(".reading-prototype-banner strong");if(banner)banner.textContent="Pronostico preliminare, non garanzia";
  if(!available.length)return;
  const cards=available.map(([key,title])=>{const section=reading.sections[key];return `<article class="reading-pilot-card"><header><span>${title}</span><strong>Dato disponibile</strong></header><p>${esc(section.content)}</p>${section.signals?.length?`<ul>${section.signals.map(signal=>`<li>${esc(signal)}</li>`).join("")}</ul>`:""}${section.sources?.length?`<footer>${section.sources.map(source=>`<a href="${esc(source.url)}" target="_blank" rel="noreferrer">${esc(source.label)}</a>`).join(" · ")}</footer>`:""}</article>`}).join("");
  document.querySelector(".reading-projection-prototype")?.insertAdjacentHTML("beforebegin",`<section class="section reading-pilot-evidence"><header class="section-heading"><div><p class="eyebrow">Atalanta - Sassuolo · versione iniziale</p><h2>Evidenze già integrate</h2></div><p>Storico e contesto restano separati dai dati 2026/27.</p></header><div>${cards}</div></section>`);
}
function renderTacticalBaselines(match,dataset,teams){
  if(!match||!dataset?.profiles?.length)return;
  const profileFor=teamId=>dataset.profiles.find(profile=>profile.teamId===teamId),teamFor=teamId=>teams.find(team=>team.id===teamId);
  const card=teamId=>{const team=teamFor(teamId),profile=profileFor(teamId);if(!team||!profile)return"";const list=(label,items)=>`<div><strong>${label}</strong>${items?.length?`<ul>${items.slice(0,5).map(item=>`<li>${esc(item.label)}</li>`).join("")}</ul>`:'<p class="muted">N/D dal provider</p>'}</div>`;return `<article class="reading-tactical-card">${teamLogo(team)}<span class="sample-label sample-${profile.dataQuality==="complete"?"strong":"low"}">${profile.dataQuality==="complete"?"Profilo completo":profile.dataQuality==="limited-sample"?"Campione limitato":"Solo statistiche"}</span><dl><div><dt>Campione</dt><dd>${esc(profile.competition)} · ${profile.summary.appearances} gare</dd></div><div><dt>Modulo più usato</dt><dd>${esc(profile.formation.code||"N/D")}${profile.formation.appearances?` · ${profile.formation.appearances} gare`:""}</dd></div><div><dt>Possesso</dt><dd>${profile.summary.possessionPct===null?"N/D":`${profile.summary.possessionPct}%`}</dd></div><div><dt>Tiri / gara</dt><dd>${profile.summary.shotsPerGame??"N/D"}</dd></div><div><dt>Gol / gara</dt><dd>${profile.derived.goalsPerGame}</dd></div></dl><div class="reading-tactical-traits">${list("Punti di forza",profile.strengths)}${list("Vulnerabilità",profile.weaknesses)}${list("Stile",profile.playingStyle)}</div>${profile.notes?.length?`<p class="reading-tactical-note">${profile.notes.map(esc).join(" ")}</p>`:""}<a href="${esc(profile.source.url)}" target="_blank" rel="noreferrer">Fonte WhoScored</a></article>`};
  const target=document.querySelector(".reading-projection-prototype");
  target?.insertAdjacentHTML("beforebegin",`<section class="section reading-tactical-baseline"><header class="section-heading"><div><p class="eyebrow">WhoScored · stagione 2025/26</p><h2>Baseline tattica delle squadre</h2></div><p>Contesto storico, non previsione autonoma.</p></header><div>${card(match.homeTeam)}${card(match.awayTeam)}</div><p class="objective-method">Il modello sarà ricalcolato con forma 2026/27, assenze, probabili formazioni definitive e arbitro; le quote resteranno un confronto esterno.</p></section>`);
}
function refereeStatsTable(rows,competition){
  const isSerieA=competition==="serieA";
  return `<div class="table-wrap"><table class="referee-stats-table"><thead><tr><th>Arbitro</th><th>Partite</th>${isSerieA?"<th>Gialli</th>":"<th>Falli / gara</th>"}<th>Gialli / gara</th>${isSerieA?"<th>Rossi</th>":""}<th>Rossi / gara</th><th>Campione</th></tr></thead><tbody>${rows.map(row=>{const s=row[competition];return `<tr><td><strong>${esc(row.name)}</strong></td><td>${s.matches}</td>${isSerieA?`<td>${s.yellowCards}</td>`:`<td>${s.foulsPerMatch.toFixed(2)}</td>`}<td>${s.yellowCardsPerMatch.toFixed(2)}</td>${isSerieA?`<td>${s.redCards}</td>`:""}<td>${s.redCardsPerMatch.toFixed(2)}</td><td><span class="sample-label sample-${s.matches<5?'low':s.matches<10?'medium':'strong'}">${sampleLabel(s.matches)}</span></td></tr>`}).join("")}</tbody></table></div>`;
}
function refereeRankings(rows,competition){
  const eligible=rows.filter(row=>row[competition].matches>=5),top=(field,ascending=false)=>[...eligible].sort((a,b)=>(ascending?a[competition][field]-b[competition][field]:b[competition][field]-a[competition][field])||a.name.localeCompare(b.name,"it")).slice(0,5),card=(title,field,ascending=false)=>`<article class="card ranking-card"><h3>${title}</h3><ol>${top(field,ascending).map(row=>`<li><span>${esc(row.name)}</span><strong>${row[competition][field].toFixed(2)}</strong></li>`).join("")}</ol></article>`;return `<div class="ranking-grid">${card("Più gialli / gara","yellowCardsPerMatch")}${card("Meno gialli / gara","yellowCardsPerMatch",true)}${competition==="serieA"?card("Più espulsioni / gara","redCardsPerMatch"):card("Più falli / gara","foulsPerMatch")}</div>`;
}
const competitionLabel=value=>value==="serie-a"?"Serie A":"Serie B";
function pilotRefereeTable(rows){return `<div class="table-wrap"><table class="pilot-referee-table"><thead><tr><th>Competizione</th><th>Arbitro</th><th>Partite</th><th>Falli / gara</th><th>Gialli / gara</th><th>2° gialli</th><th>Rossi diretti</th><th>Rigori / gara</th><th>Attendibilità</th><th>Fonte</th></tr></thead><tbody>${[...rows].sort((a,b)=>a.competition.localeCompare(b.competition)||a.referee.localeCompare(b.referee,"it")).map(row=>`<tr><td><span class="competition-chip">${competitionLabel(row.competition)}</span></td><td><strong>${esc(row.referee)}</strong></td><td>${row.matches}</td><td>${row.foulsPerMatch?.toFixed(2)??"—"}</td><td>${row.yellowCardsPerMatch?.toFixed(2)??"—"}</td><td>${row.secondYellowCards}</td><td>${row.straightRedCards}</td><td>${row.penaltiesPerMatch?.toFixed(2)??"—"}</td><td><span class="sample-label sample-low">${esc(row.reliability)}</span></td><td>${row.fixtureIds.map(id=>`<a class="source-id" href="https://www.espn.com/soccer/match/_/gameId/${esc(id)}" target="_blank" rel="noreferrer">${esc(id)}</a>`).join(" ")}</td></tr>`).join("")}</tbody></table></div>`}
function pilotTeamTable(rows){return `<div class="table-wrap"><table class="pilot-team-table"><thead><tr><th>Competizione</th><th>Arbitro</th><th>Squadra</th><th>Partite</th><th>Falli / gara</th><th>Gialli / gara</th><th>Media altri arbitri</th><th>Confronto</th></tr></thead><tbody>${[...rows].sort((a,b)=>a.competition.localeCompare(b.competition)||a.referee.localeCompare(b.referee,"it")||a.teamName.localeCompare(b.teamName,"it")).map(row=>`<tr><td>${competitionLabel(row.competition)}</td><td><strong>${esc(row.referee)}</strong></td><td>${esc(row.teamName)}</td><td>${row.matches}</td><td>${row.foulsPerMatch?.toFixed(2)??"—"}</td><td>${row.yellowCardsPerMatch?.toFixed(2)??"—"}</td><td>${row.comparison.teamAverageWithOtherReferees?.toFixed(2)??"—"}</td><td><span class="sample-label sample-${row.reliability==="campione insufficiente"?'low':'medium'}">${esc(row.comparison.severity)}</span></td></tr>`).join("")}</tbody></table></div>`}
function pilotSection(aggregates,report){const serieA=report.competitions.find(item=>item.competition==="serie-a"),serieB=report.competitions.find(item=>item.competition==="serie-b"),missing=Object.entries(report.missingFields);return `<section class="section referee-section pilot-section" id="pilot-espn"><p class="eyebrow">Importatore automatico · ESPN</p><h2>Pilot statistiche arbitrali</h2><p class="lead-small">Primo controllo su 10 partite di Serie A e 10 di Serie B 2025/26. I risultati sportivi non sono usati per formulare giudizi di favoritismo.</p><div class="pilot-summary"><article><span>Serie A importate</span><strong>${serieA?.imported??0}/${serieA?.requested??0}</strong></article><article><span>Serie B importate</span><strong>${serieB?.imported??0}/${serieB?.requested??0}</strong></article><article><span>Arbitri analizzati</span><strong>${aggregates.referees.length}</strong></article><article class="${missing.length?'pilot-warning':''}"><span>Campi mancanti</span><strong>${missing.reduce((sum,[,count])=>sum+count,0)}</strong></article></div>${missing.length?`<aside class="pilot-missing"><strong>Copertura del provider</strong><p>${missing.map(([field,count])=>`${esc(field)}: assente in ${count} partite`).join(" · ")}. Gli altri campi richiesti risultano disponibili nel pilot.</p></aside>`:""}<h3 class="pilot-subtitle">Statistiche per arbitro</h3>${pilotRefereeTable(aggregates.referees)}<h3 class="pilot-subtitle">Confronto arbitro-squadra</h3><p class="muted">Con una sola gara per coppia, il confronto resta correttamente classificato come campione insufficiente.</p>${pilotTeamTable(aggregates.refereeTeams)}<p class="referee-note">Dati recuperati ${new Date(report.retrievedAt).toLocaleString("it-IT")} · Provider ESPN · Fixture e fonti consultabili nella tabella.</p></section>`}

const numberCell=value=>value===null||value===undefined?"—":Number(value).toFixed(2);
const signedDelta=value=>value>0?`+${value}`:`${value}`;
function teamRefereeProfilePanel(profile){
  if(!profile||profile.availability!=="available")return `<div class="team-referee-empty"><strong>Dati non disponibili per la Serie A 2025/26</strong><p>${esc(profile?.teamName||"Squadra")} militava in Serie B: la pagina WhoScored selezionata sul torneo Serie A non espone righe. Il dato resta N/D e non viene ricostruito.</p>${profile?.sourceUrl?`<a href="${esc(profile.sourceUrl)}" target="_blank" rel="noreferrer">Verifica la pagina WhoScored</a>`:""}</div>`;
  const coverage=profile.coverage,totals=profile.teamOverviewTotals,coverageText=coverage.mode==="complete"?"Tabella completa":`Top 20 · ${coverage.visibleAppearances}/${coverage.seasonAppearances} presenze visibili`;
  return `<div class="team-referee-summary"><article><span>Arbitri visibili</span><strong>${coverage.visibleReferees}</strong></article><article><span>Copertura presenze</span><strong>${coverage.visibleAppearancePct}%</strong></article><article><span>Gialli squadra</span><strong>${totals?.yellowCards??"N/D"}</strong></article><article><span>Rossi squadra</span><strong>${totals?.redCards??"N/D"}</strong></article></div><aside class="team-referee-coverage ${coverage.mode==="top-20"?"is-partial":""}"><strong>${coverageText}</strong><p>${coverage.mode==="top-20"?"WhoScored limita la vista a 20 arbitri: le righe mancanti non vengono inventate. I totali squadra provengono dalla pagina panoramica WhoScored già acquisita.":"Le presenze delle righe coincidono con le 38 gare del totale squadra."}</p></aside><div class="table-wrap"><table class="team-referee-table"><thead><tr><th>Arbitro</th><th>Pres.</th><th>Falli</th><th>Falli pc</th><th>Rigori ap</th><th>Gialli ap</th><th>Gialli</th><th>Rossi</th><th>ESPN</th></tr></thead><tbody>${profile.rows.map(row=>{const comparison=row.espnComparison,exact=comparison&&comparison.matchDifference===0&&comparison.yellowCardDifference===0;return `<tr><td><a href="${esc(row.sourceUrl)}" target="_blank" rel="noreferrer"><strong>${esc(row.referee)}</strong></a><small>${row.currentCan2026_27?"CAN 2026/27":"storico / non CAN"}</small></td><td>${row.appearances}<span class="sample-label sample-${row.sample==="insufficient"?"low":row.sample==="moderate"?"medium":"strong"}">${row.sample==="insufficient"?"campione basso":row.sample==="moderate"?"moderato":"significativo"}</span></td><td>${numberCell(row.foulsAwardedAgainstPerAppearance)}</td><td>${numberCell(row.foulsPerTackle)}</td><td>${numberCell(row.penaltiesAwardedAgainstPerAppearance)}</td><td>${numberCell(row.yellowCardsPerAppearance)}</td><td>${row.yellowCards}</td><td>${row.redCards}</td><td>${comparison?`<span class="source-check ${exact?"is-exact":"is-different"}">${exact?"pres. e gialli coincidono":`Δ pres. ${signedDelta(comparison.matchDifference)} · Δ gialli ${signedDelta(comparison.yellowCardDifference)}`}</span>`:'<span class="source-check">non collegato</span>'}</td></tr>`}).join("")}</tbody></table></div><footer class="team-referee-source"><span>Filtri: Totale · Corrente · Serie A · infrazioni Da</span><a href="${esc(profile.sourceUrl)}" target="_blank" rel="noreferrer">Fonte WhoScored</a></footer>`;
}
function whoScoredTeamRefereeSection(dataset){const ordered=[...dataset.profiles].sort((a,b)=>a.teamName.localeCompare(b.teamName,"it")),initial=ordered.find(profile=>profile.teamId==="inter")||ordered[0];return `<section class="section referee-section team-referee-section" id="whoscored-squadre"><p class="eyebrow">WhoScored · disciplina per squadra</p><h2>Arbitro–squadra 2025/26</h2><p class="lead-small">Le stesse statistiche della pagina Inter sono state acquisite per tutte le 20 squadre 2026/27 e collegate, dove possibile, ai confronti ESPN.</p><div class="pilot-summary"><article><span>Squadre censite</span><strong>${dataset.coverage.teams}/20</strong></article><article><span>Con dati Serie A</span><strong>${dataset.coverage.available}</strong></article><article><span>Righe WhoScored</span><strong>${dataset.coverage.refereeRows}</strong></article><article><span>Collegate a ESPN</span><strong>${dataset.coverage.linkedToEspn}</strong></article></div><label class="team-referee-selector" for="team-referee-select"><span>Scegli squadra</span><select id="team-referee-select">${ordered.map(profile=>`<option value="${esc(profile.teamId)}"${profile.teamId===initial.teamId?" selected":""}>${esc(profile.teamName)}${profile.availability==="available"?"":" · N/D Serie A"}</option>`).join("")}</select></label><div id="team-referee-panel">${teamRefereeProfilePanel(initial)}</div><aside class="method-note"><strong>Come leggere il confronto</strong><p>WhoScored ed ESPN restano due fonti autonome. “Coincide” riguarda soltanto presenze e gialli della stessa coppia arbitro–squadra; una differenza segnala copertura o classificazione diversa, non un errore corretto automaticamente e non un indizio di favoritismo.</p></aside></section>`}
function fullRefereeTable(rows){return `<div class="table-wrap"><table class="pilot-referee-table"><thead><tr><th>Competizione</th><th>Arbitro</th><th>Partite</th><th>Falli / gara</th><th>Gialli / gara</th><th>2ª ammonizioni</th><th>Rossi diretti</th><th>Rigori</th><th>Campione</th></tr></thead><tbody>${rows.map(row=>`<tr><td>${competitionLabel(row.competition)}</td><td><strong>${esc(row.referee)}</strong></td><td>${row.matches}</td><td>${numberCell(row.foulsPerMatch)}</td><td>${numberCell(row.yellowCardsPerMatch)}</td><td>${row.secondYellowCards}</td><td>${row.straightRedCards}</td><td>${row.penalties}</td><td><span class="sample-label sample-${row.matches<5?'low':row.matches<10?'medium':'strong'}">${esc(row.reliability)}</span></td></tr>`).join("")}</tbody></table></div>`}
function fullTeamTable(rows){return `<div class="table-wrap"><table class="pilot-team-table"><thead><tr><th>Competizione</th><th>Arbitro</th><th>Squadra</th><th>Partite</th><th>Falli / gara</th><th>Gialli / gara</th><th>Media altri arbitri</th><th>Confronto</th><th>Attendibilità</th></tr></thead><tbody>${rows.map(row=>`<tr><td>${competitionLabel(row.competition)}</td><td><strong>${esc(row.referee)}</strong></td><td>${esc(row.teamName)}</td><td>${row.matches}</td><td>${numberCell(row.foulsPerMatch)}</td><td>${numberCell(row.yellowCardsPerMatch)}</td><td>${numberCell(row.comparison.teamAverageWithOtherReferees)}</td><td>${esc(row.comparison.severity)}</td><td><span class="sample-label sample-${row.matches<5?'low':row.matches<10?'medium':'strong'}">${esc(row.reliability)}</span></td></tr>`).join("")}</tbody></table></div>`}
function sourceDifferences(validation){const rows=validation.sourceComparison.rows.filter(row=>row.espn&&Object.values(row.differences).some(value=>value!==0&&value!==null)),totals=validation.sourceComparison.totals||[];return `<section class="section referee-section" id="differenze-fonti"><p class="eyebrow">Riconciliazione</p><h2>Differenze fra le fonti</h2><p class="muted">ESPN, Soccerbase e lo snapshot Serie B restano separati. Le differenze non vengono sovrascritte.</p><h3 class="pilot-subtitle">Totali aggregati di confronto</h3><div class="table-wrap"><table><thead><tr><th>Competizione</th><th>Partite ESPN</th><th>Partite snapshot</th><th>Δ partite</th><th>Δ falli / gara</th><th>Δ gialli / gara</th><th>Δ rossi / gara</th></tr></thead><tbody>${totals.map(row=>`<tr><td>${competitionLabel(row.competition)}</td><td>${row.espn.matches}</td><td>${row.snapshot.matches}</td><td>${row.differences.matches}</td><td>${numberCell(row.differences.foulsPerMatch)}</td><td>${numberCell(row.differences.yellowCardsPerMatch)}</td><td>${numberCell(row.differences.redCardsPerMatch)}</td></tr>`).join("")}</tbody></table></div><p class="muted">Il confronto usa soltanto gli arbitri dell’organico CAN 2026/27 presenti negli snapshot; per questo il totale non coincide necessariamente con tutte le gare.</p><details><summary>Mostra ${rows.length} confronti per arbitro con differenze</summary><div class="table-wrap"><table><thead><tr><th>Competizione</th><th>Arbitro</th><th>Partite ESPN</th><th>Partite snapshot</th><th>Δ gialli / gara</th><th>Δ rossi / gara</th></tr></thead><tbody>${rows.map(row=>`<tr><td>${competitionLabel(row.competition)}</td><td>${esc(row.referee)}</td><td>${row.espn.matches}</td><td>${row.snapshot.matches}</td><td>${numberCell(row.differences.yellowCardsPerMatch)}</td><td>${numberCell(row.differences.redCardsPerMatch)}</td></tr>`).join("")}</tbody></table></div></details><aside class="pilot-missing"><strong>Copertura ESPN</strong><p>${validation.missingFields.referee} partite di Serie A (giornate 35–38) non espongono l’arbitro nell’endpoint ESPN; falli, cartellini e rigori restano disponibili. La lacuna è conservata nel report.</p></aside></section>`}
function fullRefereeSection(aggregates,report,validation){const regular=aggregates.referees.filter(row=>row.stage==="regular-season"&&row.refereeSlug&&row.referee!=="provider:unknown"),current=regular.filter(row=>row.currentCan2026_27),historical=regular.filter(row=>!row.currentCan2026_27),teamRows=aggregates.refereeTeams.filter(row=>row.stage==="regular-season"&&row.referee!=="provider:unknown"),a=report.competitions.find(row=>row.competition==="serie-a"),b=report.competitions.find(row=>row.competition==="serie-b"),stageNames={"playoff-preliminary":"Playoff · preliminare","playoff-semifinal":"Playoff · semifinale","playoff-final":"Playoff · finale",playout:"Playout"};return `<section class="section referee-section" id="statistiche-2025-26"><p class="eyebrow">Importazione completa · ESPN</p><h2>Statistiche arbitrali 2025/26</h2><p class="lead-small">Stagioni regolari complete. Vittorie e sconfitte non sono usate come prova di favoritismi.</p><div class="pilot-summary"><article><span>Serie A regolare</span><strong>${a.regularSeason}/380</strong></article><article><span>Serie B regolare</span><strong>${b.regularSeason}/380</strong></article><article><span>Playoff / playout B separati</span><strong>${b.postseason}</strong></article><article><span>Partite senza giornata associata</span><strong>${validation.missingFields.matchday}</strong></article></div><aside class="pilot-missing"><strong>Campo interessato: matchday</strong><p>Tutte le ${a.regularSeason+b.regularSeason} gare regolari sono associate a una delle 38 giornate.</p></aside><h3 class="pilot-subtitle">Arbitri dell’organico CAN 2026/27</h3>${fullRefereeTable(current)}<h3 class="pilot-subtitle">Arbitri storici non presenti nell’organico 2026/27</h3><p class="muted">Restano nei dati storici con <code>currentCan2026_27: false</code>.</p>${fullRefereeTable(historical)}<h3 class="pilot-subtitle">Confronto arbitro–squadra</h3><p class="muted">0–4 gare: campione insufficiente · 5–9: indicazione moderata · 10 o più: confronto più significativo.</p><details><summary>Mostra tutti i confronti (${teamRows.length})</summary>${fullTeamTable(teamRows)}</details><h3 class="pilot-subtitle">Stage Serie B separati</h3><div class="pilot-summary">${Object.entries(report.stages).filter(([key])=>key.startsWith("serie-b:")&&!key.endsWith("regular-season")).map(([key,count])=>`<article><span>${esc(stageNames[key.split(":")[1]])}</span><strong>${count}</strong></article>`).join("")}</div><p class="referee-note">Dati recuperati ${new Date(report.retrievedAt).toLocaleString("it-IT")} · Fixture ID, URL fonte e retrievedAt registrati in ogni partita.</p></section>${sourceDifferences(validation)}`}

const fantasyPrice=(value,budget)=>Math.max(1,Math.round(value*budget/500));
const fantasyBudgetAmounts=(plan,budget)=>{
  const exact=plan.map(item=>budget*item.pct/100),amounts=exact.map(Math.floor);
  let remainder=budget-amounts.reduce((sum,value)=>sum+value,0);
  exact.map((value,index)=>({index,fraction:value-Math.floor(value)})).sort((a,b)=>b.fraction-a.fraction||a.index-b.index).forEach(item=>{if(remainder>0){amounts[item.index]+=1;remainder-=1}});
  return amounts;
};
function fantasyPlayerCalendar(data,player){
  const fixtures=data.teams.find(team=>team.id===player.teamId)?.calendar.fixtures||[];
  return fixtures.map(fixture=>{const score=Math.max(5,Math.min(95,Math.round((fixture.ease*.8+player.score*.2)*10)/10));return {...fixture,score,recommendation:score>=68?"Da schierare":score>=53?"Schierabile":score>=40?"Con cautela":"Da evitare"}});
}
function fantasyPlayerRows(data,budget=500,role="",stars="",query="",sortKey=null){
  const teamById=new Map(data.teams.map(team=>[team.id,team])),needle=query.trim().toLowerCase();
  const matchingTeams=needle.length>=2?data.teams.filter(team=>team.name.toLowerCase().startsWith(needle)):[];
  const searchedTeam=matchingTeams.length===1?matchingTeams[0].name.toLowerCase():null;
  sortKey=sortKey||document.querySelector(".fantasy-sort.active")?.dataset.fantasySort||"score";
  const sortValues={score:player=>player.score,marketValue:player=>player.marketValueEur,minutes:player=>player.minutes,goalAssist:player=>(player.goals??0)+(player.assists??0),cards:player=>(player.fantasyScoring?.yellowCards??0)+(player.fantasyScoring?.dismissals??0),price:player=>fantasyPrice(player.value500,budget)};
  const valueFor=sortValues[sortKey]||sortValues.score;
  const filtered=data.players.filter(player=>(!role||player.role===role)&&(!stars||player.stars===Number(stars))&&(!needle||(searchedTeam?player.team.toLowerCase()===searchedTeam:`${player.name} ${player.team}`.toLowerCase().includes(needle))));
  const rows=[...filtered].sort((a,b)=>{const av=valueFor(a),bv=valueFor(b),aMissing=av===null||av===undefined,bMissing=bv===null||bv===undefined;if(aMissing!==bMissing)return aMissing?1:-1;const primary=typeof av==="string"?String(bv).localeCompare(av,"it"):(bv??0)-(av??0);return primary||b.score-a.score||a.name.localeCompare(b.name,"it")}).slice(0,80);
  return {count:filtered.length,html:rows.map(player=>{const team=teamById.get(player.teamId),scoring=player.fantasyScoring||{},yellow=scoring.yellowCards,red=scoring.dismissals;return `<tr><td><span class="fantasy-role role-${player.role}">${player.role}</span><span class="fantasy-stars" aria-label="${player.stars} ${player.stars===1?"stella":"stelle"}">${"★".repeat(player.stars)}${"☆".repeat(5-player.stars)}</span></td><td><button class="fantasy-player fantasy-player-button" type="button" data-fantasy-player="${esc(player.id)}"><strong>${esc(player.name)}</strong><small>${esc(player.detailedRole)} · ${esc(player.reliability)} · dati ${esc(player.competitionProfile.label)}${player.goalkeeperStatus?` · ${esc(player.goalkeeperStatus)}`:""}</small></button></td><td><span class="fantasy-team"><img src="${esc(team?.fantasyLogo||"")}" alt="">${esc(player.team)}</span></td><td><strong>${player.score}</strong><small class="fantasy-index">/100</small></td><td>${player.marketValueLabel?`<strong class="market-value">${esc(player.marketValueLabel)}</strong>`:"N/D"}</td><td>${player.minutes??"N/D"}</td><td>${player.goals??"N/D"} / ${player.assists??"N/D"}</td><td>${yellow===null||yellow===undefined?"N/D":`${yellow} G / ${red??0} R`}</td><td><strong class="fantasy-price">${fantasyPrice(player.value500,budget)}</strong></td></tr>`}).join("")};
}
function configureFantasyHeaders(){
  const headers=[...document.querySelectorAll(".fantasy-table th")];
  headers.find(th=>th.textContent.includes("Calendario"))?.remove();
  const goalAssist=headers.find(th=>th.textContent.trim()==="G / A");
  goalAssist?.insertAdjacentHTML("afterend",'<th>Cartellini</th>');
  const sortable=new Map([["Indice","score"],["Valore mercato","marketValue"],["Minuti","minutes"],["G / A","goalAssist"],["Cartellini","cards"],["Max crediti","price"]]);
  document.querySelectorAll(".fantasy-table th").forEach(th=>{const label=th.textContent.trim(),key=sortable.get(label);if(key)th.innerHTML=`<button type="button" class="fantasy-sort${key==="score"?" active":""}" data-fantasy-sort="${key}" aria-label="Ordina per ${label} in ordine decrescente" aria-pressed="${key==="score"}">${label}<span aria-hidden="true"> ↓</span></button>`});
}
function fantasyGoalkeeperTrios(data,budget=500){
  const trios=data.goalkeeperTrios?.examples||[];
  if(!trios.length)return "";
  const scale=budget/500;
  return `<section class="section goalkeeper-rotation"><header class="section-heading"><div><p class="eyebrow">Esempio pratico · tris di portieri</p><h2>Il calendario funziona per incrocio</h2></div><p>Ogni giornata parte il portiere con la gara migliore, entro il 7% del budget.</p></header><div class="goalkeeper-trios">${trios.slice(0,3).map((trio,index)=>`<article><div class="goalkeeper-trio-head"><span>Soluzione ${index+1}</span><strong>${fantasyPrice(trio.cost500,budget)} crediti</strong></div><div class="goalkeeper-list">${trio.players.map(player=>`<div><span>${esc(player.name)}<small>${esc(player.team)} · ${player.starts} giornate</small></span><strong>${fantasyPrice(player.value500,budget)}</strong></div>`).join("")}</div><dl><div><dt>Copertura</dt><dd>${trio.coveredDays}/38</dd></div><div><dt>Favorevoli</dt><dd>${trio.favorableDays}</dd></div><div><dt>Difficili</dt><dd>${trio.difficultDays}</dd></div><div><dt>Indice rotazione</dt><dd>${trio.rotationIndex}</dd></div></dl></article>`).join("")}</div><p class="goalkeeper-note">${esc(data.goalkeeperTrios.method)} Costi adattati al budget selezionato (${Math.round(35*scale)} crediti teorici).</p></section>`;
}
function fantasyLineupCalendar(data,playerId,budget=500){
  const player=data.players.find(item=>item.id===playerId)||data.players[0],teams=new Map(data.teams.map(team=>[team.id,team]));
  const scoring=player.fantasyScoring||{},statValue=value=>value===null||value===undefined?"N/D":value;
  const playerStats=`<section class="fantasy-player-stats" aria-label="Statistiche fantasy di ${esc(player.name)}"><article><span>Valore massimo d'asta</span><strong>${fantasyPrice(player.value500,budget)} crediti</strong><small>Budget impostato: ${budget}</small></article><article><span>Indice fantasy</span><strong>${player.score}/100</strong><small>${player.stars} ${player.stars===1?"stella":"stelle"} · ${esc(player.reliability)}</small></article><article><span>Presenze con voto</span><strong>${statValue(scoring.appearancesWithVoteProxy)}</strong><small>Dato del foglio Fantacalcio</small></article><article><span>Media voto</span><strong>${statValue(scoring.averageRating)}</strong><small>Dato del foglio Fantacalcio</small></article><article><span>Fantamedia</span><strong>${statValue(scoring.fantasyAverage)}</strong><small>Dato del foglio Fantacalcio</small></article></section>`;
  const cells=fantasyPlayerCalendar(data,player).map(item=>{const opponent=teams.get(item.opponent);return `<article class="lineup-day lineup-${item.recommendation.toLowerCase().replaceAll(" ","-")}"><span>${item.matchday}ª giornata · ${item.venue==="C"?"Casa":"Trasferta"}</span><div><img src="${esc(String(opponent?.logo||"").replace(/^\.\.\//,""))}" alt=""><strong>${esc(opponent?.name||item.opponent)}</strong></div><b>${esc(item.recommendation)}</b><small>Schierabilità ${item.score}/100 · gara ${esc(item.label.toLowerCase())}</small></article>`}).join("");
  return `<header><div><p class="eyebrow">Statistiche giocatore · calendario completo</p><h2>${esc(player.name)}</h2><p>${esc(player.team)} · ${esc(player.detailedRole)} · ${player.stars} ${player.stars===1?"stella":"stelle"}</p></div><a class="button" href="statistiche-squadra/${esc(player.teamId)}.html">Apri statistiche complete</a></header>${playerStats}<div class="lineup-calendar-grid">${cells}</div>`;
}
function fantasyPage(data){
  const starCards=Object.entries(data.starGuide).sort((a,b)=>b[0]-a[0]).map(([stars,text])=>`<article><span class="fantasy-stars" aria-label="${stars} ${Number(stars)===1?"stella":"stelle"}">${"★".repeat(Number(stars))}${"☆".repeat(5-Number(stars))}</span><p>${esc(text)}</p></article>`).join("");
  const slotCards=starCards;
  const initialBudgetAmounts=fantasyBudgetAmounts(data.budgetPlan,500);
  const plan=data.budgetPlan.map((item,index)=>`<article data-budget-role="${item.role}" data-pct="${item.pct}"><span>${esc(item.label)} · ${item.players} giocatori</span><strong>${initialBudgetAmounts[index]}</strong><small>${item.pct}% del budget</small></article>`).join("");
  return hero("Asta 2026/27","Fantacalcio, una rosa costruita con criterio.","Valore, continuità e tutte le 38 giornate diventano una guida d'asta e di formazione adattabile al tuo budget. Gli slot A–D sono confrontati all'interno dello stesso ruolo.")+`<section class="fantasy-config"><div><p class="eyebrow">Il tuo budget</p><label for="fantasy-budget">Crediti iniziali</label><div class="fantasy-budget-input"><input id="fantasy-budget" type="number" min="100" max="2000" step="50" value="500"><span>crediti</span></div></div><div class="fantasy-plan">${plan}</div></section><div id="goalkeeper-trios">${fantasyGoalkeeperTrios(data,500)}</div><section class="section fantasy-slots"><header class="section-heading"><div><p class="eyebrow">Gerarchia d'asta</p><h2>Come leggere gli slot</h2></div></header><div>${slotCards}</div></section><section class="section fantasy-board"><header class="section-heading"><div><p class="eyebrow">${data.players.length} profili con dati disponibili</p><h2>Consigli per l'asta</h2></div><p>Prezzo massimo orientativo, non quotazione ufficiale.</p></header><div class="fantasy-controls"><label><span>Cerca</span><input id="fantasy-search" type="search" placeholder="Calciatore o squadra"></label><label><span>Ruolo</span><select id="fantasy-role"><option value="">Tutti</option><option value="P">Portieri</option><option value="D">Difensori</option><option value="C">Centrocampisti</option><option value="A">Attaccanti</option></select></label><label><span>Slot</span><select id="fantasy-slot"><option value="">Tutti</option>${["A","B","C","D"].map(slot=>`<option>${slot}</option>`).join("")}</select></label><strong id="fantasy-count"></strong></div><div class="table-wrap"><table class="fantasy-table"><thead><tr><th>Slot</th><th>Calciatore</th><th>Squadra</th><th>Indice</th><th>Valore mercato</th><th>Calendario · 38 giornate</th><th>Minuti</th><th>G / A</th><th>Max crediti</th></tr></thead><tbody id="fantasy-players"></tbody></table></div><aside class="fantasy-method"><strong>Peso di presente, mercato e storia</strong><p>${esc(data.methodology.description)} Il Como viene quindi premiato per il 4° posto 2025/26; la Fiorentina non riceve un vantaggio eccessivo dal 5° posto nella classifica perpetua dopo il 15° posto recente.</p><p>${esc(data.methodology.caveat)}</p></aside></section><section class="section lineup-calendar" id="calendario-formazione"></section>`;
}

const cupBracketSlot=(label="Da definire")=>`<span class="cup-team-slot"><i aria-hidden="true"></i><span>${esc(label)}</span></span>`;
const cupRoundConfig=[
  {id:"preliminary",step:"01",label:"Turno preliminare",window:"8–9 agosto 2026"},
  {id:"round-32",step:"02",label:"Trentaduesimi",window:"14–17 agosto 2026"},
  {id:"round-16",step:"03",label:"Sedicesimi",window:"2–15 settembre 2026"},
  {id:"round-of-16",step:"04",label:"Ottavi di finale",window:"2 dicembre 2026 – 13 gennaio 2027"},
  {id:"quarter",step:"05",label:"Quarti di finale",window:"3–10 febbraio 2027"},
  {id:"semifinal",step:"06",label:"Semifinali",window:"3–24 marzo 2027"},
  {id:"final",step:"07",label:"Finale",window:"19 maggio 2027"}
];
function cupMatchCard(match,index,round){
  const pathLabel=["preliminary","round-32"].includes(round.id)?`Partita ${index+1}`:round.id==="final"?"Atto conclusivo":round.id==="semifinal"?`Semifinale ${index+1}`:`Percorso ${String(match.branch??index+1).padStart(2,"0")}`;
  return `<article class="cup-match-card" aria-label="${esc(`${match.home} contro ${match.away}, ${match.scheduleLabel||"data da definire"}`)}"><header><span>${pathLabel}</span>${round.id==="final"?'<b aria-hidden="true">CI</b>':""}</header><div class="cup-match-teams">${cupBracketSlot(match.home)}${cupBracketSlot(match.away)}</div><footer><span>Data</span><strong>${esc(match.scheduleLabel||"Data da definire")}</strong></footer></article>`;
}
function cupRound(round,data){
  const matches=data.matches.filter(match=>match.stage===round.id).sort((a,b)=>scheduleChronology(a,b)||(a.branch??0)-(b.branch??0));
  return `<section class="cup-round cup-round--${round.id}" id="coppa-${round.id}" data-stage="${round.id}"><header class="cup-round-heading"><span>${round.step}</span><div><p>${round.window}</p><h3>${round.label}</h3></div><small>${matches.length} ${matches.length===1?"incrocio":"incroci"}</small></header><div class="cup-match-grid">${matches.map((match,index)=>cupMatchCard(match,index,round)).join("")}</div></section>`;
}
function cupBracket(data){
  const visibleMatches=data.matches.filter(match=>cupRoundConfig.some(round=>round.id===match.stage));
  const roundNavigation=cupRoundConfig.map(round=>`<a href="#coppa-${round.id}"><span>${round.step}</span>${round.label}</a>`).join("");
  return `<section class="section cup-stage"><header class="section-heading cup-stage-heading"><div><p class="eyebrow">Tabellone 2026/27</p><h2>Il percorso, turno dopo turno</h2><p>Gli incroci sono disposti in ordine cronologico. I nomi separati da una barra rappresentano alternative ancora aperte, non squadre già qualificate.</p></div><span class="cup-badge"><i aria-hidden="true"></i> ${visibleMatches.length} incroci mostrati</span></header><nav class="cup-round-nav" aria-label="Vai a un turno della Coppa Italia">${roundNavigation}</nav><div class="cup-round-list">${cupRoundConfig.map(round=>cupRound(round,data)).join("")}</div><footer class="cup-stage-note"><span>Aggiornato al ${dateOnly(data.updatedAt)}</span><p>Fonte: <a href="${esc(data.source.url)}" target="_blank" rel="noreferrer">${esc(data.source.label)}</a>. Date, orari e programmazione TV sono riportati quando disponibili nella fonte.</p></footer></section>`;
}

async function render(){
  const page=document.body.dataset.page,[teams,matches,readings,previousStandings,objectiveProfiles]=await Promise.all([load("teams.json"),load("matches.json"),load("readings.json"),load("standings-2025-26.json"),loadObjectiveProfiles()]);let refs=[],refereeFull=null,refereeFullReport=null,refereeValidation=null,teamRefereeProfiles=null;if(page==="referees")[refs,refereeFull,refereeFullReport,refereeValidation,teamRefereeProfiles]=await Promise.all([load("referees.json"),loadGenerated("referee-stats/2025-26/aggregates.json"),loadGenerated("referee-stats/2025-26/import-report.json"),loadGenerated("referee-stats/2025-26/validation-report.json"),load("team-referee-profiles.json")]);
  let teamDirectory=null,playerLeaderboards=null,teamStyleProfiles=null,predictionDataset=null,headToHeadData=null;if(page==="team-stats")[teamDirectory,playerLeaderboards]=await Promise.all([loadTeamDirectory(),loadPlayerLeaderboards()]);else if(page==="readings")[teamDirectory,teamStyleProfiles,predictionDataset,headToHeadData]=await Promise.all([loadTeamDirectory(),load("team-style-profiles.json"),load("predictions.json"),loadGenerated("head-to-head/first-leg-2026-27.json")]);
  let fantasy=null;if(page==="fantasy")fantasy=await loadGenerated("fantacalcio-advice.json");
  let cupBracketData=null;if(page==="cup")cupBracketData=await load("coppa-italia-2026-27.json");
  const league=matches.filter(m=>m.competition==="serie-a"),cup=matches.filter(m=>m.competition==="coppa-italia"),standings=calculateStandings(teams,matches),standingsTeams=[...teams,...previousStandings.historicalTeams];let html="",activeReading=null,activeReadingMatch=null,activePrediction=null;
  if(page==="home"){
    const completed=league.filter(match=>match.status==="finished").length,nextMatches=league.filter(match=>match.status!=="finished").sort(matchdayChronology).slice(0,10),leader=completed===0?{teamName:"N/D",points:0}:standings[0];
    html=hero("Stagione ufficiale","Il calcio italiano, giornata dopo giornata.","Calendario, numeri e contesto della Serie A Enilive 2026/27. Ogni dato resta collegato alla propria fonte.",`<div class="hero-season"><span>Serie A</span><strong>26<span>/</span>27</strong><small>${completed}/380 partite concluse</small></div>`)+`<section class="season-overview" aria-label="Panoramica stagione"><article><span>Squadre</span><strong>${teams.length}</strong><small>nel calendario ufficiale</small></article><article><span>Partite</span><strong>380</strong><small>${completed} concluse</small></article><article><span>Capolista</span><strong>${esc(leader?.teamName||teams.find(team=>team.id===leader?.team)?.name||"—")}</strong><small>${leader?.points??0} punti</small></article><article><span>Copertura</span><strong>38</strong><small>giornate consultabili</small></article></section><section class="section home-dashboard"><header class="section-heading"><div><p class="eyebrow">In primo piano</p><h2>Dentro la stagione</h2></div><a class="text-link" href="calendario.html">Apri il calendario →</a></header><div class="home-dashboard-grid"><div class="home-next"><h3><span>Prossime partite</span>${nextMatches.length?` - Giornata ${nextMatches[0].matchday}`:""}</h3>${nextMatches.length?`<ul class="home-match-list">${nextMatches.map(match=>homeMatchListItem(match,teams)).join("")}</ul>`:empty("Programmazione in aggiornamento.")}</div><aside class="home-rail"><a href="#classifiche"><span>Classifiche</span><strong>Situazione e archivio</strong><small>Posizioni, verdetti e storico stagionale</small></a><a href="statistiche-squadre.html"><span>Squadre</span><strong>Rose e leader</strong><small>Statistiche individuali e valori per 90'</small></a><a href="arbitri.html"><span>Arbitri</span><strong>Numeri e campioni</strong><small>Confronti neutrali tra le fonti</small></a></aside></div></section>`+homeStandings(standings,previousStandings,objectiveProfiles,teams,standingsTeams);
  }
  if(page==="calendar"){
    html=hero("Serie A","Calendario 2026/27","Scegli una giornata o una squadra e consulta tutte le 380 partite.")+dayNav()+teamNav(teams)+`<div class="calendar-list">${calendarDays(league,teams)}</div>`;
  }
  if(page==="team"){
    const teamId=new URLSearchParams(location.search).get("team"),team=teams.find(t=>t.id===teamId)||teams[0],teamMatches=league.filter(m=>m.homeTeam===team.id||m.awayTeam===team.id).sort((a,b)=>a.matchday-b.matchday);
    html=hero("Calendario squadra",team.name,`Tutte le 38 partite di ${esc(team.name)}, dalla prima all'ultima giornata.`,`<div class="team-hero-logo"><img src="${team.logo}" alt="Stemma ${esc(team.name)}"></div>`)+teamNav(teams,team.id)+`<section class="section team-schedule"><div class="team-schedule-head"><h2>Le 38 giornate</h2><a class="button" href="calendario.html">Calendario completo</a></div><div class="team-match-list">${teamMatches.map(m=>`<section class="team-matchday">${matchCard(m,teams)}</section>`).join("")}</div></section>`;
    document.title=`${team.name} | Calendario Serie A 2026/27`;document.querySelector("#app").innerHTML=html;return;
  }
  if(page==="team-stats")html=hero("Serie A 2026/27","Statistiche squadre","Consulta le rose, le statistiche individuali, i valori per 90 minuti e le classifiche dei migliori calciatori.")+`${teamDirectoryGrid(teamDirectory)}${globalPlayerLeaderboards(playerLeaderboards)}`;
  if(page==="fantasy")html=fantasyPage(fantasy);
  if(page==="readings")html=hero("Analisi prepartita","Lettura","Forma, assenze, tattica, arbitro e mercato: ogni segnale viene presentato come contesto, mai come certezza.")+`<section class="section">${readings.length?`<div class="grid">${readings.map(r=>`<article class="card"><h3>${esc(r.title)}</h3><p>${esc(r.summary)}</p></article>`).join("")}</div>`:`<div class="editorial-empty"><span class="editorial-empty-mark">L</span><div><p class="eyebrow">Prossimamente</p><h2>La prima lettura è in preparazione</h2><p>Le analisi appariranno qui quando saranno disponibili formazioni, quote e informazioni verificabili. Nessun dato verrà completato per supposizione.</p><a class="button button-primary" href="calendario.html">Consulta il calendario</a></div><ol><li><strong>01</strong><span>Contesto e forma</span></li><li><strong>02</strong><span>Assenze e tattica</span></li><li><strong>03</strong><span>Arbitro e mercato</span></li></ol></div>`}</section>`;
  if(page==="cup")html=hero("Eliminazione diretta","Coppa Italia","Dai preliminari dell’8 agosto alla finale del 19 maggio: date, orari e percorsi della coppa in un tabellone distinto dal campionato.")+cupBracket(cupBracketData);
  if(page==="referees")html=hero("Organico CAN · stagione 2026/27","Arbitri",`${refs.length} arbitri nell'organico attuale, seguiti dai dati completi 2025/26 e dagli arbitri storici separati.`,`<div class="hero-stat"><strong>${refs.length}</strong><span>arbitri censiti</span></div>`)+`<nav class="referee-nav" aria-label="Sezioni pagina arbitri"><a href="#organico-2026-27"><strong>42</strong><span>Organico 2026/27</span></a><a href="#statistiche-2025-26"><strong>760</strong><span>Gare ESPN 2025/26</span></a><a href="#whoscored-squadre"><strong>20</strong><span>Squadre WhoScored</span></a><a href="#differenze-fonti"><strong>≠</strong><span>Differenze fonti</span></a></nav><section class="section referee-section" id="organico-2026-27"><p class="eyebrow">Nome · Sezione AIA</p><h2>Organico 2026/27</h2><div class="referee-grid">${refs.map((ref,index)=>`<article class="card referee-card" id="${esc(ref.slug)}"><span class="referee-number">${index+1}</span><div><h3>${esc(ref.name)}</h3><p>${esc(ref.section)}</p></div><span class="status">${esc(ref.role)}</span></article>`).join("")}</div></section>${fullRefereeSection(refereeFull,refereeFullReport,refereeValidation)}${whoScoredTeamRefereeSection(teamRefereeProfiles)}<aside class="method-note"><strong>Linguaggio neutrale</strong><p>I risultati non sono usati come prova di favoritismi. I confronti descrivono soltanto severità relativa, media e dimensione del campione.</p></aside>`;
  if(page==="readings"){
    const matchId=new URLSearchParams(location.search).get("match"),selectedMatch=league.find(match=>match.id===matchId),reading=readings.find(item=>item.matchId===matchId),prediction=predictionDataset?.predictions?.find(item=>item.matchId===matchId);
    activeReading=reading;
    activeReadingMatch=selectedMatch;
    activePrediction=prediction;
    const history=headToHeadData?.fixtures?.find(fixture=>fixture.fixtureId===matchId);
    html=selectedMatch?readingPrototypeDetail(selectedMatch,reading,teams,teamDirectory,objectiveProfiles,prediction,history):readingIndex(readings,league,teams,predictionDataset?.predictions||[],headToHeadData);
    if(matchId&&!selectedMatch)html=`<aside class="data-warning"><strong>Partita non trovata</strong><p>Il collegamento richiesto non corrisponde al calendario corrente.</p></aside>${html}`;
  }
  document.querySelector("#app").innerHTML=html;
  if(page==="readings"){renderProbableLineups(activeReadingMatch,teamDirectory,activePrediction);renderReadingPilotEvidence(activeReading);renderTacticalBaselines(activeReadingMatch,teamStyleProfiles,teams)}
  if(page==="fantasy")configureFantasyHeaders();
  if(page==="fantasy"){const budget=document.querySelector("#fantasy-budget"),role=document.querySelector("#fantasy-role"),slot=document.querySelector("#fantasy-slot"),search=document.querySelector("#fantasy-search"),tbody=document.querySelector("#fantasy-players"),count=document.querySelector("#fantasy-count"),calendar=document.querySelector("#calendario-formazione"),goalkeeperTrios=document.querySelector("#goalkeeper-trios");let selectedPlayerId=fantasy.players[0].id;document.querySelector(".fantasy-slots .eyebrow").textContent="Valutazione d'asta";document.querySelector(".fantasy-slots h2").textContent="Come leggere le stelle";document.querySelector('label[for="fantasy-budget"]')?.setAttribute("aria-label","Crediti iniziali");slot.previousElementSibling.textContent="Stelle";slot.innerHTML=`<option value="">Tutte</option>${[5,4,3,2,1].map(value=>`<option value="${value}">${value} ${value===1?"stella":"stelle"}</option>`).join("")}`;document.querySelector(".fantasy-table th").textContent="Ruolo · stelle";[...document.querySelectorAll(".fantasy-table th")].find(th=>th.textContent.includes("Calendario"))?.remove();const heroEyebrow=document.querySelector(".hero .eyebrow"),heroText=document.querySelector(".hero .lead");if(heroEyebrow)heroEyebrow.textContent="Asta 2026/27";if(heroText)heroText.textContent="Valore, continuità e tutte le 38 giornate diventano una guida d'asta adattabile al tuo budget. Le stelle confrontano i calciatori all'interno dello stesso ruolo.";const currentBudget=()=>Math.max(100,Math.min(2000,Number(budget.value)||500)),showCalendar=playerId=>{selectedPlayerId=playerId;calendar.innerHTML=fantasyLineupCalendar(fantasy,playerId,currentBudget());calendar.scrollIntoView({behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"start"})};const update=()=>{const credits=currentBudget(),result=fantasyPlayerRows(fantasy,credits,role.value,slot.value,search.value),amounts=fantasyBudgetAmounts(fantasy.budgetPlan,credits);tbody.innerHTML=result.html;count.textContent=`${result.count} profili`;goalkeeperTrios.innerHTML=fantasyGoalkeeperTrios(fantasy,credits);calendar.innerHTML=fantasyLineupCalendar(fantasy,selectedPlayerId,credits);document.querySelectorAll("[data-budget-role]").forEach((card,index)=>{card.querySelector("strong").textContent=amounts[index]})};[role,slot].forEach(control=>control.addEventListener("change",update));budget.addEventListener("input",update);search.addEventListener("input",update);tbody.addEventListener("click",event=>{const button=event.target.closest("[data-fantasy-player]");if(button)showCalendar(button.dataset.fantasyPlayer)});update()}
  if(page==="fantasy"){document.querySelector(".fantasy-table thead").addEventListener("click",event=>{const button=event.target.closest("[data-fantasy-sort]");if(!button)return;document.querySelectorAll("[data-fantasy-sort]").forEach(item=>{const active=item===button;item.classList.toggle("active",active);item.setAttribute("aria-pressed",String(active))});document.querySelector("#fantasy-role").dispatchEvent(new Event("change"))})}
  if(page==="team-stats"){const controls=document.querySelector(".global-leaderboard-controls"),target=document.querySelector("#global-player-leaderboard");controls.addEventListener("click",event=>{const button=event.target.closest("[data-player-stat]");if(!button)return;controls.querySelectorAll("[data-player-stat]").forEach(item=>{const active=item===button;item.classList.toggle("active",active);item.setAttribute("aria-pressed",String(active))});target.innerHTML=globalPlayerLeaderboardTable(playerLeaderboards,button.dataset.playerStat)})}
  if(page==="referees"){const grid=document.querySelector(".referee-grid");grid.insertAdjacentHTML("beforebegin",`<div class="referee-controls"><label><span>Cerca arbitro</span><input id="referee-search" type="search" placeholder="Nome arbitro…" autocomplete="off"></label></div>`);const search=document.querySelector("#referee-search"),cards=[...grid.querySelectorAll(".referee-card")],update=()=>{const query=search.value.trim().toLowerCase();cards.forEach(card=>{const name=card.querySelector("h3")?.textContent.toLowerCase()||"",matches=!query||name.includes(query);card.hidden=!matches})};search.addEventListener("input",update)}
  if(page==="referees"){const teamSelect=document.querySelector("#team-referee-select"),teamPanel=document.querySelector("#team-referee-panel");teamSelect?.addEventListener("change",()=>{teamPanel.innerHTML=teamRefereeProfilePanel(teamRefereeProfiles.profiles.find(profile=>profile.teamId===teamSelect.value))})}
  if(page==="home"){configureStandingsTables();const activate=value=>{document.querySelectorAll("[data-standings-panel]").forEach(panel=>panel.hidden=panel.dataset.standingsPanel!==value);document.querySelectorAll("[data-standings-tab]").forEach(button=>{const active=button.dataset.standingsTab===value;button.classList.toggle("active",active);button.setAttribute("aria-pressed",String(active))});history.replaceState(null,"",value==="archive"?"#classifica-2025-26":location.pathname)};document.querySelectorAll("[data-standings-tab]").forEach(button=>button.addEventListener("click",()=>activate(button.dataset.standingsTab)));activate(location.hash==="#classifica-2025-26"?"archive":"current")}
}
document.querySelectorAll("[data-page-link]").forEach(a=>a.classList.toggle("active",a.dataset.pageLink===document.body.dataset.page));
const btn=document.querySelector(".menu-button"),nav=document.querySelector(".site-nav");btn.addEventListener("click",()=>{const open=nav.classList.toggle("open");btn.setAttribute("aria-expanded",open)});
render().catch(e=>{document.querySelector("#app").innerHTML=`<section class="empty"><h1>Dati non disponibili</h1><p>${esc(e.message)}</p></section>`;console.error(e)});
