services:
  - type: web
    name: serie-a-2026-27
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: RENDER
        value: "1"
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.13.0"
