"use strict";
const fs=require('fs'),path=require('path');
const {CONFIG}=require('./config'),{read,finite,kickoff,infoUniverse}=require('./data'),{mean,c1}=require('./models'),{correlation,spearman,probabilityMetrics}=require('./metrics');
function auditSample(input,dataset,predictions){
  const participants=dataset.participantAudit,probable=predictions.filter(r=>r.informationSet==='PREMATCH_PROBABLE');
  const reasons=Object.fromEntries([...new Set(predictions.flatMap(r=>r.exclusionReasons))].map(k=>[k,predictions.filter(r=>r.exclusionReasons.includes(k)).length]));
  const countsBy=(rows,key)=>Object.fromEntries([...new Set(rows.map(r=>r[key]))].sort().map(v=>[v,{n:rows.filter(r=>r[key]===v).length,primaryEligible:rows.filter(r=>r[key]===v&&r.primaryEligible).length,knownTargetPositives:rows.filter(r=>r[key]===v&&r.target===1).length}]));
  return {completedMatches:input.completed.length,actualPlayerMatchRecords:participants.length,played:participants.filter(r=>r.participation==='PLAYED').length,actualStarters:participants.filter(r=>r.actualStarter===true).length,actualSubstitutes:participants.filter(r=>r.participation==='PLAYED'&&r.actualStarter===false).length,unused:participants.filter(r=>r.participation==='UNUSED').length,totalActualMinutes:participants.reduce((n,r)=>n+(r.actualMinutes??0),0),
    sourceRecordedOrdinaryYellowPositives:participants.filter(r=>r.recordedOrdinaryYellow>0).length,sourceRecordedPlayedYellowPositives:participants.filter(r=>r.participation==='PLAYED'&&r.recordedOrdinaryYellow>0).length,sourceRecordedPlayedRate:mean(participants.filter(r=>r.participation==='PLAYED').map(r=>Number(r.recordedOrdinaryYellow>0))),recordedRateInterpretation:CONFIG.targetDisclaimer,
    projectedRecords:predictions.length,probableRecords:probable.length,probableMatches:new Set(probable.map(r=>r.matchId)).size,officialRecords:predictions.filter(r=>r.informationSet==='PREMATCH_OFFICIAL').length,projectedStarters:probable.filter(r=>r.projectedStarter).length,projectedReserves:probable.filter(r=>!r.projectedStarter).length,rowsWithCompleteDisciplinaryFeed:probable.filter(r=>r.targetCoverage.coverage==='COMPLETE').length,individuallyDeterminateTarget:probable.filter(r=>r.target!==null).length,unverifiedTargets:probable.filter(r=>r.target===null&&!r.targetCoverage.void).length,
    observationalPositives:probable.filter(r=>r.target===1).length,observationalNegatives:probable.filter(r=>r.target===0).length,ordinaryYellowEventsOutsideProjectedUniverse:participants.filter(r=>r.recordedOrdinaryYellow>0&&!probable.some(x=>x.matchId===r.matchId&&x.team===r.team&&(x.playerId?r.playerId===x.playerId:x.playerName===r.playerName))).length,
    primaryEligible:probable.filter(r=>r.primaryEligible).length,excluded:probable.filter(r=>!r.primaryEligible).length,exclusionCountsOverlapping:reasons,warningCountsOverlapping:Object.fromEntries([...new Set(probable.flatMap(r=>r.warnings||[]))].map(k=>[k,probable.filter(r=>r.warnings?.includes(k)).length])),unavailableUniverses:dataset.matchAudits.filter(r=>r.exclusionReason),matchAudits:dataset.matchAudits,
    missing:{playerId:probable.filter(r=>!r.playerId).length,detailedRole:probable.filter(r=>!r.detailedRole).length,fouls:probable.filter(r=>r.features.foulLogRatio===null).length,expectedMinutes:probable.filter(r=>r.features.expectedMinutes===null).length,referee:probable.filter(r=>!r.referee.identity).length,opponentFeatures:probable.filter(r=>r.features.opponentLogRatio===null).length},
    byRole:countsBy(probable,'roleGroup'),byMatchday:countsBy(probable,'matchday'),byTeam:countsBy(probable,'team'),unusedOutsideProjection:participants.filter(p=>p.participation==='UNUSED'&&!probable.some(r=>r.matchId===p.matchId&&r.team===p.team&&r.playerId===p.playerId)).length,
    target:CONFIG.target,targetVersion:CONFIG.targetVersion,marketTarget:CONFIG.marketTarget,marketTargetVersion:CONFIG.marketTargetVersion,disclaimer:CONFIG.targetDisclaimer,policy:CONFIG.primaryCohortPolicy,positiveRate:mean(probable.filter(r=>r.primaryEligible).map(r=>r.target)),neverSilentDrop:true};
}
function subgroups(rows,key,gate){return [...new Set(rows.map(r=>r[key]))].sort().map(value=>{const raw=rows.filter(r=>r[key]===value),a=raw.filter(r=>r.primaryEligible);return {group:value,universeN:raw.length,n:a.length,positives:a.reduce((n,r)=>n+r.target,0),observedRate:mean(a.map(r=>r.target)),status:a.length>=CONFIG.evaluation.minimumCell&&a.some(r=>r.target===1)&&a.some(r=>r.target===0)&&gate.status.startsWith('SUFFICIENT')?'DESCRIPTIVE_ONLY':'INSUFFICIENT_SAMPLE',models:Object.fromEntries(Array.from({length:5},(_,i)=>{const k=`pRecordedYellow_C${i}`;return [k,a.length>=CONFIG.evaluation.minimumCell&&gate.status.startsWith('SUFFICIENT')?probabilityMetrics(a.map(r=>({p:r[k],y:r.target}))):null];}))};});}
function exposureDiagnostics(rows,gate){const tagged=rows.map(r=>({...r,exposureBin:r.features.expectedMinutes===null?'MISSING':r.features.expectedMinutes<30?'<30':r.features.expectedMinutes<60?'30-59':r.features.expectedMinutes<75?'60-74':'75+',actualGroup:r.actualStarter===true?'ACTUAL_STARTER_DIAGNOSTIC':r.participation==='PLAYED'?'ACTUAL_SUBSTITUTE_DIAGNOSTIC':'UNUSED_OR_UNKNOWN',projectedGroup:r.projectedStarter?'PROJECTED_STARTER':'PROJECTED_RESERVE'}));const a=rows.filter(r=>r.primaryEligible),errors=a.map(r=>(r.pRecordedYellow_C2-r.target)**2);return {bins:['<30','30-59','60-74','75+','MISSING'],byExpectedMinutes:subgroups(tagged,'exposureBin',gate),byActualParticipation:subgroups(tagged,'actualGroup',gate),byProjectedParticipation:subgroups(tagged,'projectedGroup',gate),minutesErrorCorrelation:gate.status.startsWith('SUFFICIENT')?correlation(errors,a.map(r=>r.features.expectedMinutes===null||!finite(r.actualMinutes)?null:r.features.expectedMinutes-r.actualMinutes)):null,actualMinutesErrorCorrelation:gate.status.startsWith('SUFFICIENT')?correlation(errors,a.map(r=>r.actualMinutes)):null,substitutionEventErrorCorrelation:gate.status.startsWith('SUFFICIENT')?correlation(errors,a.map(r=>r.substitutionEventDiagnostic)):null,actualMinutesUsedAsFeature:false,informationAdvantage:'Actual minutes and starter/substitute categories are diagnostic only; models only see the target-time reconstructed Expected Minutes and probable XI state',target:CONFIG.target,disclaimer:CONFIG.targetDisclaimer,projectedParticipation:'Reserve Expected Minutes stay null because the repository has no target-time unconditional participation distribution'};}
function foulDiagnostics(rows,gate){
  const tagged=rows.map(r=>{const ratio=r.features.foulLogRatio;return {...r,foulBand:ratio===null?'MISSING':ratio<Math.log(0.75)?'LOW_<0.75X':ratio>Math.log(1.25)?'HIGH_>1.25X':'NEAR_LEAGUE_0.75-1.25X'};});
  const eligible=tagged.filter(r=>r.primaryEligible),available=eligible.filter(r=>finite(r.features.foulLogRatio));
  const tinyHigh=available.filter(r=>finite(r.features.dataOnly.foulsPer90)&&r.features.dataOnly.foulsPer90>=2&&(r.features.dataOnly.foulsMinutes??0)<450).sort((a,b)=>b.features.dataOnly.foulsPer90-a.features.dataOnly.foulsPer90).slice(0,10);
  return {target:CONFIG.target,disclaimer:CONFIG.targetDisclaimer,feature:'log stabilized combined current plus discounted historical fouls/90 versus walk-forward league rate',priorEquivalentMinutes:450,currentAvailable:eligible.filter(r=>finite(r.features.dataOnly.foulsPer90)).length,historicalAvailable:eligible.filter(r=>finite(r.features.dataOnly.historicalFoulsCommitted)&&finite(r.features.dataOnly.historicalFoulsMinutes)).length,combinedFeatureAvailable:available.length,missing:eligible.length-available.length,bands:subgroups(tagged,'foulBand',gate),tinyHighRateCases:tinyHigh.map(r=>({matchId:r.matchId,playerId:r.playerId,playerName:r.playerName,currentFouls:r.features.dataOnly.foulsCommitted,currentMinutes:r.features.dataOnly.foulsMinutes,currentFoulsPer90:r.features.dataOnly.foulsPer90,historicalFouls:r.features.dataOnly.historicalFoulsCommitted,historicalMinutes:r.features.dataOnly.historicalFoulsMinutes,stabilizedLogRatio:r.features.foulLogRatio,pC1:r.pRecordedYellow_C1,pC1PlusFouls:r.ablations.C1_PLUS_FOULS,pC2:r.pRecordedYellow_C2})),errorCorrelationWithFoulFeature:gate.status.startsWith('SUFFICIENT')?correlation(available.map(r=>(r.pRecordedYellow_C2-r.target)**2),available.map(r=>r.features.foulLogRatio)):null,interpretation:'Raw current rates are never used directly; 450 league-equivalent minutes plus discounted prior-season evidence stabilize the feature. Role-specific foul coefficients are not justified by this sample.'};
}
function fallbackAudit(rows){const probable=rows.filter(r=>r.informationSet==='PREMATCH_PROBABLE'),counts=key=>Object.fromEntries([...new Set(probable.map(r=>JSON.stringify(key(r))))].sort().map(serialized=>[serialized,probable.filter(r=>JSON.stringify(key(r))===serialized).length]));return {rows:probable.length,C0:counts(r=>r.fallback.C0),C1:counts(r=>r.fallback.C1),C2ExpectedMinutes:counts(r=>r.fallback.C2.expectedMinutes),C2Fouls:counts(r=>r.fallback.C2.fouls),C3:counts(r=>r.fallback.C3),C4:counts(r=>r.fallback.C4),allRowsExposeFallback:probable.every(r=>r.fallback&&r.fallback.C0&&r.fallback.C1&&r.fallback.C2&&r.fallback.C3&&r.fallback.C4)};}
function shrinkageExamples(){const prior={p:0.2,fallback:'SYNTHETIC_ROLE_PRIOR'},f={playerId:'toy',season:'2026-27',cutoff:'2026-10-03T12:00:00Z',historicalEligibleRecords:[]},records=(n,y,minutes,season='2026-27')=>Array.from({length:n},(_,i)=>({playerId:'toy',target:Number(i<y),actualMinutes:minutes/n,season,competition:'serie-a',contextCertified:true,availableAt:'2026-01-01T00:00:00Z',matchId:`toy-${season}-${i}`}));
  return [{name:'ALEX_JIMENEZ_TYPE_2_YELLOWS_45_MINUTES',cur:records(2,2,45)},{name:'ONE_YELLOW_20_MINUTES',cur:records(1,1,20)},{name:'TINY_SAMPLE_ZERO_YELLOWS',cur:records(2,0,60)},{name:'LARGE_HIGH_RATE',cur:records(60,24,5400)},{name:'LARGE_LOW_RATE',cur:records(60,2,5400)},{name:'NEW_PLAYER_NO_HISTORY',cur:[]},{name:'HISTORICAL_ONLY',cur:[],hist:records(40,8,3600,'2025-26')},{name:'CURRENT_CONTRADICTS_HISTORY',cur:records(5,4,450),hist:records(60,3,5400,'2025-26')}].map(c=>({name:c.name,category:'SYNTHETIC_BEHAVIOURAL_CHECK_NOT_HISTORICAL_PREDICTION',input:{priorProbability:0.2,current:c.cur,historical:c.hist??[]},...c1(prior,{...f,historicalEligibleRecords:c.hist??[]},c.cur)}));
}
function matchupAudit(input,rows){const primaryN=rows.filter(r=>r.primaryEligible).length,last=component=>[...rows].reverse().map(r=>r.components?.[component]).find(Boolean),opponent=last('C3'),team=last('teamAblation'),home=last('homeAblation');return [
  {signal:'OPPONENT_FOUL_DRAWING',dataFeatureN:rows.filter(r=>r.features.opponentLogRatio!==null).length,estimate:opponent},
  {signal:'ROLE_CARD_PRESSURE',dataFeatureN:rows.filter(r=>r.roleGroup!=='UNKNOWN').length,estimate:null,interpretation:'Role is already the C0 baseline; no second matchup modifier'},
  {signal:'DIRECT_DUEL',dataFeatureN:0,estimate:null,interpretation:'No verified player-versus-player disciplinary/foul attribution'},
  {signal:'FLANK_CENTRAL_PRESSURE',dataFeatureN:0,estimate:null,interpretation:'No verified disciplinary channel labels'},
  {signal:'OPPONENT_YELLOW_DRAWING',dataFeatureN:0,estimate:null,interpretation:'Team yellow totals do not identify which opponent drew the card'},
  {signal:'TEAM_DISCIPLINE_ABLATION',dataFeatureN:rows.filter(r=>r.features.teamFoulLogRatio!==null).length,estimate:team,interpretation:'Separate team-foul ablation; never auto-added to C3'},
  {signal:'HOME_AWAY_ABLATION',dataFeatureN:rows.length,estimate:home,interpretation:'Prespecified diagnostic only; never automatically retained'}
].map(x=>({signal:x.signal,dataFeatureN:x.dataFeatureN,eligibleTrainingN:primaryN,effectEstimate:x.estimate?.beta??null,uncertainty:x.estimate?.interval??null,persistence:x.estimate?.persistence??'NOT_ESTIMABLE',maturity:x.estimate?.maturity??(x.dataFeatureN?'IMMATURE':'UNKNOWN'),status:x.estimate?.status??(x.dataFeatureN?'WATCH':'UNKNOWN'),quantitativeInfluence:Boolean(x.estimate?.quantitativeInfluence),interpretation:x.interpretation??'Historical playerStats.foulsWon, team sums; exact target/future matches excluded'}));}
function refereeAudit(root){const d=read(root,'data/generated/referee-stats/2025-26/aggregates.json'),all=d.referees.filter(r=>r.competition==='serie-a'&&r.stage==='regular-season'),named=all.filter(r=>r.referee!=='provider:unknown'),matches=all.reduce((n,r)=>n+r.matches,0),yellows=all.reduce((n,r)=>n+(r.yellowCards??0),0),league=yellows/matches,k=12;
  return {source:'data/generated/referee-stats/2025-26/aggregates.json',competition:'serie-a',season:'2025-26',matchesInLeaguePool:matches,identifiedMatches:named.reduce((n,r)=>n+r.matches,0),unknownBucketMatches:all.filter(r=>r.referee==='provider:unknown').reduce((n,r)=>n+r.matches,0),leagueYellowPerMatch:league,rows:named.map(r=>{const shrunk=(k*league+(r.yellowCards??0))/(k+r.matches);return {referee:r.referee,identity:r.refereeSlug,matches:r.matches,yellows:r.yellowCards,yellowsPerMatch:r.yellowCardsPerMatch,leagueRelativeRate:r.yellowCardsPerMatch!==null?r.yellowCardsPerMatch/league:null,shrunkYellowPerMatch:shrunk,priorWeight:k/(k+r.matches),coverage:r.coverage,shrunkTargetEffect:null,shrinkage:'Descriptive match-yellow rate shrunk by 12 league-equivalent matches; not applied to player target',competition:r.competition,season:r.season,maturity:r.matches>=CONFIG.signal.minimumRefereeMatches?'MATURE_DESCRIPTIVE':'IMMATURE',status:'WATCH',quality:'DERIVED_MATCH_TOTALS_DIFFERENT_ESTIMAND; C4 requires walk-forward player-target evidence'};}),otherSeasons:[2023,2024,2025].map(y=>{const season=`${y}-${String(y+1).slice(2)}`,a=read(root,`data/normalized/referee-matches/${season}/serie-a.json`).matches,b=read(root,`data/normalized/referee-matches/${season}/serie-b.json`).matches;const {datasetCoverage}=require('../../referee-stats/coverage');return {season,serieA:datasetCoverage(a),serieB:datasetCoverage(b),neverPooled:true,rawGzipA:a.filter(m=>fs.existsSync(path.join(root,`data/raw/referee-stats/espn/${season}/serie-a/${m.providerFixtureId}.json.gz`))).length,rawGzipB:b.filter(m=>fs.existsSync(path.join(root,`data/raw/referee-stats/espn/${season}/serie-b/${m.providerFixtureId}.json.gz`))).length};})};}
function legacyAudit(root,input,rows,gate){const audit=[],scores=new Map();for(const f of ['data/sources/prediction-archive-md1-2026-27.json','data/sources/prediction-archive-md02-2026-27.json','data/sources/prediction-archive-md04-2026-27.json'])for(const p of read(root,f).predictions){const m=input.matches.find(m=>m.id===p.matchId),valid=m&&p.generatedAt&&p.generatedAt<kickoff(m);let resolved=0;for(const c of p.likelyBooked||[]){const aliases=(m?.playerIdentityAliases||[]).filter(a=>a.teamId===c.teamId&&[a.canonicalName,...a.aliases].some(n=>require('../../../js/pages/disciplinary.mjs').nameKey(n)===require('../../../js/pages/disciplinary.mjs').nameKey(c.name)));const id=c.playerId??(aliases.length===1?aliases[0].playerId:null);if(valid&&id){scores.set(`${p.matchId}|${id}`,c.riskScore);resolved++;}}audit.push({source:f,matchId:p.matchId,generatedAt:p.generatedAt,cutoff:m?kickoff(m):null,status:valid?'PREMATCH_TIMESTAMP_PASSES':'REJECTED_POST_KICKOFF_OR_UNKNOWN',resolvedScores:resolved,candidateCount:p.likelyBooked?.length??0});}
  for(const r of rows)r.legacyRiskScore=scores.get(`${r.matchId}|${r.playerId}`)??null;
  const paired=rows.filter(r=>r.primaryEligible&&finite(r.legacyRiskScore));return {archives:audit,availablePrematchScores:rows.filter(r=>finite(r.legacyRiskScore)).length,eligibleCommonScores:paired.length,rocAuc:gate.status.startsWith('SUFFICIENT')?require('./metrics').auc(paired.map(r=>({p:r.legacyRiskScore,y:r.target}))):null,prAuc:gate.status.startsWith('SUFFICIENT')?require('./metrics').averagePrecision(paired.map(r=>({p:r.legacyRiskScore,y:r.target}))):null,rankCorrelationWithModels:Object.fromEntries(Array.from({length:5},(_,i)=>[`C${i}`,spearman(paired.map(r=>r.legacyRiskScore),paired.map(r=>r[`pRecordedYellow_C${i}`]))])),ranking:gate.status.startsWith('SUFFICIENT')?require('./metrics').ranking(paired,'legacyRiskScore'):null,commonSubsetComparison:gate.status.startsWith('SUFFICIENT')?Object.fromEntries(Array.from({length:5},(_,i)=>{const k=`pRecordedYellow_C${i}`;return [k,{rocAuc:require('./metrics').auc(paired.map(r=>({p:r[k],y:r.target}))),prAuc:require('./metrics').averagePrecision(paired.map(r=>({p:r[k],y:r.target}))),ranking:require('./metrics').ranking(paired,k)}];})):null,properScores:null,calibrationExperiment:false,selectionBias:'Legacy top-five subset; comparison only on its exact intersecting IDs, separate from full-universe metrics',currentRegeneratedPredictionsUsed:false};}
function selectResearchLeader(evaluation,bootstrap){if(evaluation.gate.status.startsWith('INSUFFICIENT'))return {leader:'UNRESOLVED',reason:'INITIAL_COMPARISON_GATE_FAILED'};let leader='C0';for(let i=1;i<=4;i++){const comparison=bootstrap.comparisons.find(c=>c.id===`C${i}_MINUS_C${i-1}`);if(comparison?.label==='BETTER_WITH_EVIDENCE')leader=`C${i}`;else if(comparison?.label==='SIMILAR')break;else return {leader:'UNRESOLVED',reason:`${comparison?.id??'MISSING_COMPARISON'}_${comparison?.label??'UNAVAILABLE'}`,simplestSupported:leader};}return {leader,reason:'SIMPLEST_SEQUENTIAL_MODEL_WITH_PAIRED_EVIDENCE'};}
function readiness(input,evaluation,now=new Date().toISOString(),snapshotGate=null){const rows=input.matches.filter(m=>m.matchday===6&&m.competition==='serie-a'),checks=rows.map(m=>{const u=infoUniverse(input,m,'PREMATCH_PROBABLE');return {matchId:m.id,kickoff:kickoff(m),status:m.status,beforeKickoff:kickoff(m)>now,candidates:u.rows.length,unresolvedIds:u.rows.filter(r=>!r.playerId).length,duplicateIds:u.rows.length-new Set(u.rows.map(r=>`${r.teamId}|${r.playerId??r.currentName}`)).size,sourceAvailableAt:u.availableAt??null,sourceBeforeKickoff:Boolean(u.availableAt&&u.availableAt<kickoff(m)),refereeDesignation:m.refereeAssignment?.referee?.slug??null,disciplinaryActualIncluded:Boolean(m.score||m.bookings?.length)};});const blockers=[];if(evaluation.gate.status.startsWith('INSUFFICIENT'))blockers.push('INITIAL_RECORDED_YELLOW_COMPARISON_INSUFFICIENT');if(checks.length!==10||checks.some(c=>!c.beforeKickoff||c.status!=='scheduled'||!c.candidates||c.unresolvedIds||c.duplicateIds||!c.sourceBeforeKickoff||c.disciplinaryActualIncluded))blockers.push('MD6_FIXTURE_IDENTITY_TIMING_OR_OUTCOME_GATE');if(snapshotGate?.infrastructure!=='READY')blockers.push('SNAPSHOT_SCHEMA_OR_PAYLOAD_GATE');const infrastructure=blockers.length?'NOT READY':'READY',final=snapshotGate?.finalFreeze==='READY_TO_FREEZE'&&infrastructure==='READY'?'READY TO FREEZE':'WAIT FOR LATER PRE-KICKOFF REFRESH';return {status:infrastructure==='READY'?'TECHNICALLY_READY_FOR_MD6_RESEARCH_SNAPSHOT':'NOT_READY_FOR_MD6_RESEARCH_SNAPSHOT',checkedAt:now,checks,blockers,snapshotValidation:snapshotGate,snapshotCreated:false,dryRunOnly:true,bookmakerCertifiedActualsReady:false,observationalActualsReady:true,infrastructure,finalSnapshot:final,nextProcess:['Refresh probable lineups inside the prespecified pre-kickoff freshness window.','Import and verify referee designations when available; C4 remains a transparent neutral fallback meanwhile.','Re-run the deterministic research and snapshot readiness checks; never recalculate a frozen snapshot after outcomes.','After completion, join RECORDED_YELLOW and PLAYER_YELLOW actuals as permanently separate layers.'],commandToRecheck:'node scripts/research/cards/run.js --snapshot-readiness',freezeCommand:final==='READY TO FREEZE'?'node scripts/research/cards/run.js --freeze-md6 --reason "final pre-kickoff refresh"':null,freezeCommandReason:final==='READY TO FREEZE'?null:'Inputs are technically valid but still too early/provisional for the final immutable snapshot'};}
module.exports={auditSample,subgroups,exposureDiagnostics,foulDiagnostics,fallbackAudit,shrinkageExamples,matchupAudit,refereeAudit,legacyAudit,selectResearchLeader,readiness};
