"use strict";
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{execFileSync}=require('child_process');
const hash=x=>crypto.createHash('sha256').update(x).digest('hex');
const allowed=f=>f.startsWith('scripts/research/cards/')||f.startsWith('data/analysis/card-prediction-research/')||f.startsWith('output/reports/card-prediction-research-c0-c4-')||f.startsWith('data/predictions/card-snapshots/2026-27/')||f==='data/predictions/card-snapshots/manifest.json'||f==='scripts/test-card-prediction-research.js'||f==='docs/card-prediction-research-c0-c4.md'||f==='package.json';
const protectedProduction=f=>f==='data/normalized/predictions.json'||f.startsWith('data/predictions/snapshots/')||f.startsWith('data/analysis/exact-score-research/')||f.startsWith('scripts/research/exact-score/')||f.startsWith('scripts/predictions/')||f==='scripts/build-predictions.js'||f==='scripts/disciplinary-features.js'||f==='scripts/build-team-matchup-profiles.js'||f==='data/sources/team-matchup-profiles-2026-27.json'||/^data\/sources\/(mycombo-|schedina-|sisal-|prediction-archive-|card-settlement-)/.test(f)||f==='scripts/mycombo-market-policy.js'||f==='scripts/enforce-mycombo-risk.js'||f.startsWith('js/')||f.startsWith('css/')||f.endsWith('.html');
function capture(root){const files=execFileSync('git',['-c','core.quotepath=false','ls-files','-co','--exclude-standard','-z'],{cwd:root,maxBuffer:32*1024*1024}).toString().split('\0').filter(Boolean);return Object.fromEntries([...new Set(files)].filter(f=>!allowed(f)&&fs.statSync(path.join(root,f)).isFile()).sort().map(f=>[f,hash(fs.readFileSync(path.join(root,f)))]));}
function captureProtected(root){const all=capture(root);return Object.fromEntries(Object.entries(all).filter(([file])=>protectedProduction(file)));}
const externalPaths=new Set(['scripts/build-champions-player-stats.js','scripts/import-champions-pilot-stats.js','data/normalized/champions-player-stats-2026-27.json','scripts/test-champions-current-season-data.js','data/sources/champions-pilot-match-stats-2025-27.json','data/raw/champions-pilot/espn/scoreboards/2026-27/gre.1/2026-as-of-2026-10-03.json.gz',...['401896758','401896764','401896769','401896771','401896829'].map(id=>`data/raw/champions-pilot/espn/summaries/2026-27/gre.1/2026-10-03/${id}.json.gz`)]);
function classify(before,after,authorization=null){
  const accepted=authorization?.origin==='HUMAN_USER_CONFIRMATION'&&authorization?.scope==='PARALLEL_CHAMPIONS_WORK'?authorization.files:[];
  const changed=[...new Set([...Object.keys(before),...Object.keys(after)])].filter(f=>before[f]!==after[f]);
  const authorizedExternalChanges=changed.filter(file=>externalPaths.has(file)&&accepted.some(a=>a.file===file&&a.baselineSha256===before[file]&&a.acceptedSha256===after[file])).map(file=>({file,before:before[file],after:after[file],origin:'USER_CONFIRMED_PARALLEL_CHAMPIONS_WORK'}));
  return {changed,authorizedExternalChanges,unexpected:changed.filter(file=>!authorizedExternalChanges.some(a=>a.file===file))};
}
function assertUnchanged(root,before){const after=capture(root),record=path.join(root,'data/analysis/card-prediction-research/parallel-work-authorization.json');const authorization=fs.existsSync(record)?JSON.parse(fs.readFileSync(record,'utf8')):null;const audit=classify(before,after,authorization);if(audit.unexpected.length)throw new Error(`PRODUCTION_FREEZE_VIOLATION: ${audit.unexpected.join(', ')}`);return {status:audit.authorizedExternalChanges.length?'PASS_WITH_USER_CONFIRMED_PARALLEL_CHANGES':'PASS',checkedFiles:Object.keys(before).length,unchangedFiles:Object.keys(before).filter(f=>before[f]===after[f]).length,changedFiles:[],authorizedExternalChanges:audit.authorizedExternalChanges,originalBaselinePreserved:true,files:[...new Set([...Object.keys(before),...Object.keys(after)])].map(file=>({file,before:before[file]??null,after:after[file]??null,unchanged:before[file]===after[file],authorizedParallelChange:audit.authorizedExternalChanges.some(a=>a.file===file)}))};}
function assertProtectedUnchanged(root,before){const after=captureProtected(root),changed=[...new Set([...Object.keys(before),...Object.keys(after)])].filter(file=>before[file]!==after[file]);if(changed.length)throw new Error(`PRODUCTION_FREEZE_VIOLATION: ${changed.join(', ')}`);return {status:'PASS',scope:'TASK_REQUIRED_PROTECTED_PRODUCTION_ARTIFACTS',checkedFiles:Object.keys(before).length,unchangedFiles:Object.keys(before).filter(file=>before[file]===after[file]).length,changedFiles:[],authorizedExternalChanges:[],originalBaselinePreserved:true,files:[...new Set([...Object.keys(before),...Object.keys(after)])].map(file=>({file,before:before[file]??null,after:after[file]??null,unchanged:before[file]===after[file]}))};}
module.exports={hash,allowed,protectedProduction,capture,captureProtected,classify,assertUnchanged,assertProtectedUnchanged};
