"use strict";
const fs=require('fs'),path=require('path'),{spawnSync}=require('child_process');
const {CONFIG}=require('./config'),I=require('./integrity'),D=require('./data'),M=require('./models'),E=require('./metrics'),A=require('./diagnostics'),S=require('./snapshot');
const root=path.resolve(__dirname,'../../..'),out='data/analysis/card-prediction-research',reportBase='output/reports/card-prediction-research-c0-c4-recorded-yellow-2026-10-04';
function write(f,value){const target=path.join(root,f);if(!I.allowed(f))throw new Error('Research write outside allowlist');fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,typeof value==='string'?value:JSON.stringify(value,null,2)+'\n');}
function build(input){const dataset=D.construct(input),predictions=[];
  for(const row of dataset.rows){const features=M.features(input,row),ids=new Set(features.provenance.sourceMatchIds),train=predictions.filter(p=>p.primaryEligible&&p.informationSet===row.informationSet&&ids.has(p.matchId));
    const p=M.predict(features,train),m=input.matches.find(m=>m.id===row.matchId),subs=(m.substitutions||[]).filter(s=>s.playerInId===row.playerId||s.playerOutId===row.playerId).length;
    predictions.push({...row,season:m.season,expectedMinutes:features.expectedMinutes,expectedMinutesReliability:features.expectedMinutesReliability,substitutionRisk:features.substitutionRisk,modelId:'C0_C1_C2_C3_C4',models:Array.from({length:5},(_,i)=>({modelId:`C${i}`,modelVersion:CONFIG.version,state:'RESEARCH',target:CONFIG.target,probability:p[`pRecordedYellow_C${i}`]})),features,...p,legacyRiskScore:null,substitutionEventDiagnostic:subs,training:{matchIds:[...new Set(train.map(r=>r.matchId))],observations:train.length,positives:train.reduce((n,r)=>n+r.target,0),sourceMatchIds:features.provenance.sourceMatchIds}});
  }
  const probable=predictions.filter(r=>r.informationSet==='PREMATCH_PROBABLE'),official=predictions.filter(r=>r.informationSet==='PREMATCH_OFFICIAL');
  return {dataset,predictions,evaluations:{PREMATCH_PROBABLE:E.evaluate(probable),PREMATCH_OFFICIAL:E.evaluate(official)},bootstrap:E.bootstrap(probable)};
}
function registry(){const implementationHashes=Object.fromEntries(['config.js','data.js','models.js','metrics.js','snapshot.js'].map(f=>[f,I.hash(fs.readFileSync(path.join(__dirname,f),'utf8').replace(/\r\n/g,'\n'))]));const hash=I.hash(JSON.stringify({config:CONFIG,implementationHashes}));return {registryVersion:2,configurationHash:hash,configurationOnlyHash:I.hash(JSON.stringify(CONFIG)),implementationHashes,disclaimer:CONFIG.targetDisclaimer,observationalTarget:{id:CONFIG.target,version:CONFIG.targetVersion},marketCertifiedTarget:{id:CONFIG.marketTarget,version:CONFIG.marketTargetVersion,status:'NOT_VALIDATED'},allowedStates:['RESEARCH','SHADOW','CANDIDATE','PRODUCTION'],promotionEnabled:false,models:[
  {id:'C0',family:'Beta-Binomial hierarchical population baseline',formula:'Jeffreys league posterior; broad and supported detailed roles shrunk with k=12; leave target individual out of population prior',features:['league','broad role','supported detailed role']},
  {id:'C1',family:'Exposure-tempered Beta-Binomial individual posterior',formula:'(k*pC0 + discounted prior-season/current observational successes)/(k + effective samples)',features:['C0','timestamped 2025-26 Serie A ordinary-yellow aggregate','walk-forward current RECORDED_YELLOW history','sample maturity']},
  {id:'C2',family:'Training-fold penalized logistic offsets',formula:'logit(pC2)=logit(pC1)+bEM*xEM+bF*xF; coefficients estimated only on earlier matches with ridge=4',features:['C1','pre-match Expected Minutes','stabilized historical/current fouls/90']},
  {id:'C3',family:'Training-only logistic opponent offset, maturity/persistence gate',formula:'logit(pC3)=logit(pC2)+bO*xO only if ACTIVE; otherwise C3=C2',features:['C2','opponent foul-drawing pressure; other duel/channel families data-only']},
  {id:'C4',family:'Referee Beta-Binomial environment with eligible player-target evidence',formula:'Referee posterior shrunk toward pre-match league environment; only mature/persistent same-competition effect can alter C3; otherwise C4=C3',features:['C3','pre-match designated referee','eligible target history']}
].map(m=>({...m,state:'RESEARCH',version:CONFIG.version,target:CONFIG.target,targetVersion:CONFIG.targetVersion,disclaimer:CONFIG.targetDisclaimer,estimand:CONFIG.estimand,configurationHash:hash,priors:CONFIG.leaguePrior,shrinkage:CONFIG.shrinkage,dataCutoff:'Per-player target kickoff, source availability enforced',limitations:['Observational target, not bookmaker-certified','No prospective validation yet','No model promotion']}))};}
function collect(root,artifacts,production,validation){const input=artifacts.input,probable=artifacts.predictions.filter(r=>r.informationSet==='PREMATCH_PROBABLE'),evalMain=artifacts.evaluations.PREMATCH_PROBABLE;
  const generatedAt=new Date().toISOString(),modelRegistry=registry(),sample=A.auditSample(input,artifacts.dataset,artifacts.predictions),legacy=A.legacyAudit(root,input,artifacts.predictions,evalMain.gate),selection=A.selectResearchLeader(evalMain,artifacts.bootstrap),snapshotPreview=S.buildPreview(root,input,artifacts.predictions,{generatedAt,configurationHash:modelRegistry.configurationHash,researchLeader:selection.leader}),snapshotValidation=S.validatePreview(snapshotPreview),snapshotGate=S.freezeGate(snapshotPreview,generatedAt),readiness=A.readiness(input,evalMain,generatedAt,snapshotGate);
  return {generatedAt,state:'RESEARCH',category:'RETROSPECTIVE_RESEARCH',target:CONFIG.target,targetVersion:CONFIG.targetVersion,marketTarget:CONFIG.marketTarget,marketTargetVersion:CONFIG.marketTargetVersion,disclaimer:CONFIG.targetDisclaimer,config:CONFIG,registry:modelRegistry,researchLeader:selection,sample,evaluations:artifacts.evaluations,bootstrap:artifacts.bootstrap,legacy,
    leakage:{status:'PASS',targetExcluded:artifacts.predictions.every(r=>!r.features.provenance.sourceMatchIds.includes(r.matchId)),futureExcluded:artifacts.predictions.every(r=>r.features.provenance.sourceMatchIds.every(id=>D.priorMatches(input.matches,input.matches.find(m=>m.id===r.matchId)).some(m=>m.id===id))),actualMinutesPredictor:false,sourceTimestampGate:true,officialInformationSetsNeverPooled:true,sourceRevisionCaution:'Reconstructed event-time histories, not frozen historical feature states; no claimed prospective validation',trainingByMatch:input.completed.map(m=>({matchId:m.id,cutoff:D.kickoff(m),role:'RETROSPECTIVE_ONLY',models:artifacts.predictions.filter(r=>r.matchId===m.id).map(r=>({playerId:r.playerId,informationSet:r.informationSet,n:r.training.observations,matchIds:r.training.matchIds}))}))},
    roles:A.subgroups(probable,'roleGroup',evalMain.gate),detailedRoles:A.subgroups(probable,'detailedRole',evalMain.gate),exposure:A.exposureDiagnostics(probable,evalMain.gate),fouls:A.foulDiagnostics(probable,evalMain.gate),fallbacks:A.fallbackAudit(artifacts.predictions),teams:A.subgroups(probable,'team',evalMain.gate),opponents:A.subgroups(probable,'opponent',evalMain.gate),homeAway:A.subgroups(probable,'homeAway',evalMain.gate),matchupSignals:A.matchupAudit(input,probable),referees:A.refereeAudit(root),shrinkageExamples:A.shrinkageExamples(),readiness,snapshotPreview,snapshotValidation,production,validation,
    filesChanged:[...new Set([...Object.keys(production.researchFiles),reportBase+'.md',reportBase+'.json','package.json'])].sort(),limitations:['RECORDED_YELLOW is an observational source-event target and is never interchangeable with PLAYER_YELLOW.','Retrospective feature state is reconstructed as-of from timestamped inputs; it is not a set of historically frozen feature snapshots.','Date-only official lineups cannot prove capture before kickoff, so the primary comparison uses probable-lineup universes only.','Reserve Expected Minutes remain null because no target-time unconditional participation distribution is preserved.','Prior-season Serie A category totals do not certify bookmaker context; other competitions are not pooled.','C4 has no active referee adjustment in this five-matchday sample; historical referee totals have a different estimand.','Legacy archives yield only a tiny pre-match score intersection and remain ranking-only.','Missing referee raw gzip files still block independent historical referee reconstruction.','Jeffreys prior-only 0.5 affects earliest no-training rows and is a mathematical reference, not a calibrated league card rate.'],verdicts:['CARD MODEL STATE: RESEARCH','OBSERVATIONAL TARGET: RECORDED_YELLOW',`C0-C4 COMPARISON: ${evalMain.gate.status.startsWith('SUFFICIENT')?'VALID FOR INITIAL RESEARCH':'INSUFFICIENT'}`,`RESEARCH LEADER: ${selection.leader}`,`MD6 SNAPSHOT INFRASTRUCTURE: ${readiness.infrastructure}`,`FINAL MD6 SNAPSHOT: ${readiness.finalSnapshot}`,'BOOKMAKER-CERTIFIED CARD MODEL: NOT VALIDATED','PRODUCTION CARD MODEL: UNCHANGED','NO MODEL PROMOTION']};
}
function validate(){
  const scripts=['scripts/test-card-prediction-research.js','scripts/test-card-foundation.mjs','scripts/test-player-identities.js','scripts/test-predictions.js','scripts/test-team-matchup-profiles.js','scripts/test-future-data-readiness.js','scripts/test-prediction-snapshots.js','scripts/test-exact-score-research.js','scripts/test-schedina.js','scripts/test-schedina-md04.js','scripts/test-schedina-md05-results.mjs','scripts/test-champions-player-markets.js'];
  const results=scripts.map(file=>{const r=spawnSync(process.execPath,[file],{cwd:root,encoding:'utf8',maxBuffer:5*1024*1024});const knownBlocker=file==='scripts/test-exact-score-research.js'&&r.status!==0&&/PRODUCTION_FREEZE_VIOLATION/.test(r.stderr)&&/test-baselines\.js:138/.test(r.stderr)&&fs.existsSync(path.join(root,'tmp/exact-score-m1-m2-before.json'));return {file,passed:r.status===0,exitCode:r.status,knownBlocker,knownBlockerReason:knownBlocker?'Legacy tmp/exact-score-m1-m2-before.json repository inventory predates Phase 1 and rejects separate new card research files; original assertion and baseline retained':null,stdout:r.stdout,stderr:r.stderr};});
  const card=results.find(r=>r.file==='scripts/test-card-prediction-research.js');let cardAssertions=null;try{cardAssertions=JSON.parse(card.stdout).passed;}catch{}
  return {suites:results.length,passed:results.filter(r=>r.passed).length,failed:results.filter(r=>!r.passed).length,unexpectedFailures:results.filter(r=>!r.passed&&!r.knownBlocker).length,knownBlockers:results.filter(r=>r.knownBlocker).length,cardAssertions,cardAssertionFailures:card?.passed?0:null,results,browserRequired:false,reason:'No UI/CSS/HTML/production contracts changed in this research-only task'};
}
function main(args=process.argv.slice(2)){
  const known=new Set(['--snapshot-readiness','--freeze-md6','--replace','--reason']),unknown=args.filter((a,i)=>!known.has(a)&&args[i-1]!=='--reason');if(unknown.length)throw new Error(`Unknown research option: ${unknown.join(', ')}`);const freeze=args.includes('--freeze-md6'),replace=args.includes('--replace'),reasonIndex=args.indexOf('--reason'),reason=reasonIndex>=0?args[reasonIndex+1]:null;
  const inventoryFile=`${out}/production-before.json`,inventoryBefore=fs.existsSync(path.join(root,inventoryFile))?D.read(root,inventoryFile).hashes:I.capture(root),beforeFile=`${out}/production-protected-before-recorded-yellow.json`,before=fs.existsSync(path.join(root,beforeFile))?D.read(root,beforeFile).hashes:I.captureProtected(root);
  if(!fs.existsSync(path.join(root,inventoryFile)))write(inventoryFile,{capturedAt:new Date().toISOString(),phase:'PHASE_2A',hashes:inventoryBefore,packageJsonBeforeSha256:I.hash(fs.readFileSync(path.join(root,'package.json')))});
  if(!fs.existsSync(path.join(root,beforeFile)))write(beforeFile,{capturedAt:new Date().toISOString(),phase:'RECORDED_YELLOW_C0_C4',scope:'TASK_REQUIRED_PROTECTED_PRODUCTION_ARTIFACTS',hashes:before});
  I.assertProtectedUnchanged(root,before);
  const input=D.load(root),artifacts={input,...build(input)},validation=validate();
  if(validation.unexpectedFailures)throw new Error(`RESEARCH_TEST_FAILURE: ${validation.results.filter(r=>!r.passed&&!r.knownBlocker).map(r=>r.file+': '+r.stderr+r.stdout).join('\n')}`);
  const production=I.assertProtectedUnchanged(root,before),repositoryNow=I.capture(root);production.outOfScopeRepositoryDriftPresentAtCheck=[...new Set([...Object.keys(inventoryBefore),...Object.keys(repositoryNow)])].filter(file=>inventoryBefore[file]!==repositoryNow[file]&&!I.protectedProduction(file));
  const {execFileSync}=require('child_process');const all=execFileSync('git',['ls-files','-co','--exclude-standard','-z'],{cwd:root,maxBuffer:32*1024*1024}).toString().split('\0').filter(f=>f&&I.allowed(f)&&f!=='package.json');
  const planned=[`${out}/config.json`,`${out}/model-registry.json`,`${out}/retrospective-player-match.json`,`${out}/sample-audit.json`,`${out}/evaluation.json`,`${out}/bootstrap.json`,`${out}/validation.json`,`${out}/md6-readiness.json`,`${out}/md6-snapshot-preview.json`,`${out}/card-snapshot.schema.json`,`${out}/calibration-status.svg`,`${out}/input-manifest.json`];
  production.researchFiles=Object.fromEntries([...new Set([...all,...planned])].map(f=>[f,fs.existsSync(path.join(root,f))?I.hash(fs.readFileSync(path.join(root,f))):'GENERATED_AFTER_CHECK']));
  const report=collect(root,artifacts,production,validation);
  write(`${out}/config.json`,CONFIG);write(`${out}/model-registry.json`,report.registry);write(`${out}/retrospective-player-match.json`,{state:'RESEARCH',category:'RETROSPECTIVE_RESEARCH',snapshot:false,configHash:report.registry.configurationHash,estimand:CONFIG.estimand,rows:artifacts.predictions});
  write(`${out}/sample-audit.json`,{...report.sample,participantAudit:artifacts.dataset.participantAudit});write(`${out}/evaluation.json`,{target:CONFIG.target,disclaimer:CONFIG.targetDisclaimer,evaluations:report.evaluations,roles:report.roles,exposure:report.exposure,fouls:report.fouls,fallbacks:report.fallbacks,teams:report.teams,opponents:report.opponents,homeAway:report.homeAway,matchupSignals:report.matchupSignals,referees:report.referees,legacy:report.legacy,researchLeader:report.researchLeader});write(`${out}/bootstrap.json`,report.bootstrap);write(`${out}/validation.json`,validation);write(`${out}/md6-readiness.json`,report.readiness);write(`${out}/md6-snapshot-preview.json`,report.snapshotPreview);write(`${out}/card-snapshot.schema.json`,S.snapshotSchema());
  write(`${out}/input-manifest.json`,{category:'RESEARCH_INPUT_INVENTORY_NOT_PREDICTION_SNAPSHOT',captureAt:report.generatedAt,configHash:report.registry.configurationHash,target:CONFIG.target,disclaimer:CONFIG.targetDisclaimer,sources:Object.entries(inventoryBefore).filter(([f])=>f.startsWith('data/')&&(/matches.json|probable-lineups|official-lineups|squad.json|referee|prediction-archive|snapshots/.test(f))).map(([file,sha256])=>({file,sha256})),historicalKnowledgeState:'Retrospective event-time reconstruction from timestamp-gated sources; no claim that every feature vector was historically frozen'});
  write(`${out}/calibration-status.svg`,require('./report').calibrationStatus(report));write(reportBase+'.md',require('./report').markdown(report));
  report.production=I.assertProtectedUnchanged(root,before);report.production.outOfScopeRepositoryDriftPresentAtCheck=production.outOfScopeRepositoryDriftPresentAtCheck;let frozen=null;if(freeze)frozen=S.writeFrozenSnapshot(root,report.snapshotPreview,{replace,reason});report.snapshotWrite=frozen;write(reportBase+'.json',report);
  console.log(JSON.stringify({state:'RESEARCH',target:CONFIG.target,completedMatches:report.sample.completedMatches,projectedRows:report.sample.probableRecords,positives:report.sample.observationalPositives,primaryEligible:report.sample.primaryEligible,sampleStatus:report.evaluations.PREMATCH_PROBABLE.gate.status,researchLeader:report.researchLeader.leader,tests:validation.passed+'/'+validation.suites,knownValidationBlockers:validation.knownBlockers,productionFilesUnchanged:report.production.unchangedFiles,authorizedParallelChanges:report.production.authorizedExternalChanges.length,readiness:report.readiness.status,finalSnapshot:report.readiness.finalSnapshot,snapshotWritten:Boolean(frozen),report:reportBase+'.md'},null,2));return report;
}
if(require.main===module)main();
module.exports={root,out,reportBase,write,build,registry,collect,validate,main};
