"use strict";
const { FEATURE_DEFINITIONS, FEATURE_GROUPS } = require("./contracts");
const nullableNumber = { type: ["number", "null"] };
const cutoffSchema = { type: "object", additionalProperties: false, required: ["mode", "matchdayExclusive", "targetMatchIdExcluded", "completedOnly", "effectiveDateExclusive"], properties: {
  mode: { const: "asOfMatchday" }, matchdayExclusive: { type: "integer", minimum: 1 }, targetMatchIdExcluded: { type: "string", minLength: 1 }, completedOnly: { const: true }, effectiveDateExclusive: { type: "string", format: "date-time" }
} };
const provenanceSchema = { type: "object", additionalProperties: false, required: ["source", "sourceHash", "cutoff", "period", "kind", "availability", "matchesUsed", "sample", "availableBefore", "competition", "season", "note"], properties: {
  source: { type: "string", minLength: 1 }, sourceHash: { type: "string", minLength: 1 }, cutoff: cutoffSchema, period: { enum: ["CURRENT", "HISTORICAL", "MIXED", "CONTEXT", "UNAVAILABLE"] }, kind: { enum: ["OBSERVED", "PREDICTED", "CONTEXT", "UNAVAILABLE"] }, availability: { enum: ["AVAILABLE", "UNAVAILABLE"] }, matchesUsed: { type: "array", uniqueItems: true, items: { type: "string" } }, historicalMatchesUsed: { type: "array", uniqueItems: true, items: { type: "string" } }, sample: { type: "integer", minimum: 0 }, availableBefore: { type: ["string", "null"] }, competition: { type: ["string", "null"] }, season: { type: ["string", "null"] }, note: { type: ["string", "null"] }
} };
const featureVectorSchema = { $schema: "https://json-schema.org/draft/2020-12/schema", title: "ExactScoreFeatureVector", type: "object", additionalProperties: false,
  required: ["schemaVersion", "matchId", "homeTeam", "awayTeam", "targetMatchday", "generationClass", "retrospective", "dataCutoff", "scenario", "predictionEligible", "features", "diagnostics"], properties: {
    schemaVersion: { const: 1 }, matchId: { type: "string" }, homeTeam: { type: "string" }, awayTeam: { type: "string" }, targetMatchday: { type: "integer", minimum: 1 }, generationClass: { enum: ["PROSPECTIVE", "RETROSPECTIVE"] }, retrospective: { type: "boolean" }, dataCutoff: cutoffSchema, scenario: { const: "PREDICTED PROCESS" }, predictionEligible: { const: true }, diagnostics: { type: "object" },
    features: { type: "object", additionalProperties: false, required: Object.keys(FEATURE_DEFINITIONS), properties: Object.fromEntries(Object.entries(FEATURE_DEFINITIONS).map(([key, definition]) => [key, { type: "object", additionalProperties: false, required: ["value", "group", "provenance"], properties: { value: nullableNumber, group: { const: definition.group }, provenance: provenanceSchema } }])) }
  }, $comment: "Runtime temporal/identity/source/availability checks are mandatory in addition to structural schema validation." };
const scalarMetrics = { type: "object", required: ["n", "mae", "rmse", "bias"], properties: { n: { type: "integer", minimum: 0 }, mae: nullableNumber, rmse: nullableNumber, bias: nullableNumber } };
const evaluationSchema = { $schema: "https://json-schema.org/draft/2020-12/schema", title: "ExactScoreResearchEvaluation", type: "object", required: ["schemaVersion", "exactScoreDataGate", "researchOnly", "promotionDisabled", "sameSample", "retrospective", "prospective", "caution", "nextAction"], properties: {
  schemaVersion: { const: 1 }, researchOnly: { const: true }, promotionDisabled: { const: true }, exactScoreDataGate: { enum: ["INSUFFICIENT", "COLLECTING", "READY_FOR_BASELINE_MODEL"] }, sameSample: { type: "object", required: ["matchIds", "n", "folds"], properties: { matchIds: { type: "array", uniqueItems: true, items: { type: "string" } }, n: { type: "integer", minimum: 0 }, folds: { type: "array" } } },
  retrospective: { type: "object", required: ["label", "models"], properties: { label: { const: "RETROSPECTIVE RESEARCH ONLY" }, models: { type: "array", items: { type: "object", required: ["model", "sample", "temporalCoverage", "goalMAE", "scoreLogLoss", "exactHitRate", "top3Coverage", "top5Coverage", "actualScoreRank", "oneXtwo", "btts", "overUnder", "calibration", "lowScores", "drawDiagnostic", "uncertainty", "matchDiagnostics"], properties: { sample: { type: "integer", minimum: 0 }, scoreLogLoss: nullableNumber, exactHitRate: nullableNumber, top3Coverage: nullableNumber, top5Coverage: nullableNumber, goalMAE: { type: "object", required: ["home", "away", "total"], properties: { home: scalarMetrics, away: scalarMetrics, total: scalarMetrics } } } } } } },
  prospective: { type: "object", required: ["pendingMatches", "evaluatedMatches", "exactScorePredictions", "models", "metrics"], properties: { evaluatedMatches: { const: 0 }, exactScorePredictions: { const: 0 }, metrics: { type: "null" }, models: { type: "array", maxItems: 0 } } }, caution: { const: "Exact score hit rate is a secondary metric." }
} };
module.exports = { featureVectorSchema, evaluationSchema, FEATURE_GROUPS };
