import {cardType} from './disciplinary.mjs';
const isFiniteNumber=value=>typeof value==="number"&&Number.isFinite(value);
const decimal=(value,digits=1)=>isFiniteNumber(value)?value.toLocaleString("it-IT",{minimumFractionDigits:digits,maximumFractionDigits:digits}):"N/D";
const probability=value=>isFiniteNumber(value)?`${(value*100).toLocaleString("it-IT",{minimumFractionDigits:0,maximumFractionDigits:1})}%`:"N/D";
const riskLabel=value=>value==="low"?"basso":value==="medium"?"medio":value==="high"?"alto":null;
const tierLabel=value=>value==="primary"?"PRIMARY":value==="co-primary"?"CO-PRIMARY":value==="secondary"?"SECONDARY":null;
const confidenceLabel=value=>value==="high"?"alta":value==="medium"?"media":value==="low"?"bassa":value||null;
const signalQuality=value=>!isFiniteNumber(value)?"Dati insufficienti":value>=.75?"Segnale forte":value>=.55?"Segnale medio":"Segnale debole";
const playerKey=player=>`${player?.playerId||player?.name||""}|${player?.teamId||player?.team||""}`;

export function fixtureLineupForMatch(match,team,teamDirectory){
  const official=teamDirectory?.officialLineups?.[`${match?.id}:${team?.id}`];
  if(official)return official;
  const lineup=team?.probableLineup;
  if(lineup?.status==="official"&&lineup.matchId!==match?.id)return team.projectedLineup||{...lineup,status:"reference"};
  if(lineup?.matchday&&lineup.matchday!==match?.matchday)return {...lineup,status:"reference",context:`Riferimento dalla ${lineup.matchday}ª giornata`};
  return lineup;
}

export function formationPresentation(match,teamDirectory){
  const teams=teamDirectory?.teams||[],meta=id=>teams.find(team=>team.id===id);
  const fixtureLineup=team=>fixtureLineupForMatch(match,team,teamDirectory);
  const lineups=[fixtureLineup(meta(match?.homeTeam)),fixtureLineup(meta(match?.awayTeam))];
  const official=lineups.length===2&&lineups.every(lineup=>lineup?.status==="official");
  const probable=lineups.some(lineup=>lineup?.status==="probable");
  return official?{status:"official",label:"FORMAZIONI UFFICIALI",note:"Le proiezioni individuali utilizzano le distinte ufficiali disponibili."}:probable?{status:"probable",label:"FORMAZIONI PROBABILI",note:"Le proiezioni individuali possono cambiare dopo le formazioni ufficiali."}:{status:"unconfirmed",label:"FORMAZIONI DA CONFERMARE",note:"Le probabilità individuali saranno aggiornate dopo le formazioni ufficiali."};
}

export function renderPredictionV2Sections({prediction,teams=[],esc=value=>String(value),teamLogo=()=>""}={}){
  const teamFor=id=>teams.find(team=>team.id===id)||{id,name:id||"N/D"};
  const metric=(value,digits=1)=>decimal(value,digits);
  const interval=source=>{
    if(!source||![source.min,source.central,source.max].every(isFiniteNumber))return '<span class="prediction-v2-missing">N/D</span>';
    const span=source.max-source.min,position=span>0?Math.max(0,Math.min(100,(source.central-source.min)/span*100)):50;
    const label=`${metric(source.central)}; intervallo ${metric(source.min)} - ${metric(source.max)}`;
    return `<span class="prediction-v2-value">${metric(source.central)}</span><span class="prediction-v2-range-text">${metric(source.min)} — ${metric(source.max)}</span><span class="prediction-v2-range" role="img" aria-label="${esc(label)}"><i aria-hidden="true" style="--range-position:${position.toFixed(1)}%"></i></span>`;
  };
  const projectionCard=projection=>{const team=teamFor(projection.teamId),channels=projection.attackChannels,channelLabel=channel=>channel==="left"?"Fascia sinistra":channel==="right"?"Fascia destra":"Zona centrale";const attackChannels=channels?`<details class="prediction-v2-channels"><summary>Direzioni d'attacco</summary><div class="prediction-channels"><span>Lati d'attacco</span>${[["left","Sinistra"],["central","Centro"],["right","Destra"]].map(([key,label])=>`<div><small>${label}</small><i aria-hidden="true"><b style="width:${isFiniteNumber(channels[key])?channels[key]:0}%"></b></i><strong>${isFiniteNumber(channels[key])?metric(channels[key]):"N/D"}%</strong></div>`).join("")}<em>Canale prevalente: ${channelLabel(channels.dominant)}</em></div></details>`:"";return `<article class="prediction-v2-team-card">${teamLogo(team)}<div class="prediction-v2-team-metrics"><div><span>Gol attesi</span><strong>${metric(projection.expectedGoals)}</strong></div><div><span>Tiri</span>${interval(projection.shotsTotal)}</div><div><span>SOT</span>${interval(projection.shotsOnTarget)}</div><div><span>Corner</span>${interval(projection.corners)}</div></div>${attackChannels}</article>`};
  const projections=Array.isArray(prediction?.teamProjections)?prediction.teamProjections:[];
  const numbers=`<section class="section prediction-v2-numbers" aria-labelledby="prediction-v2-numbers-title"><header class="section-heading"><div><p class="eyebrow">Previsione centrale</p><h2 id="prediction-v2-numbers-title">La partita in numeri</h2></div><p>Valore centrale e intervallo storico/model-based p20–p80. La barra colloca il valore nel range, senza rappresentare una distribuzione continua.</p></header>${projections.length?`<div class="prediction-v2-team-grid">${projections.map(projectionCard).join("")}</div>`:'<p class="prediction-v2-empty">Proiezioni squadra N/D</p>'}</section>`;

  const directionFor=evidence=>evidence?.status!=="active"?{className:"unknown",symbol:"?",label:"Segnale non sufficiente"}:evidence.level==="elevated"?{className:"favourable",symbol:"↑",label:"favorevole"}:evidence.level==="suppressed"?{className:"unfavourable",symbol:"↓",label:"sfavorevole"}:{className:"neutral",symbol:"→",label:"neutro"};
  const reasonFor=(metricName,evidence,direction)=>direction.className==="unknown"?"L'evidenza disponibile non basta per descrivere il matchup.":direction.className==="favourable"?`Il profilo avversario mostra un segnale elevato specifico per ${metricName}.`:direction.className==="unfavourable"?`Il profilo avversario mostra una soppressione specifica per ${metricName}.`:`Il segnale avversario specifico per ${metricName} resta nella norma.`;
  const matchupCard=projection=>{const team=teamFor(projection.teamId),interaction=projection.opponentMatchupInteraction||{},evidence=interaction.metricEvidence||{},own=projection.ownOffensiveInteraction||{};const rows=[["Volume tiri","il volume tiri",evidence.shots,interaction.signalStability?.shots],["Tiri nello specchio","i tiri nello specchio",evidence.shotsOnTarget,interaction.signalStability?.shotsOnTarget]];const ownText=isFiniteNumber(own.shotsAdjustmentPct)&&own.shotsAdjustmentPct>0?"La produzione offensiva corrente sostiene il volume centrale.":"Spinta offensiva aggiuntiva non disponibile.";return `<article class="prediction-v2-matchup-card">${teamLogo(team)}<p class="prediction-v2-own-signal">${esc(ownText)}</p><div>${rows.map(([label,name,item,stability])=>{const direction=directionFor(item);return `<section><span>${label}</span><strong class="signal-${direction.className}">${direction.symbol} ${direction.label}</strong><p>${esc(reasonFor(name,item,direction))}</p><small>${signalQuality(stability)} · stabilità del segnale, non confidenza del pronostico</small></section>`}).join("")}</div></article>`};
  const why=`<section class="section prediction-v2-why" aria-labelledby="prediction-v2-why-title"><header class="section-heading"><div><p class="eyebrow">Matchup V2</p><h2 id="prediction-v2-why-title">Perché il modello vede la partita così</h2></div><p>Tiri e SOT restano segnali distinti. Gli stati descrivono l'effetto del matchup sulla metrica, non un giudizio generale sulla squadra.</p></header>${projections.length?`<div class="prediction-v2-matchup-grid">${projections.map(matchupCard).join("")}</div>`:'<p class="prediction-v2-empty">Segnale non sufficiente</p>'}</section>`;

  const shooters=prediction?.shooters;
  const ranked=[...(shooters?.totalShots||[]),...(shooters?.shotsOnTarget||[])],seen=new Set(),players=ranked.map(item=>(shooters?.allPlayers||[]).find(player=>playerKey(player)===playerKey(item))||item).filter(item=>{const key=playerKey(item);if(seen.has(key))return false;seen.add(key);return true});
  const playerMeta=player=>`${esc(player.team||teamFor(player.teamId).name)} · ${esc(player.role||"Ruolo N/D")}${player.detailedRole?` · ${esc(player.detailedRole)}`:""}`;
  const expectedMinutes=player=>isFiniteNumber(player.expectedMinutes)?`${Math.round(player.expectedMinutes)}' attesi`:"Minuti attesi N/D";
  const tier=player=>tierLabel(player.allocationClass)?`<span class="prediction-v2-tier">Tiri: ${tierLabel(player.allocationClass)}</span>`:"";
  const substitution=player=>riskLabel(player.substitutionRisk)?`<small>Rischio sostituzione: ${riskLabel(player.substitutionRisk)}</small>`:"";
  const tableRows=players.map(player=>`<tr><th scope="row"><strong>${esc(player.name||"N/D")}</strong><small>${playerMeta(player)}</small>${tier(player)}</th><td>${expectedMinutes(player)}</td><td class="is-key">${metric(player.projectedShots,2)}</td><td class="is-key">${probability(player.shotProbabilities?.over15)}</td><td>${probability(player.shotProbabilities?.over25)}</td><td class="is-key">${metric(player.projectedShotsOnTarget,2)}</td><td>${probability(player.shotOnTargetProbabilities?.over05)}</td><td class="is-key">${probability(player.shotOnTargetProbabilities?.over15)}</td></tr>`).join("");
  const playerCards=players.map(player=>`<article class="prediction-v2-player-card"><header><div><strong>${esc(player.name||"N/D")}</strong><small>${playerMeta(player)}</small></div>${tier(player)}</header><p>${expectedMinutes(player)}</p>${substitution(player)}<div class="prediction-v2-player-markets"><section><h3>Tiri <strong>${metric(player.projectedShots,2)}</strong></h3><dl><div><dt>1+</dt><dd>${probability(player.shotProbabilities?.over05)}</dd></div><div><dt>2+</dt><dd>${probability(player.shotProbabilities?.over15)}</dd></div><div><dt>3+</dt><dd>${probability(player.shotProbabilities?.over25)}</dd></div></dl></section><section><h3>SOT <strong>${metric(player.projectedShotsOnTarget,2)}</strong></h3><dl><div><dt>1+</dt><dd>${probability(player.shotOnTargetProbabilities?.over05)}</dd></div><div><dt>2+</dt><dd>${probability(player.shotOnTargetProbabilities?.over15)}</dd></div></dl></section></div></article>`).join("");
  const shooterPanel=`<section class="section serie-a-shooters prediction-v2-shooters" aria-labelledby="serie-a-shooters-title"><header class="section-heading"><div><p class="eyebrow">Prediction Engine V2</p><h2 id="serie-a-shooters-title">Possibili migliori tiratori</h2></div><p>Proiezioni e probabilità del modello; non sono quote né raccomandazioni.</p></header>${players.length?`<div class="prediction-v2-shooter-table"><table><thead><tr><th>Giocatore</th><th>Min</th><th>Tiri</th><th>2+</th><th>3+</th><th>SOT</th><th>1+ SOT</th><th>2+ SOT</th></tr></thead><tbody>${tableRows}</tbody></table></div><div class="prediction-v2-player-cards">${playerCards}</div>`:'<p class="prediction-v2-empty">Proiezioni individuali N/D</p>'}<p class="objective-method">Le soglie sono lette dall'output V2; il frontend non ricalcola Poisson, minuti, matchup o allocazione.</p></section>`;

  const outsiderGroup=(kind,label,items,available)=>{if(!available)return `<article><h3>${label}</h3><p class="prediction-v2-empty">Classificazione outsider N/D</p></article>`;const qualified=(items||[]).filter(player=>kind==="shots"?player.qualifiedOutsider===true:player.qualifiedSotOutsider===true);if(!qualified.length)return `<article><h3>${label}</h3><div class="prediction-v2-zero"><strong>Nessun outsider qualificato</strong><p>Nessun giocatore supera contemporaneamente i criteri minimi di volume, minuti ed evidenza del modello.</p></div></article>`;return `<article><h3>${label}</h3><div class="prediction-v2-outsider-list">${qualified.map(player=>{const confidence=kind==="shots"?player.outsiderConfidence:player.sotOutsiderConfidence;return `<section><header><div><strong>${esc(player.name||"N/D")}</strong><small>${playerMeta(player)}</small></div><span>${confidence?`Evidenza ${esc(confidenceLabel(confidence))}`:"Evidenza N/D"}</span></header><dl><div><dt>${kind==="shots"?"Tiri previsti":"SOT previsti"}</dt><dd>${metric(kind==="shots"?player.projectedShots:player.projectedShotsOnTarget,2)}</dd></div><div><dt>${kind==="shots"?"2+ tiri":"1+ SOT"}</dt><dd>${probability(kind==="shots"?player.shotProbabilities?.over15:player.shotOnTargetProbabilities?.over05)}</dd></div>${kind==="sot"?`<div><dt>2+ SOT</dt><dd>${probability(player.shotOnTargetProbabilities?.over15)}</dd></div>`:""}<div><dt>Minuti</dt><dd>${expectedMinutes(player)}</dd></div></dl><p>${esc(player.playerBaselineStability?.evidence?.[0]||"Evidenza individuale qualificata dal modello.")}</p></section>`}).join("")}</div></article>`};
  const hasShots=!!shooters&&Object.prototype.hasOwnProperty.call(shooters,"outsiders"),hasSot=!!shooters&&Object.prototype.hasOwnProperty.call(shooters,"sotOutsiders");
  const outsiderPanel=`<section class="section prediction-v2-outsiders" aria-labelledby="prediction-v2-outsiders-title"><header class="section-heading"><div><p class="eyebrow">Classificazione statistica</p><h2 id="prediction-v2-outsiders-title">Outsider del modello</h2></div><p>Zero outsider e un risultato valido: la pagina visualizza soltanto le qualificazioni prodotte dal detector V2.</p></header><div class="prediction-v2-outsider-grid">${outsiderGroup("shots","Outsider tiri",shooters?.outsiders,hasShots)}${outsiderGroup("sot","Outsider SOT",shooters?.sotOutsiders,hasSot)}</div></section>`;

  const disciplineTeam=projection=>`<article>${teamLogo(teamFor(projection.teamId))}<dl><div><dt>Falli previsti</dt><dd>${interval(projection.fouls)}</dd></div><div><dt>Gialli · baseline storica</dt><dd>${interval(projection.cards)}</dd></div></dl></article>`;
  const booked=Array.isArray(prediction?.likelyBooked)?prediction.likelyBooked:[];
  const bookingRows=booked.map(candidate=>{const duel=candidate.directOpponent?`Duello diretto con ${esc(candidate.directOpponent)}`:"Duello diretto N/D",refereeMissing=candidate.refereeFactorSource==="NO_DESIGNATION_AVAILABLE"||candidate.refereeEvidence?.some(item=>/N\/D|non disponibile/i.test(item)),referee=candidate.refereeFactorSource==="NO_DESIGNATION_AVAILABLE"?"Arbitro non designato: fallback 1":refereeMissing?"Influenza arbitrale N/D":isFiniteNumber(candidate.refereeFactor)&&candidate.refereeFactor>1?"Arbitro sopra la baseline disciplinare":isFiniteNumber(candidate.refereeFactor)?"Influenza arbitrale neutra":"Influenza arbitrale N/D";return `<li class="${candidate.possibleFirstBooked?"possible-first-booked":""}"><span>${candidate.rank??"—"}</span><div><strong>${esc(candidate.name||"N/D")}</strong><small>${esc(teamFor(candidate.teamId).name)} · ${esc(candidate.role||"Ruolo N/D")}${candidate.possibleFirstBooked?" · possibile primo ammonito (euristica)":""}</small><em>${duel} · ${referee}</em></div><b>${isFiniteNumber(candidate.riskScore)?`${metric(candidate.riskScore,0)}/100`:"N/D"}</b></li>`}).join("");
  const discipline=`<section class="section prediction-v2-discipline" aria-labelledby="prediction-v2-discipline-title"><header class="section-heading"><div><p class="eyebrow">Falli, cartellini e duelli</p><h2 id="prediction-v2-discipline-title">Disciplina e ammoniti</h2></div><p>Il rischio individuale resta separato dal pronostico generale.</p></header>${projections.length?`<div class="prediction-v2-discipline-teams">${projections.map(disciplineTeam).join("")}</div>`:""}<section class="prediction-booked-panel"><header><div><p class="eyebrow">Gerarchia disciplinare</p><h3>Probabili ammoniti</h3></div><p>Risk score comparativo, non probabilità di ammonizione. Primo nome: euristica del ranking, senza probabilità del primo cartellino.</p></header>${booked.length?`<ol>${bookingRows}</ol>`:'<p class="prediction-v2-empty">Candidati ammonizione N/D</p>'}</section></section>`;
  return {numbers,why,shooters:shooterPanel,outsiders:outsiderPanel,discipline};
}

export function createPage(deps){
  const {esc,contrastInk,dateOnly,scheduleLabel,scheduleChronology,teamLogo,empty,hero,competitionLabel,load,loadGenerated,loadObjectiveProfiles,loadTeamDirectory}=deps;
const readingModules=[
  ["context","01","Contesto e posta in gioco","Classifica, obiettivi stagionali, momento e peso della partita."],
  ["form","02","Forma e numeri","Rendimento recente, casa/trasferta e indicatori con campione dichiarato."],
  ["availability","03","Disponibilita e probabili scelte","Assenze, rientri, rotazioni e formazioni soltanto se verificati."],
  ["tactics","04","Chiavi tattiche","Strutture, duelli, spazi e possibili adattamenti delle due squadre."],
  ["referee","05","Arbitro e disciplina","Designazione, profilo disciplinare e compatibilita con il tipo di gara."],
  ["market","06","Mercato e quote","Movimenti delle quote e mercati utili, sempre con orario e fonte."],
  ["synthesis","07","Sintesi e scenari","Segnali favorevoli, contrari e condizioni che possono cambiare la lettura."]
];
const readingField=section=>section?.content?`<div class="reading-content"><p>${esc(section.content)}</p>${section.signals?.length?`<ul>${section.signals.map(signal=>`<li>${esc(signal)}</li>`).join("")}</ul>`:""}</div>`:`<div class="reading-missing"><strong>N/D</strong><span>Sezione da compilare con dati verificati.</span></div>`;
function readingFixtureLink(match,teams,reading,prediction,history){
  const home=teams.find(team=>team.id===match.homeTeam),away=teams.find(team=>team.id===match.awayTeam);
  const finished=match.status==="finished"&&match.score;
  const likelyScore=prediction?.scoreForecast?.primary?.score||prediction?.exactScores?.[0]?.score;
  const [homeColor1="#174fa5",homeColor2="#081d48"]=home.colors||[],[awayColor1="#174fa5",awayColor2="#081d48"]=away.colors||[];
  const teamColorStyle=`--home-color-1:${homeColor1};--home-color-2:${homeColor2};--away-color-1:${awayColor1};--away-color-2:${awayColor2}`;
  const preview=finished?`<span class="reading-fixture-preview" aria-label="Dati della partita"><span><small>Pronostico esatto</small><strong>${esc(likelyScore||"N/D")}</strong></span><span><small>Intervallo</small><strong>${match.halfTimeScore?`${match.halfTimeScore.home} - ${match.halfTimeScore.away}`:"N/D"}</strong></span><span><small>Dati calciatori</small><strong>${(match.playerStats?.home?.length||0)+(match.playerStats?.away?.length||0)}</strong></span></span>`:prediction?`<span class="reading-fixture-preview" aria-label="Anteprima della lettura"><span><small>Verdetto</small><strong>${esc(prediction.verdict.label)}</strong></span><span><small>Risultato esatto</small><strong>${esc(likelyScore||"N/D")}</strong></span><span><small>Confidenza</small><strong>${prediction.confidence.value}/100</strong></span></span>`:reading?.summary?`<span class="reading-fixture-preview reading-fixture-preview-text"><span><small>Anteprima</small><strong>${esc(reading.summary)}</strong></span></span>`:"";
  const roundLabel=match.competition==="coppa-italia"?"Coppa Italia · Sedicesimi":`Giornata ${match.matchday}`;
  return `<a class="reading-fixture match fixture-card fixture-card-link${finished?" is-finished":""}" href="lettura.html?match=${esc(match.id)}" aria-label="Apri la lettura di ${esc(home.name)} - ${esc(away.name)}" style="${teamColorStyle}"><header class="match-head"><div class="match-badges"><span class="matchday-chip">${roundLabel}</span>${finished?'<span class="status finished">Conclusa</span>':""}</div><span class="match-date">${scheduleLabel(match)}</span></header><span class="reading-fixture-teams">${teamLogo(home)}<b class="${finished?"reading-final-score":""}">${finished?`${match.score.home} - ${match.score.away}`:"VS"}</b>${teamLogo(away)}</span>${preview}</a>`;
}
function readingIndex(readings,matches,teams,predictions=[],headToHeadData){
  const chronological=(left,right)=>scheduleChronology(left,right)||left.id.localeCompare(right.id);
  const scheduled=matches.filter(match=>match.competition==="serie-a"&&match.status!=="finished");
  const completed=matches.filter(match=>match.competition==="serie-a"&&match.status==="finished").sort(chronological);
  const nextDay=[...new Set(scheduled.map(match=>match.matchday))].sort((left,right)=>left-right)[0],nextMatches=scheduled.filter(match=>match.matchday===nextDay).sort(chronological),byMatch=new Map(readings.map(reading=>[reading.matchId,reading])),predictionByMatch=new Map(predictions.map(prediction=>[prediction.matchId,prediction])),historyByMatch=new Map((headToHeadData?.fixtures||[]).map(fixture=>[fixture.fixtureId,fixture]));
  const firstLeg=scheduled.filter(match=>match.matchday<=19&&match.matchday!==nextDay),matchdays=[...new Set(firstLeg.map(match=>match.matchday))].sort((left,right)=>left-right);
  const directory=matchdays.map(matchday=>`<details class="reading-h2h-matchday"${matchday===nextDay?" open":""}><summary><span>Giornata ${matchday}</span><small>10 partite · storico H2H collegato</small></summary><div class="reading-fixture-grid">${firstLeg.filter(match=>match.matchday===matchday).sort(chronological).map(match=>readingFixtureLink(match,teams,byMatch.get(match.id),predictionByMatch.get(match.id),historyByMatch.get(match.id))).join("")}</div></details>`).join("");
  return hero("Analisi e tabellini","Letture","Prima della gara trovi probabilità e scenari; dopo il fischio finale, risultato, eventi e statistiche reali di squadre e calciatori.")+`${completed.length?`<section class="section reading-completed-section"><header class="section-heading"><div><p class="eyebrow">Partite concluse</p><h2>Archivio tabellini</h2></div><p>Apri il menu della giornata per marcatori, ammoniti, sostituzioni e dati dei calciatori.</p></header><details class="reading-completed-matchday"><summary><span>Tabellini delle partite precedenti</span><small>${completed.length} partite concluse</small></summary><div class="reading-fixture-grid">${completed.map(match=>readingFixtureLink(match,teams,byMatch.get(match.id),predictionByMatch.get(match.id),historyByMatch.get(match.id))).join("")}</div></details></section>`:""}<section class="section"><header class="section-heading"><div><p class="eyebrow">Prossimo turno</p><h2>Giornata ${nextDay||"N/D"}</h2></div><p>Pronostico tecnico senza quote Sisal; le formazioni ufficiali della prima giornata sono usate come riferimento, non come conferma.</p></header>${nextMatches.length?`<div class="reading-fixture-grid">${nextMatches.map(match=>readingFixtureLink(match,teams,byMatch.get(match.id),predictionByMatch.get(match.id),historyByMatch.get(match.id))).join("")}</div>`:empty("Nessuna partita programmata.")}</section><section class="section reading-h2h-directory"><header class="section-heading"><div><p class="eyebrow">Girone d'andata completo</p><h2>Precedenti per tutte le 190 partite</h2></div><p>Apri una giornata e poi la singola lettura per marcatori e ammoniti degli ultimi cinque confronti disponibili.</p></header><div class="reading-h2h-matchdays">${directory}</div></section>`;
}
function readingDetail(match,reading,teams){
  const home=teams.find(team=>team.id===match.homeTeam),away=teams.find(team=>team.id===match.awayTeam),sections=reading?.sections||{},completed=readingModules.filter(([key])=>sections[key]?.content).length;
  const title=reading?.title||`${home.name} - ${away.name}`;
  const isCup=match.competition==="coppa-italia",competition=isCup?"Coppa Italia · Sedicesimi":`Serie A · Giornata ${match.matchday}`,fixtureLabel=isCup?"Sedicesimi":`Giornata ${match.matchday}`,fixtureNav=isCup?`<a href="coppa-italia.html#coppa-round-16">${fixtureLabel}</a>`:`<span>${fixtureLabel}</span>`;
  return `<nav class="reading-back"><a href="lettura.html">← Tutte le letture</a>${fixtureNav}</nav><section class="reading-match-hero"><div><p class="eyebrow">${competition}</p><h1>${esc(title)}</h1><p>${scheduleLabel(match)}</p><span class="reading-progress">${completed}/7 sezioni compilate</span></div><div class="reading-matchup">${teamLogo(home)}<b>VS</b>${teamLogo(away)}</div></section>${reading?.summary?`<aside class="reading-summary"><span>Sintesi editoriale</span><p>${esc(reading.summary)}</p></aside>`:""}<section class="section reading-detail"><header class="section-heading"><div><p class="eyebrow">Scheda di lavoro</p><h2>Struttura della lettura</h2></div><p>I campi non ancora verificati restano N/D.</p></header><div class="reading-module-grid">${readingModules.map(([key,number,moduleTitle,description])=>`<article class="reading-module" id="lettura-${key}"><header><span>${number}</span><div><h3>${moduleTitle}</h3><p>${description}</p></div></header>${readingField(sections[key])}${sections[key]?.sources?.length?`<footer>${sections[key].sources.map(source=>`<a href="${esc(source.url)}" target="_blank" rel="noreferrer">${esc(source.label||"Fonte")}</a>`).join(" · ")}</footer>`:""}</article>`).join("")}</div></section>`;
}
function headToHeadPanel(history,prediction){
  if(!history)return `<section class="section reading-h2h-section"><aside class="data-warning"><strong>Precedenti N/D</strong><p>Nessun dataset storico collegato a questa partita.</p></aside></section>`;
  const meetings=history.previousMeetings||[],available=history.coverage?.available??meetings.length;
  const eventList=(items,emptyLabel)=>items?.length?`<ul>${items.map(item=>`<li><strong>${esc(item.player)}</strong><small>${esc(item.team)} · ${esc(item.minute||"minuto N/D")}${item.ownGoal?" · autogol":""}</small></li>`).join("")}</ul>`:`<p class="reading-h2h-empty">${emptyLabel}</p>`;
  const cards=meeting=>{const gap=meeting.coverage?.missingFields?.includes("bookingEvents");if(!meeting.bookings?.length)return `<p class="reading-h2h-empty">${gap?"Dettaglio ammoniti N/D":"Nessun ammonito registrato"}</p>`;return `${eventList(meeting.bookings,"Nessun ammonito registrato")}${gap?'<small class="reading-h2h-warning">Conteggio ESPN non riconciliato: sono mostrati soltanto gli eventi nominativi disponibili.</small>':""}`};
  const goals=meeting=>{const gap=meeting.coverage?.missingFields?.includes("goalEvents");if(!meeting.goals?.length)return `<p class="reading-h2h-empty">${gap?"Dettaglio marcatori N/D":"Nessun gol"}</p>`;return eventList(meeting.goals,"Nessun gol")};
  const rows=meetings.map((meeting,index)=>`<details class="reading-h2h-match"${index===0?" open":""}><summary><span>${dateOnly(meeting.date)} · ${esc(meeting.competition)}</span><strong>${esc(meeting.homeTeam.name)} ${meeting.score.home}-${meeting.score.away} ${esc(meeting.awayTeam.name)}</strong></summary><div class="reading-h2h-events"><section><h3>Marcatori</h3>${goals(meeting)}</section><section><h3>Ammoniti</h3>${cards(meeting)}</section></div><a href="${esc(meeting.source.url)}" target="_blank" rel="noreferrer">Fonte ESPN</a></details>`).join("");
  const model=prediction?.headToHead?.usedInModel?`<aside class="reading-h2h-model"><strong>Uso nel modello</strong><p>Correttivo leggero e limitato sui gol attesi; non sostituisce forma, rendimento corrente, formazioni o matchup tattico.</p></aside>`:"";
  return `<section class="section reading-h2h-section"><header class="section-heading"><div><p class="eyebrow">Storico ufficiale · ESPN</p><h2>Ultimi ${available} scontri diretti disponibili</h2></div><p>${available}/5 precedenti · Serie A, Serie B e Coppa Italia</p></header>${available<5?`<aside class="data-warning"><strong>Campione storico limitato</strong><p>Il provider espone ${available} confronti per questa coppia; quelli mancanti non vengono ricostruiti.</p></aside>`:""}<div class="reading-h2h-list">${rows}</div>${model}</section>`;
}
const sampleLabel=matches=>matches<5?"Campione insufficiente":matches<10?"Indicazione moderata":"Confronto più significativo";
const actualValue=value=>value===null||value===undefined?"N/D":esc(String(value));
function readingPostMatchReport(match,home,away){
  if(match.status!=="finished"||!match.score)return"";
  const teamFor=id=>id===home.id?home:away;
  const eventList=(items,renderer,emptyLabel)=>items?.length?`<ol>${items.map(renderer).join("")}</ol>`:`<p class="reading-post-match-empty">${emptyLabel}</p>`;
  const scorers=eventList(match.scorers,item=>`<li><span>${item.minute}'</span><div><strong>${esc(item.player)}</strong><small>${esc(teamFor(item.team).name)}${item.ownGoal?" · autogol":""}${item.assist?` · assist ${esc(item.assist)}`:""}</small></div></li>`,"Nessun gol");
  const bookings=eventList(match.bookings,item=>{const type=cardType(item.eventType||item.card),red=type==="redCard"||type==="yellowRedCard";return `<li><span class="reading-booking-card${red?" is-red":type==="unknown"?" is-unknown":""}" aria-label="${type==="unknown"?"Cartellino tipo N/D":red?"Cartellino rosso":"Cartellino giallo"}"></span><div><strong>${esc(item.player)}</strong><small>${item.minute==null?"Minuto N/D":`${esc(item.minute)}'`} · ${esc(teamFor(item.team).name)}${type==="yellowRedCard"?" · espulsione per secondo giallo":type==="redCard"?" · rosso diretto":type==="unknown"?" · tipo N/D":""}</small></div></li>`},match.resultCoverage?.bookings==="unavailable"?"Cartellini N/D":"Nessun cartellino");
  const substitutions=eventList(match.substitutions,item=>`<li><span>${item.minute}'</span><div><strong>${esc(item.playerIn)} <small>entra</small></strong><small>${esc(teamFor(item.team).name)} · esce ${esc(item.playerOut)}</small></div></li>`,match.resultCoverage?.substitutions==="unavailable"?"Sostituzioni N/D":"Nessuna sostituzione registrata");
  const statRows=[
    ["Possesso", "possessionPct", "%"],["xG", "expectedGoals", ""],["Tiri totali", "shots", ""],["Tiri in porta", "shotsOnTarget", ""],["Corner", "corners", ""],["Passaggi riusciti", "passesCompleted", ""],["Precisione passaggi", "passAccuracyPct", "%"],["Falli commessi", "fouls", ""],["Falli subiti", "fouls", "", true],["Ammonizioni", "yellowCards", ""],["Duelli vinti", "duelsWon", ""],["Parate", "goalkeeperSaves", ""]
  ];
  const statValue=(side,key,suffix)=>match.teamStats?.[side]?.[key]===null||match.teamStats?.[side]?.[key]===undefined?"N/D":`${actualValue(match.teamStats[side][key])}${suffix}`;
  const comparison=statRows.map(([label,key,suffix,fromOpponent=false])=>`<tr><td>${statValue(fromOpponent?"away":"home",key,suffix)}</td><th scope="row">${label}</th><td>${statValue(fromOpponent?"home":"away",key,suffix)}</td></tr>`).join("");
  const playerTable=(team,players=[])=>match.resultCoverage?.playerStats==="unavailable"?`<article class="reading-player-team"><h3>${esc(team.name)}</h3><p class="reading-post-match-empty">Statistiche individuali N/D</p></article>`:`<article class="reading-player-team"><header>${teamLogo(team,{showName:false})}<div><h3>${esc(team.name)}</h3><small>${players.length} calciatori impiegati</small></div></header><div class="reading-player-table-scroll"><table class="reading-player-table"><thead><tr><th>Calciatore</th><th>Impiego</th><th>Min</th><th>Voto</th><th>G</th><th>A</th><th>Tiri in porta</th><th>xG</th></tr></thead><tbody>${players.map(player=>`<tr><td><strong>${esc(player.player)}</strong></td><td>${player.starter?"Titolare":"Subentrato"}</td><td>${actualValue(player.minutes)}</td><td>${actualValue(player.rating)}</td><td>${actualValue(player.goals)}</td><td>${actualValue(player.assists)}</td><td>${actualValue(player.shotsOnTarget)}</td><td>${actualValue(player.expectedGoals)}</td></tr>`).join("")}</tbody></table></div></article>`;
  const sourceUrl=match.resultSource?.url||match.sources?.find(source=>source.sourceType==="match-report-stats")?.sourceUrl;
  const officialMvp=match.mvp?`<aside class="reading-official-mvp"><span>Panini Player of the Match</span><strong>${esc(match.mvp.player)}</strong><small>${esc(teamFor(match.mvp.team).name)} · MVP ufficiale</small><a href="${esc(match.mvp.sourceUrl)}" target="_blank" rel="noreferrer">Fonte Lega Serie A</a></aside>`:"";
  return `<section class="section reading-post-match" id="tabellino"><header class="section-heading"><div><p class="eyebrow">Dati reali · partita conclusa</p><h2>Tabellino e statistiche</h2></div><p>Intervallo ${match.halfTimeScore?`${match.halfTimeScore.home} - ${match.halfTimeScore.away}`:"N/D"} · moduli ${actualValue(match.formations?.home)} / ${actualValue(match.formations?.away)}</p></header>${officialMvp}<div class="reading-match-events-grid"><article><h3>Marcatori</h3>${scorers}</article><article><h3>Cartellini</h3>${bookings}</article><article><h3>Sostituzioni</h3>${substitutions}</article></div><div class="reading-team-comparison"><table><thead><tr><th>${esc(home.name)}</th><th>Statistiche squadra</th><th>${esc(away.name)}</th></tr></thead><tbody>${comparison}</tbody></table></div><div class="reading-player-stats-grid">${playerTable(home,match.playerStats?.home)}${playerTable(away,match.playerStats?.away)}</div>${sourceUrl?`<a class="reading-post-match-source" href="${esc(sourceUrl)}" target="_blank" rel="noreferrer">Fonte tabellino · ${esc(match.resultSource?.provider||"StatMuse")}</a>`:""}</section>`;
}
function readingPrototypeDetail(match,reading,teams,teamDirectory,objectiveProfiles,prediction,history,refereeProfiles){
  const home=teams.find(team=>team.id===match.homeTeam),away=teams.find(team=>team.id===match.awayTeam);
  const directoryTeams=teamDirectory?.teams||[],homeMeta=directoryTeams.find(team=>team.id===home.id)||{},awayMeta=directoryTeams.find(team=>team.id===away.id)||{};
  const isCup=match.competition==="coppa-italia",competition=isCup?"Coppa Italia · Sedicesimi":`Serie A · Giornata ${match.matchday}`,fixtureLabel=isCup?"Sedicesimi":`Giornata ${match.matchday}`,fixtureNav=isCup?`<a href="coppa-italia.html#coppa-round-16">${fixtureLabel}</a>`:`<span>${fixtureLabel}</span>`;
  const unavailable=(label,note)=>`<div class="reading-unavailable"><span>${label}</span><strong>N/D</strong><small>${note}</small></div>`;
  const duplicatePanels=new Set(["Campo","Dati disponibili"]);
  const dataPanel=(label,body,className="")=>duplicatePanels.has(label)?"":`<section class="reading-data-panel ${className}"><span>${label}</span>${body}</section>`;
  const finished=match.status==="finished"&&match.score,formation=formationPresentation(match,teamDirectory);
  const scoreForecasts=prediction?.scoreForecast?.display||prediction?.exactScores?.slice(0,3)||[];
  const scoreCards=scoreForecasts.length===3?scoreForecasts.map((item,index)=>`<div${index===0?' class="is-central"':""}><strong>${esc(item.score)}</strong><small>${index===0?"Risultato centrale":"Alternativa"}${item.probabilityPct!=null?` · ${item.probabilityPct}%`:""}</small></div>`).join(""):'<div class="is-central"><strong>N/D</strong><small>Risultato centrale</small></div><div><strong>N/D</strong><small>Alternativa</small></div><div><strong>N/D</strong><small>Alternativa</small></div>';
  const scoreCoverage=prediction?.scoreProfile?.topThreeCoveragePct;
  const surpriseValue=prediction?.surprise?.value;
  const summary=`<div class="reading-summary reading-summary-prototype reading-hero-summary reading-result-summary"><div class="reading-exact-scores"><span>Risultato esatto pronosticato</span><div class="reading-score-list">${scoreCards}</div><small class="reading-score-caveat">Centrale dai gol attesi arrotondati${scoreCoverage!=null?` · tre scenari coprono il ${scoreCoverage}%`:""}</small></div><div class="reading-hero-signal reading-hero-surprise reading-surprise-factor"><span>Fattore sorpresa</span><strong>${isFiniteNumber(surpriseValue)?`${surpriseValue}/100`:"N/D"}</strong><small>${prediction?.surprise?.level?esc(prediction.surprise.level):"Dato non disponibile"}</small>${isFiniteNumber(surpriseValue)?`<div class="reading-surprise-bar" role="progressbar" aria-label="Fattore sorpresa ${surpriseValue} su 100" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${surpriseValue}"><b style="width:${surpriseValue}%"></b></div>`:""}</div><div class="reading-hero-signal"><span>Confidenza</span><strong>${isFiniteNumber(prediction?.confidence?.value)?`${prediction.confidence.value}/100`:"N/D"}</strong><small>${prediction?.confidence?.level?esc(prediction.confidence.level):"Dato non disponibile"}</small></div><div class="reading-formation-status is-${formation.status}"><strong>${formation.label}</strong><small>${esc(formation.note)}</small></div></div>`;
  const assignment=match.refereeAssignment,refereeProfile=assignment?refereeProfiles?.profiles?.find(profile=>profile.refereeSlug===assignment.referee.slug):null;
  const refereeMetric=(label,value)=>`<article><span>${label}</span><strong>${value??"N/D"}</strong></article>`;
  const refereeStats=refereeProfile?`<div class="reading-referee-stats">${refereeMetric("Falli / gara",refereeProfile.perMatch.fouls?.toFixed(2)??"N/D")}${refereeMetric("Gialli / gara",refereeProfile.perMatch.yellowCards?.toFixed(2)??"N/D")}${refereeMetric("Rossi / gara",refereeProfile.perMatch.redCards?.toFixed(2)??"N/D")}${refereeMetric("Rigori / gara",refereeProfile.perMatch.penalties?.toFixed(2)??"N/D")}</div>`:`<div class="reading-referee-stats">${refereeMetric("Statistiche disciplinari","N/D")}</div>`;
  const officialName=value=>value?.name||value||"N/D";
  const refereePanel=assignment?`<section class="section reading-referee-assignment" id="lettura-referee"><header class="section-heading"><div><p class="eyebrow">Designazione ufficiale AIA</p><h2>Squadra arbitrale</h2></div><p>Incarichi ufficiali, separati dalle statistiche disciplinari.</p></header><div class="reading-referee-designation"><article class="is-main"><span>Arbitro</span><strong>${esc(officialName(assignment.referee))}</strong></article><article><span>Assistenti</span><strong>${esc((assignment.assistants||[]).map(officialName).join(" · ")||"N/D")}</strong></article><article><span>IV ufficiale</span><strong>${esc(officialName(assignment.fourthOfficial))}</strong></article><article><span>VAR</span><strong>${esc(officialName(assignment.var))}</strong></article><article><span>AVAR</span><strong>${esc(officialName(assignment.avar))}</strong></article></div>${refereeStats}<p class="reading-referee-method">La designazione non modifica automaticamente il pronostico.</p></section>`:`<section class="section reading-referee-assignment" id="lettura-referee"><header class="section-heading"><div><p class="eyebrow">Designazione ufficiale AIA</p><h2>N/D</h2></div><p>Arbitro non ancora disponibile.</p></header></section>`;
  const v2=renderPredictionV2Sections({prediction,teams,esc,teamLogo});
  const archiveBanner=finished?'<aside class="reading-prototype-banner reading-archive-banner"><strong>Analisi prepartita archiviata</strong><p>Le sezioni successive conservano il pronostico formulato prima della gara; il tabellino qui sopra contiene i dati reali conclusivi.</p></aside>':"";
  return `<nav class="reading-back"><a href="lettura.html">← Tutte le letture</a>${fixtureNav}</nav><section class="reading-match-hero${finished?" is-finished":""}"><div><p class="eyebrow">${competition} · ${finished?"conclusa":"prepartita"}</p><h1>${esc(home.name)} - ${esc(away.name)}</h1><p>${scheduleLabel(match)} · ${esc(homeMeta.stadium||"Stadio N/D")}</p></div><div class="reading-matchup" aria-label="${esc(home.name)} contro ${esc(away.name)}">${teamLogo(home,{showName:false})}<b>${finished?`${match.score.home} - ${match.score.away}`:"VS"}</b>${teamLogo(away,{showName:false})}</div>${summary}</section>${readingPostMatchReport(match,home,away)}${archiveBanner}${v2.numbers}${v2.why}${v2.shooters}${v2.outsiders}${v2.discipline}${refereePanel}<section class="section reading-info-grid"><article class="round16-info-box round16-formations"><span>1</span><h2>Sistemi di riferimento</h2><div class="reading-base-shape"><strong>${esc(home.name)} · ${esc(homeMeta.preferredFormation||"N/D")}</strong><p>Allenatore: ${esc(homeMeta.coach||"N/D")}</p></div><div class="reading-base-shape"><strong>${esc(away.name)} · ${esc(awayMeta.preferredFormation||"N/D")}</strong><p>Allenatore: ${esc(awayMeta.coach||"N/D")}</p></div></article></section>${headToHeadPanel(history,prediction)}`;
}
function renderProbableLineups(match,teamDirectory,prediction){
  if(!match||!teamDirectory)return;
  const meta=id=>teamDirectory.teams.find(team=>team.id===id),home=meta(match.homeTeam),away=meta(match.awayTeam);
  const fixtureLineup=team=>fixtureLineupForMatch(match,team,teamDirectory);
  const officialLineups=fixtureLineup(home)?.status==="official"&&fixtureLineup(away)?.status==="official";
  const card=team=>{const lineup=fixtureLineup(team);if(!lineup)return"";const shape=lineup.formation.split("-").map(Number),units=[1,...shape];let offset=0;const rows=units.map(size=>{const players=lineup.players.slice(offset,offset+size).reverse();offset+=size;return `<div class="reading-lineup-row" style="--reading-lineup-count:${size}">${players.map(player=>`<strong>${esc(player)}</strong>`).join("")}</div>`}).reverse().join("");const [primary="#174fa5",secondary="#081d48"]=team.colors||[],official=lineup.status==="official",reference=lineup.status==="reference",label=official?"Formazione ufficiale":reference?"Formazione di riferimento":"Probabile formazione",coachNote=lineup.coachConfirmation?` (${esc(lineup.coachConfirmation)})`:"",substitutes=official&&lineup.substitutes?.length?`<p class="reading-lineup-substitutes"><strong>A disposizione:</strong> ${lineup.substitutes.map(esc).join(", ")}</p>`:"";return `<article class="reading-lineup-card" style="--reading-lineup-primary:${esc(primary)};--reading-lineup-secondary:${esc(secondary)};--reading-lineup-head-ink:${contrastInk(secondary)}"><header><span>${esc(team.name)}</span><strong>${esc(lineup.formation)}</strong></header><div class="reading-lineup-field" aria-label="${label} ${esc(team.name)} con modulo ${esc(lineup.formation)}"><i class="reading-lineup-centre" aria-hidden="true"></i>${rows}</div><footer><span>Allenatore: ${esc(lineup.coach||team.coach||"N/D")}${coachNote}</span>${substitutes}</footer></article>`};
  const target=document.querySelector(".round16-formations");
  if(target){const homeLineup=fixtureLineup(home),awayLineup=fixtureLineup(away),referenceLineups=homeLineup?.status==="reference"&&awayLineup?.status==="reference",source=homeLineup?.source||awayLineup?.source||{},updated=homeLineup?.updatedAt||awayLineup?.updatedAt||dateOnly(source.retrievedAt)||"N/D",sourceLabel=source.url?`<a href="${esc(source.url)}" target="_blank" rel="noreferrer">Fonte ${esc(source.provider||"editoriale")}</a>`:`Fonte ${esc(source.provider||"editoriale")}`,officialContext=match.competition==="coppa-italia"?"Distinte ufficiali della gara":"Distinte ufficiali della giornata "+match.matchday,projectionContext=match.competition==="coppa-italia"?"Proiezione editoriale per la gara di Coppa, non distinta ufficiale":"Proiezione editoriale della giornata, non distinta ufficiale";target.innerHTML=`<span>1</span><h2>${officialLineups?"Formazioni ufficiali":referenceLineups?"Formazioni di riferimento":"Probabili formazioni"}</h2><div class="reading-lineup-grid">${card(home)}${card(away)}</div><small>${officialLineups?officialContext:referenceLineups?"Ultime distinte ufficiali disponibili usate come riferimento; non sono formazioni confermate":projectionContext}, aggiornate ${esc(updated)}. ${sourceLabel}</small>`;}
  const banner=document.querySelector(".reading-prototype-banner p");if(banner&&match.status==="finished")banner.textContent=`Le sezioni successive conservano l'analisi prepartita; risultato, formazioni, eventi e statistiche reali sono pubblicati nel tabellino.`;
}
function renderReadingPilotEvidence(reading,match){
  if(!reading)return;
  const available=[["form","Base storica 2025/26"]].filter(([key])=>reading.sections?.[key]?.content);
  if(!available.length)return;
  const cards=available.map(([key,title])=>{const section=reading.sections[key];return `<article class="reading-pilot-card"><header><span>${title}</span><strong>Dato disponibile</strong></header><p>${esc(section.content)}</p>${section.signals?.length?`<ul>${section.signals.map(signal=>`<li>${esc(signal)}</li>`).join("")}</ul>`:""}${section.sources?.length?`<footer>${section.sources.map(source=>`<a href="${esc(source.url)}" target="_blank" rel="noreferrer">${esc(source.label)}</a>`).join(" · ")}</footer>`:""}</article>`}).join("");
  document.querySelector(".reading-h2h-section")?.insertAdjacentHTML("beforebegin",`<section class="section reading-pilot-evidence"><header class="section-heading"><div><p class="eyebrow">Atalanta - Sassuolo · versione iniziale</p><h2>Evidenze già integrate</h2></div><p>Storico e contesto restano separati dai dati 2026/27.</p></header><div>${cards}</div></section>`);
}
function renderTacticalBaselines(match,dataset,teams){
  if(!match||!dataset?.profiles?.length)return;
  const profileFor=teamId=>dataset.profiles.find(profile=>profile.teamId===teamId),teamFor=teamId=>teams.find(team=>team.id===teamId);
  const card=teamId=>{const team=teamFor(teamId),profile=profileFor(teamId);if(!team||!profile)return"";const list=(label,items)=>`<div><strong>${label}</strong>${items?.length?`<ul>${items.slice(0,5).map(item=>`<li>${esc(item.label)}</li>`).join("")}</ul>`:'<p class="muted">N/D dal provider</p>'}</div>`;return `<article class="reading-tactical-card">${teamLogo(team)}<span class="sample-label sample-${profile.dataQuality==="complete"?"strong":"low"}">${profile.dataQuality==="complete"?"Profilo completo":profile.dataQuality==="limited-sample"?"Campione limitato":"Solo statistiche"}</span><dl><div><dt>Campione</dt><dd>${esc(profile.competition)} · ${profile.summary.appearances} gare</dd></div><div><dt>Modulo più usato</dt><dd>${esc(profile.formation.code||"N/D")}${profile.formation.appearances?` · ${profile.formation.appearances} gare`:""}</dd></div><div><dt>Possesso</dt><dd>${profile.summary.possessionPct===null?"N/D":`${profile.summary.possessionPct}%`}</dd></div><div><dt>Tiri / gara</dt><dd>${profile.summary.shotsPerGame??"N/D"}</dd></div><div><dt>Gol / gara</dt><dd>${profile.derived.goalsPerGame}</dd></div></dl><div class="reading-tactical-traits">${list("Punti di forza",profile.strengths)}${list("Vulnerabilità",profile.weaknesses)}${list("Stile",profile.playingStyle)}</div>${profile.notes?.length?`<p class="reading-tactical-note">${profile.notes.map(esc).join(" ")}</p>`:""}<a href="${esc(profile.source.url)}" target="_blank" rel="noreferrer">Fonte WhoScored</a></article>`};
  const target=document.querySelector(".reading-h2h-section");
  const currentTraits=[profileFor(match.homeTeam),profileFor(match.awayTeam)].some(profile=>profile?.characteristicsSeason==="2026-27");
  target?.insertAdjacentHTML("beforebegin",`<section class="section reading-tactical-baseline"><header class="section-heading"><div><p class="eyebrow">WhoScored · ${currentTraits?"baseline 2025/26 + tratti 2026/27":"stagione 2025/26"}</p><h2>Baseline tattica delle squadre</h2></div><p>${currentTraits?"I tratti correnti hanno ancora un campione iniziale; i numeri restano storici.":"Contesto storico, non previsione autonoma."}</p></header><div>${card(match.homeTeam)}${card(match.awayTeam)}</div><p class="objective-method">Il modello viene ricalcolato con forma 2026/27, assenze, formazioni disponibili e arbitro; le quote restano un confronto esterno.</p></section>`);
}
function refereeStatsTable(rows,competition){
  const isSerieA=competition==="serieA";
  return `<div class="table-wrap"><table class="referee-stats-table"><thead><tr><th>Arbitro</th><th>Partite</th>${isSerieA?"<th>Gialli</th>":"<th>Falli / gara</th>"}<th>Gialli / gara</th>${isSerieA?"<th>Rossi</th>":""}<th>Rossi / gara</th><th>Campione</th></tr></thead><tbody>${rows.map(row=>{const s=row[competition];return `<tr><td><strong>${esc(row.name)}</strong></td><td>${s.matches}</td>${isSerieA?`<td>${s.yellowCards}</td>`:`<td>${s.foulsPerMatch.toFixed(2)}</td>`}<td>${s.yellowCardsPerMatch.toFixed(2)}</td>${isSerieA?`<td>${s.redCards}</td>`:""}<td>${s.redCardsPerMatch.toFixed(2)}</td><td><span class="sample-label sample-${s.matches<5?'low':s.matches<10?'medium':'strong'}">${sampleLabel(s.matches)}</span></td></tr>`}).join("")}</tbody></table></div>`;
}
function refereeRankings(rows,competition){
  const eligible=rows.filter(row=>row[competition].matches>=5),top=(field,ascending=false)=>[...eligible].sort((a,b)=>(ascending?a[competition][field]-b[competition][field]:b[competition][field]-a[competition][field])||a.name.localeCompare(b.name,"it")).slice(0,5),card=(title,field,ascending=false)=>`<article class="card ranking-card"><h3>${title}</h3><ol>${top(field,ascending).map(row=>`<li><span>${esc(row.name)}</span><strong>${row[competition][field].toFixed(2)}</strong></li>`).join("")}</ol></article>`;return `<div class="ranking-grid">${card("Più gialli / gara","yellowCardsPerMatch")}${card("Meno gialli / gara","yellowCardsPerMatch",true)}${competition==="serieA"?card("Più espulsioni / gara","redCardsPerMatch"):card("Più falli / gara","foulsPerMatch")}</div>`;
}
function pilotRefereeTable(rows){return `<div class="table-wrap"><table class="pilot-referee-table"><thead><tr><th>Competizione</th><th>Arbitro</th><th>Partite</th><th>Falli / gara</th><th>Gialli / gara</th><th>2° gialli</th><th>Rossi diretti</th><th>Rigori / gara</th><th>Attendibilità</th><th>Fonte</th></tr></thead><tbody>${[...rows].sort((a,b)=>a.competition.localeCompare(b.competition)||a.referee.localeCompare(b.referee,"it")).map(row=>`<tr><td><span class="competition-chip">${competitionLabel(row.competition)}</span></td><td><strong>${esc(row.referee)}</strong></td><td>${row.matches}</td><td>${row.foulsPerMatch?.toFixed(2)??"—"}</td><td>${row.yellowCardsPerMatch?.toFixed(2)??"—"}</td><td>${row.secondYellowCards}</td><td>${row.straightRedCards}</td><td>${row.penaltiesPerMatch?.toFixed(2)??"—"}</td><td><span class="sample-label sample-low">${esc(row.reliability)}</span></td><td>${row.fixtureIds.map(id=>`<a class="source-id" href="https://www.espn.com/soccer/match/_/gameId/${esc(id)}" target="_blank" rel="noreferrer">${esc(id)}</a>`).join(" ")}</td></tr>`).join("")}</tbody></table></div>`}
function pilotTeamTable(rows){return `<div class="table-wrap"><table class="pilot-team-table"><thead><tr><th>Competizione</th><th>Arbitro</th><th>Squadra</th><th>Partite</th><th>Falli / gara</th><th>Gialli / gara</th><th>Media altri arbitri</th><th>Confronto</th></tr></thead><tbody>${[...rows].sort((a,b)=>a.competition.localeCompare(b.competition)||a.referee.localeCompare(b.referee,"it")||a.teamName.localeCompare(b.teamName,"it")).map(row=>`<tr><td>${competitionLabel(row.competition)}</td><td><strong>${esc(row.referee)}</strong></td><td>${esc(row.teamName)}</td><td>${row.matches}</td><td>${row.foulsPerMatch?.toFixed(2)??"—"}</td><td>${row.yellowCardsPerMatch?.toFixed(2)??"—"}</td><td>${row.comparison.teamAverageWithOtherReferees?.toFixed(2)??"—"}</td><td><span class="sample-label sample-${row.reliability==="campione insufficiente"?'low':'medium'}">${esc(row.comparison.severity)}</span></td></tr>`).join("")}</tbody></table></div>`}
function pilotSection(aggregates,report){const serieA=report.competitions.find(item=>item.competition==="serie-a"),serieB=report.competitions.find(item=>item.competition==="serie-b"),missing=Object.entries(report.missingFields);return `<section class="section referee-section pilot-section" id="pilot-espn"><p class="eyebrow">Importatore automatico · ESPN</p><h2>Pilot statistiche arbitrali</h2><p class="lead-small">Primo controllo su 10 partite di Serie A e 10 di Serie B 2025/26. I risultati sportivi non sono usati per formulare giudizi di favoritismo.</p><div class="pilot-summary"><article><span>Serie A importate</span><strong>${serieA?.imported??0}/${serieA?.requested??0}</strong></article><article><span>Serie B importate</span><strong>${serieB?.imported??0}/${serieB?.requested??0}</strong></article><article><span>Arbitri analizzati</span><strong>${aggregates.referees.length}</strong></article><article class="${missing.length?'pilot-warning':''}"><span>Campi mancanti</span><strong>${missing.reduce((sum,[,count])=>sum+count,0)}</strong></article></div>${missing.length?`<aside class="pilot-missing"><strong>Copertura del provider</strong><p>${missing.map(([field,count])=>`${esc(field)}: assente in ${count} partite`).join(" · ")}. Gli altri campi richiesti risultano disponibili nel pilot.</p></aside>`:""}<h3 class="pilot-subtitle">Statistiche per arbitro</h3>${pilotRefereeTable(aggregates.referees)}<h3 class="pilot-subtitle">Confronto arbitro-squadra</h3><p class="muted">Con una sola gara per coppia, il confronto resta correttamente classificato come campione insufficiente.</p>${pilotTeamTable(aggregates.refereeTeams)}<p class="referee-note">Dati recuperati ${new Date(report.retrievedAt).toLocaleString("it-IT")} · Provider ESPN · Fixture e fonti consultabili nella tabella.</p></section>`}

  async function render(){
    const page="readings",requestedMatchId=new URLSearchParams(location.search).get("match");
    const [teams,matches,readings,objectiveProfiles,teamDirectory,teamStyleProfiles,predictionDataset,headToHeadData,refereeProfiles]=await Promise.all([load("teams.json"),load("matches.json"),load("readings.json"),loadObjectiveProfiles(),loadTeamDirectory(),load("team-style-profiles.json"),load("predictions.json"),loadGenerated(`head-to-head/${requestedMatchId?"first-leg-2026-27.json":"first-leg-2026-27-summary.json"}`),requestedMatchId?loadGenerated("reading-referee-profiles-2025-26.json"):Promise.resolve(null)]);
    const league=matches.filter(m=>m.competition==="serie-a");
    const allTeams=teams;
    let html="",activeReading=null,activeReadingMatch=null,activePrediction=null;
  if(page==="readings")html=hero("Analisi prepartita","Lettura","Forma, assenze, tattica, arbitro e mercato: ogni segnale viene presentato come contesto, mai come certezza.")+`<section class="section">${readings.length?`<div class="grid">${readings.map(r=>`<article class="card"><h3>${esc(r.title)}</h3><p>${esc(r.summary)}</p></article>`).join("")}</div>`:`<div class="editorial-empty"><span class="editorial-empty-mark">L</span><div><p class="eyebrow">Prossimamente</p><h2>La prima lettura è in preparazione</h2><p>Le analisi appariranno qui quando saranno disponibili formazioni, quote e informazioni verificabili. Nessun dato verrà completato per supposizione.</p><a class="button button-primary" href="statistiche-squadre.html">Consulta le squadre</a></div><ol><li><strong>01</strong><span>Contesto e forma</span></li><li><strong>02</strong><span>Assenze e tattica</span></li><li><strong>03</strong><span>Arbitro e mercato</span></li></ol></div>`}</section>`;
  if(page==="readings"){
    const matchId=new URLSearchParams(location.search).get("match"),selectedMatch=league.find(match=>match.id===matchId),reading=readings.find(item=>item.matchId===matchId),prediction=predictionDataset?.predictions?.find(item=>item.matchId===matchId);
    activeReading=reading;
    activeReadingMatch=selectedMatch;
    activePrediction=prediction;
    const pairKey=selectedMatch?[selectedMatch.homeTeam,selectedMatch.awayTeam].sort().join("|"):null,history=headToHeadData?.fixtures?.find(fixture=>fixture.fixtureId===matchId||[fixture.homeTeamId,fixture.awayTeamId].sort().join("|")===pairKey);
    html=selectedMatch?readingPrototypeDetail(selectedMatch,reading,allTeams,teamDirectory,objectiveProfiles,prediction,history,refereeProfiles):readingIndex(readings,league,allTeams,predictionDataset?.predictions||[],headToHeadData);
    if(matchId&&!selectedMatch)html=`<aside class="data-warning"><strong>Partita non trovata</strong><p>Il collegamento richiesto non corrisponde al calendario corrente.</p></aside>${html}`;
  }
    document.querySelector("#app").innerHTML=html;
  if(page==="readings"&&activeReadingMatch){renderProbableLineups(activeReadingMatch,teamDirectory,activePrediction);if(activeReadingMatch.competition!=="coppa-italia")renderReadingPilotEvidence(activeReading,activeReadingMatch);renderTacticalBaselines(activeReadingMatch,teamStyleProfiles,teams)}
  }
  return {render};
}
