export function createPage(deps){
  const {esc,hero,playerRoleLabel,loadTeamDirectory,loadPlayerLeaderboards}=deps;
const teamDirectoryGrid=data=>`<section class="team-directory-grid team-flip-grid" aria-label="Le 20 squadre">${data.teams.map(team=>{const logo=String(team.monochromeLogo||team.logo||"").replace(/^\.\.\//,""),[primary="#174fa5",secondary="#081d48"]=team.colors||[];return `<a class="team-directory-card team-flip-card" href="statistiche-squadra/${team.id}.html" style="--team-primary:${primary};--team-secondary:${secondary}" aria-label="${esc(team.name)}: apri rosa e statistiche"><span class="team-flip-inner"><span class="team-flip-face team-flip-front"><img src="${esc(logo)}" alt=""></span><span class="team-flip-face team-flip-back"><strong>${esc(team.name)}</strong><span>${team.previousSeason.position?`${team.previousSeason.position}ª posizione · ${team.previousSeason.points} punti`:"Posizione N/D"}</span><span>${esc(team.stadium||"Stadio N/D")}</span><span>Allenatore: ${esc(team.coach||"N/D")}</span><span>Modulo: ${esc(team.preferredFormation||"N/D")}</span><b>Apri scheda</b></span></span></a>`}).join("")}</section>`;
const globalLeaderboardValue=value=>Number.isInteger(value)?String(value):Number(value).toFixed(2);
function globalPlayerLeaderboardTable(data,periodId,metricId){
  const period=data.periods?.[periodId],ranking=period?.rankings?.[metricId];
  if(!ranking?.players?.length)return `<div class="data-warning"><strong>Classifica ${esc(period?.label||periodId)} non disponibile</strong><p>La statistica selezionata non ha dati individuali verificati sufficienti per questo periodo.</p></div>`;
  const valueHeaders=ranking.hasPer90?`<th>${esc(ranking.label)} totali</th><th>${esc(ranking.label)} / 90</th>`:"";
  return `<div class="global-leaderboard-caption"><strong>${esc(period.label)} · Top 15 · ${esc(ranking.label)}</strong><span>${ranking.availablePlayers} calciatori con dato disponibile</span></div><div class="table-wrap"><table class="global-player-table"><colgroup><col class="global-col-rank"><col class="global-col-player"><col class="global-col-team"><col class="global-col-appearances"><col class="global-col-minutes"><col class="global-col-value"><col class="global-col-rate"></colgroup><thead><tr><th>#</th><th>Calciatore</th><th>Squadra 2026/27</th><th>PG</th><th>Min</th>${valueHeaders}</tr></thead><tbody>${ranking.players.map((player,index)=>{const serieB=periodId!=="2026/27"&&player.competition==="Serie B"?'<span class="serie-b-marker" title="Il riepilogo include dati prodotti in Serie B 2025/26">* Serie B</span>':"",valueCells=ranking.hasPer90?`<td><strong class="global-leader-value">${globalLeaderboardValue(player.totalValue)}</strong></td><td><strong class="global-leader-rate">${player.per90Value===null?"N/D":globalLeaderboardValue(player.per90Value)}</strong></td>`:"";return `<tr><td><span class="global-leader-rank">${index+1}</span></td><td><a class="global-leader-player" href="statistiche-squadra/${esc(player.currentTeamId)}.html#squad-results"><span><strong>${esc(player.name)}</strong>${serieB}</span><small>${esc(playerRoleLabel(player.role))}</small></a></td><td>${esc(player.currentTeam)}</td><td>${player.appearances??"N/D"}</td><td>${player.minutes??"N/D"}</td>${valueCells}</tr>`}).join("")}</tbody></table></div>`;
}
function globalPlayerLeaderboards(data){
  const defaultPeriod="2026/27",rankings=Object.values(data.periods[defaultPeriod].rankings),statButtons=rankings.map(ranking=>`<button type="button" data-player-stat="${esc(ranking.id)}" class="global-stat-button${ranking.id==="goals"?' active':''}" aria-pressed="${ranking.id==="goals"}">${esc(ranking.label)}</button>`).join(""),periodButtons=Object.values(data.periods).map(period=>`<button type="button" data-player-period="${esc(period.id)}" class="global-stat-button global-period-button${period.id===defaultPeriod?' active':''}" aria-pressed="${period.id===defaultPeriod}">${esc(period.label)}</button>`).join("");
  return `<section class="section global-player-leaders" id="top-15-calciatori"><header class="global-player-leaders-heading"><div><p class="eyebrow">Classifiche individuali per stagione</p><h2>Top 15 calciatori per statistica</h2></div><p>Separa i dati 2026/27 da quelli 2025/26 e offre un totale combinato. I valori non verificati restano esclusi; “* Serie B” segnala i dati cadetti inclusi nel 2025/26 o nel totale.</p></header><div class="global-leaderboard-controls" aria-label="Seleziona periodo e classifica"><div class="global-stat-group global-period-group"><strong>Periodo</strong><div>${periodButtons}</div></div><div class="global-stat-group"><strong>Statistica</strong><div>${statButtons}</div></div></div><div id="global-player-leaderboard" aria-live="polite">${globalPlayerLeaderboardTable(data,defaultPeriod,"goals")}</div><p class="global-leaderboard-note">Le classifiche sono ordinate per valore totale; la media ogni 90 minuti è mostrata nella stessa riga. Nel 2026/27 tiri e tiri nello specchio hanno copertura parziale, mentre i falli individuali non sono ancora disponibili.</p></section>`;
}
  async function render(){
    const page="team-stats",[teamDirectory,playerLeaderboards]=await Promise.all([loadTeamDirectory(),loadPlayerLeaderboards()]);
    let html="";
  if(page==="team-stats")html=hero("Serie A 2026/27","Statistiche squadre","Consulta le rose, le statistiche individuali, i valori per 90 minuti e le classifiche dei migliori calciatori.")+`${teamDirectoryGrid(teamDirectory)}${globalPlayerLeaderboards(playerLeaderboards)}`;
    document.querySelector("#app").innerHTML=html;
  if(page==="team-stats"){const controls=document.querySelector(".global-leaderboard-controls"),target=document.querySelector("#global-player-leaderboard");let periodId="2026/27",metricId="goals";controls.addEventListener("click",event=>{const periodButton=event.target.closest("[data-player-period]"),statButton=event.target.closest("[data-player-stat]");if(!periodButton&&!statButton)return;if(periodButton){periodId=periodButton.dataset.playerPeriod;controls.querySelectorAll("[data-player-period]").forEach(item=>{const active=item===periodButton;item.classList.toggle("active",active);item.setAttribute("aria-pressed",String(active))})}if(statButton){metricId=statButton.dataset.playerStat;controls.querySelectorAll("[data-player-stat]").forEach(item=>{const active=item===statButton;item.classList.toggle("active",active);item.setAttribute("aria-pressed",String(active))})}target.innerHTML=globalPlayerLeaderboardTable(playerLeaderboards,periodId,metricId)})}
  }
  return {render};
}
