const fs=require("fs"),path=require("path"),zlib=require("zlib");
const {loadConfig}=require("./config"),{createProvider}=require("./providers"),{normalizeBundle}=require("./normalize"),{generateAggregates}=require("./aggregate");
const args=process.argv.slice(2),option=(name,fallback)=>{const index=args.indexOf(`--${name}`);return index>=0?args[index+1]:fallback},flag=name=>args.includes(`--${name}`),ensure=dir=>fs.mkdirSync(dir,{recursive:true}),write=(file,value)=>{ensure(path.dirname(file));fs.writeFileSync(file,JSON.stringify(value,null,2)+"\n")},writeRaw=(file,value)=>{ensure(path.dirname(file));fs.writeFileSync(file,zlib.gzipSync(Buffer.from(JSON.stringify(value))))};
const requiredPaths=["competition","season","matchday","date","homeTeam.slug","awayTeam.slug","score.home","score.away","referee.name","teamStats.home.fouls","teamStats.home.yellowCards","teamStats.home.secondYellowCards","teamStats.home.straightRedCards","teamStats.home.penaltiesFor","teamStats.home.penaltiesAgainst","teamStats.away.fouls","teamStats.away.yellowCards","teamStats.away.secondYellowCards","teamStats.away.straightRedCards","teamStats.away.penaltiesFor","teamStats.away.penaltiesAgainst","source.fixtureId","source.url","source.retrievedAt"];
const missingRequired=match=>requiredPaths.filter(pathName=>{if(pathName==="matchday"&&match.stage!=="regular-season")return false;const value=pathName.split(".").reduce((current,key)=>current?.[key],match);return value===null||value===undefined||value===""});
const parallel=async(items,limit,worker)=>{const output=new Array(items.length),queue={next:0};await Promise.all(Array.from({length:Math.min(limit,items.length)},async()=>{while(queue.next<items.length){const index=queue.next++;output[index]=await worker(items[index],index)}}));return output};
function loadCalendar(config,season){const file=path.join(config.calendarRoot,`${season}.json`);if(!fs.existsSync(file))throw new Error(`Calendario normalizzato mancante: eseguire import-calendars.js --season ${season}`);const data=JSON.parse(fs.readFileSync(file,"utf8")),map=new Map(data.matches.map(row=>[row.joinKey,row]));return {data,map}}
function joinCalendar(match,calendar){if(match.stage!=="regular-season")return match;const key=[match.competition,match.season,match.homeTeam.slug,match.awayTeam.slug].join("|"),row=calendar.map.get(key);if(row){match.matchday=row.matchday;match.calendarSource={...calendar.data.sources[match.competition],retrievedAt:calendar.data.retrievedAt,joinKey:key}}return match}
async function main(){
  const config=loadConfig(),provider=createProvider(config),season=option("season",config.season),pilot=flag("pilot"),full=flag("full"),limit=full?Infinity:Number(option("limit","10")),selected=option("competition","all"),retrievedAt=new Date().toISOString(),seasonYear=Number(season.slice(0,4)),calendar=loadCalendar(config,season);
  if(!Number.isFinite(limit)&&!full)throw new Error("--limit deve essere un intero positivo.");
  const competitionIds=selected==="all"?["serie-a","serie-b"]:[selected],allMatches=[],report={provider:provider.id,season,mode:pilot?"pilot":full?"full":"limited",limit:full?null:limit,retrievedAt,competitions:[],stages:{},missingFields:{},duplicateFixtureIds:[],calendarJoin:{matched:0,unmatched:0}};
  for(const competitionId of competitionIds){const competition=config.competitions[competitionId];if(!competition)throw new Error(`Competizione sconosciuta: ${competitionId}`);const listed=await provider.listFixtures({competition,competitionId,leagueId:competition.apiFootballLeagueId,seasonYear,season,dateRange:config.seasonProfiles[season]?.dateRange,limit});const normalized=await parallel(listed.fixtures,8,async(fixture,index)=>{const bundle=await provider.fetchFixtureBundle(fixture),fixtureId=String(bundle.source?.fixtureId||fixture.fixture?.id||fixture.id||fixture.providerFixtureId);writeRaw(path.join(config.rawRoot,provider.id,season,competitionId,`${fixtureId}.json.gz`),{provider:provider.id,competition:competitionId,season,retrievedAt,listSourceUrl:listed.sourceUrl,bundle});const match=joinCalendar(normalizeBundle(bundle,{provider:provider.id,competition,season,retrievedAt}),calendar);if(match.stage==="regular-season")match.matchday===null?report.calendarJoin.unmatched++:report.calendarJoin.matched++;match.missingFields=[...new Set([...(match.missingFields||[]).filter(field=>field!=="matchday"),...missingRequired(match)])];for(const field of match.missingFields)report.missingFields[field]=(report.missingFields[field]||0)+1;if((index+1)%50===0)console.log(`${competitionId}: ${index+1}/${listed.fixtures.length}`);return match});allMatches.push(...normalized);const stageGroups=normalized.reduce((acc,row)=>((acc[row.stage]??=[]).push(row),acc),{});for(const [stage,rows] of Object.entries(stageGroups)){report.stages[`${competitionId}:${stage}`]=rows.length;const suffix=stage==="regular-season"?competitionId:`${competitionId}-${stage}`;write(path.join(config.normalizedRoot,season,`${suffix}${pilot?"-pilot":""}.json`),{provider:provider.id,competition:competitionId,season,stage,retrievedAt,matches:rows})}report.competitions.push({competition:competitionId,listed:listed.fixtures.length,regularSeason:stageGroups["regular-season"]?.length||0,postseason:normalized.length-(stageGroups["regular-season"]?.length||0),fixtureIds:normalized.map(match=>match.providerFixtureId)})}
  const seen=new Set();for(const match of allMatches){const key=`${match.competition}|${match.providerFixtureId}`;if(seen.has(key))report.duplicateFixtureIds.push(key);seen.add(key)}const aggregates=generateAggregates(allMatches,retrievedAt);write(path.join(config.generatedRoot,season,`aggregates${pilot?"-pilot":""}.json`),aggregates);write(path.join(config.generatedRoot,season,`import-report${pilot?"-pilot":""}.json`),report);console.log(JSON.stringify(report,null,2));
}
main().catch(error=>{console.error(`Import arbitri fallito: ${error.stack||error.message}`);process.exitCode=1});
