const valueFor=(statistics,type)=>statistics?.statistics?.find(item=>item.type===type)?.value??null;
const number=value=>{if(value===null||value===undefined||value==="")return null;const parsed=Number(String(value).replace("%",""));return Number.isFinite(parsed)?parsed:null};
function normalizeApiFootball(bundle,context){
  const fixture=bundle.fixture,home=fixture.teams.home,away=fixture.teams.away,statistics=bundle.statistics.response||[],events=bundle.events.response||[],statsFor=id=>statistics.find(item=>item.team?.id===id),cardCounts=id=>events.filter(event=>event.team?.id===id&&event.type==="Card").reduce((acc,event)=>{const detail=String(event.detail||"").toLowerCase();if(detail.includes("second yellow"))acc.secondYellow++;else if(detail.includes("red"))acc.straightRed++;return acc},{secondYellow:0,straightRed:0}),side=id=>{const stats=statsFor(id),cards=cardCounts(id);return {teamId:String(id),teamName:id===home.id?home.name:away.name,fouls:number(valueFor(stats,"Fouls")),yellowCards:number(valueFor(stats,"Yellow Cards")),secondYellowCards:cards.secondYellow,straightRedCards:cards.straightRed,penaltiesFor:null,penaltiesAgainst:null}};
  const homeStats=side(home.id),awayStats=side(away.id),missing=[];for(const [label,data] of [["home",homeStats],["away",awayStats]])for(const field of ["fouls","yellowCards","penaltiesFor","penaltiesAgainst"])if(data[field]===null)missing.push(`${label}.${field}`);if(!fixture.fixture.referee)missing.push("referee.name");
  return {id:`${context.competition.id}-${context.season}-${fixture.fixture.id}`,provider:context.provider,providerFixtureId:String(fixture.fixture.id),competition:context.competition.id,competitionName:context.competition.name,season:context.season,matchday:number(String(fixture.league.round||"").match(/\d+/)?.[0]),date:fixture.fixture.date||null,homeTeam:{id:String(home.id),name:home.name},awayTeam:{id:String(away.id),name:away.name},score:{home:fixture.goals.home,away:fixture.goals.away},status:fixture.fixture.status?.short||null,referee:{name:fixture.fixture.referee||null,providerId:null},teamStats:{home:homeStats,away:awayStats},source:{provider:context.provider,fixtureId:String(fixture.fixture.id),url:bundle.source.url,statisticsUrl:bundle.source.statisticsUrl,eventsUrl:bundle.source.eventsUrl,retrievedAt:context.retrievedAt},missingFields:[...new Set(missing)]};
}
function normalizeEspn(bundle,context){
  const event=bundle.event,competition=event.competitions?.[0],competitors=competition?.competitors||[],home=competitors.find(team=>team.homeAway==="home"),away=competitors.find(team=>team.homeAway==="away"),boxscore=bundle.summary.boxscore?.teams||[],statsFor=id=>boxscore.find(item=>String(item.team?.id)===String(id))?.statistics||[],stat=(id,name)=>number(statsFor(id).find(item=>item.name===name)?.displayValue),keyEvents=bundle.summary.keyEvents||[];
  if(!home||!away)throw new Error(`Squadre mancanti nel fixture ESPN ${event.id}`);
  const cards=id=>{const events=keyEvents.filter(item=>String(item.team?.id)===String(id)),secondYellow=events.filter(item=>/second.*yellow|yellow.*red/i.test(`${item.type?.type||""} ${item.type?.text||""} ${item.text||""}`)).length,totalRed=stat(id,"redCards"),explicitDirect=events.filter(item=>/red-card/.test(item.type?.type||"")&&!/yellow/.test(item.type?.type||"")).length;return {secondYellow,totalRed,straightRed:totalRed===null?(explicitDirect||null):Math.max(totalRed-secondYellow,0)}};
  const side=team=>{const id=String(team.team.id),card=cards(id),penalties=stat(id,"penaltyKickShots");return {teamId:id,teamName:team.team.displayName||team.team.name,fouls:stat(id,"foulsCommitted"),yellowCards:stat(id,"yellowCards"),secondYellowCards:card.totalRed===null&&card.secondYellow===0?null:card.secondYellow,straightRedCards:card.straightRed,penaltiesFor:penalties,penaltiesAgainst:null}};
  const homeStats=side(home),awayStats=side(away);homeStats.penaltiesAgainst=awayStats.penaltiesFor;awayStats.penaltiesAgainst=homeStats.penaltiesFor;
  const missing=[];for(const [label,data] of [["home",homeStats],["away",awayStats]])for(const field of ["fouls","yellowCards","secondYellowCards","straightRedCards","penaltiesFor","penaltiesAgainst"])if(data[field]===null)missing.push(`${label}.${field}`);const official=bundle.summary.gameInfo?.officials?.[0];if(!official?.fullName)missing.push("referee.name");
  return {id:`${context.competition.id}-${context.season}-${event.id}`,provider:context.provider,providerFixtureId:String(event.id),competition:context.competition.id,competitionName:context.competition.name,season:context.season,matchday:number(event.week?.number),date:event.date||competition.date||null,homeTeam:{id:String(home.team.id),name:home.team.displayName||home.team.name},awayTeam:{id:String(away.team.id),name:away.team.displayName||away.team.name},score:{home:number(home.score),away:number(away.score)},status:event.status?.type?.name||null,referee:{name:official?.fullName||null,providerId:official?.id?String(official.id):null},teamStats:{home:homeStats,away:awayStats},source:{provider:context.provider,fixtureId:String(event.id),url:bundle.source.url,summaryUrl:bundle.source.summaryUrl,retrievedAt:context.retrievedAt},missingFields:[...new Set(missing)]};
}
function normalizeBundle(bundle,context){if(context.provider==="api-football")return normalizeApiFootball(bundle,context);if(context.provider==="espn")return normalizeEspn(bundle,context);if(context.provider==="file"){if(!bundle.normalized)throw new Error("Il bundle del provider file deve contenere normalized.");return {...bundle.normalized,source:{...bundle.normalized.source,retrievedAt:context.retrievedAt}}}throw new Error(`Normalizzatore mancante: ${context.provider}`)}
module.exports={normalizeBundle};
