const fs=require("fs"),path=require("path"),zlib=require("zlib");
const {referee:canonicalReferee}=require("./canonical");
const root=path.resolve(__dirname,"../.."),read=file=>JSON.parse(fs.readFileSync(path.join(root,file),"utf8")),write=(file,value)=>{const target=path.join(root,file);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,JSON.stringify(value,null,2)+"\n")};
const regular={"serie-a":read("data/normalized/referee-matches/2025-26/serie-a.json").matches,"serie-b":read("data/normalized/referee-matches/2025-26/serie-b.json").matches},postseason=["serie-b-playoff-preliminary","serie-b-playoff-semifinal","serie-b-playoff-final","serie-b-playout"].flatMap(name=>read(`data/normalized/referee-matches/2025-26/${name}.json`).matches),aggregates=read("data/generated/referee-stats/2025-26/aggregates.json"),snapshot=read("data/normalized/referee-stats-2025-26.json");
const checks=[];function check(name,ok,details){checks.push({name,ok,details});if(!ok)process.exitCode=1}
for(const [competition,matches] of Object.entries(regular)){check(`${competition}: 380 gare regolari`,matches.length===380,{actual:matches.length,expected:380});check(`${competition}: fixture univoche`,new Set(matches.map(row=>row.providerFixtureId)).size===matches.length,{duplicates:matches.length-new Set(matches.map(row=>row.providerFixtureId)).size});check(`${competition}: giornate complete`,Array.from({length:38},(_,i)=>matches.filter(row=>row.matchday===i+1).length).every(count=>count===10),{perMatchday:Array.from({length:38},(_,i)=>matches.filter(row=>row.matchday===i+1).length)});check(`${competition}: source e retrievedAt`,matches.every(row=>row.source?.fixtureId&&row.source?.url&&row.source?.retrievedAt),{missing:matches.filter(row=>!row.source?.fixtureId||!row.source?.url||!row.source?.retrievedAt).length})}
check("Serie B: stage postseason separati",postseason.length===10&&postseason.every(row=>row.stage!=="regular-season"),{total:postseason.length,stages:postseason.reduce((acc,row)=>((acc[row.stage]=(acc[row.stage]||0)+1),acc),{})});
const verifiedFixtures=[...regular["serie-a"].slice(0,5),...regular["serie-b"].slice(0,5)].map(match=>{const rawFile=path.join(root,"data/raw/referee-stats/espn/2025-26",match.competition,`${match.providerFixtureId}.json.gz`),raw=JSON.parse(zlib.gunzipSync(fs.readFileSync(rawFile))),event=raw.bundle.event,summary=raw.bundle.summary,official=summary.gameInfo?.officials?.[0]?.fullName||null,stats=summary.boxscore?.teams||[];return {competition:match.competition,fixtureId:match.providerFixtureId,url:match.source.url,teamsMatch:event.competitions?.[0]?.competitors?.some(row=>row.homeAway==="home"&&row.team?.displayName===match.homeTeam.providerName)&&event.competitions?.[0]?.competitors?.some(row=>row.homeAway==="away"&&row.team?.displayName===match.awayTeam.providerName),refereeMatch:official===match.referee.providerName,statsTeams:stats.length,retrievedAt:match.source.retrievedAt}});
check("10 fixture ESPN confrontate con snapshot originali",verifiedFixtures.length===10&&verifiedFixtures.every(row=>row.teamsMatch&&row.refereeMatch&&row.statsTeams===2),verifiedFixtures);
const aggregateRows=aggregates.referees.filter(row=>row.stage==="regular-season"),aggregateMap=new Map(aggregateRows.map(row=>[`${row.competition}|${row.refereeSlug}`,row])),sourceComparison=[];for(const historical of snapshot.referees){const slug=canonicalReferee(historical.name).slug;for(const [competition,key] of [["serie-a","serieA"],["serie-b","serieB"]]){const source=historical[key],espn=aggregateMap.get(`${competition}|${slug}`)||null;sourceComparison.push({competition,referee:canonicalReferee(historical.name).name,refereeSlug:slug,currentCan2026_27:true,espn:espn?{matches:espn.matches,foulsPerMatch:espn.foulsPerMatch,yellowCardsPerMatch:espn.yellowCardsPerMatch,redCardsPerMatch:espn.redCardsPerMatch}:null,snapshot:{matches:source.matches,foulsPerMatch:source.foulsPerMatch??null,yellowCardsPerMatch:source.yellowCardsPerMatch,redCardsPerMatch:source.redCardsPerMatch},differences:espn?{matches:espn.matches-source.matches,foulsPerMatch:source.foulsPerMatch==null||espn.foulsPerMatch==null?null:Math.round((espn.foulsPerMatch-source.foulsPerMatch)*100)/100,yellowCardsPerMatch:Math.round((espn.yellowCardsPerMatch-source.yellowCardsPerMatch)*100)/100,redCardsPerMatch:Math.round((espn.redCardsPerMatch-source.redCardsPerMatch)*100)/100}:{reason:"Arbitro non associato a fixture ESPN regolare"}})}}
const round2=value=>Math.round(value*100)/100;
const comparisonTotals=["serie-a","serie-b"].map(competition=>{const rows=sourceComparison.filter(row=>row.competition===competition),espnRows=rows.filter(row=>row.espn),espnMatches=espnRows.reduce((sum,row)=>sum+row.espn.matches,0),snapshotMatches=rows.reduce((sum,row)=>sum+row.snapshot.matches,0),weighted=(items,side,field)=>{const available=items.filter(row=>row[side]?.[field]!=null),matches=available.reduce((sum,row)=>sum+row[side].matches,0);return matches?round2(available.reduce((sum,row)=>sum+row[side][field]*row[side].matches,0)/matches):null};return {competition,scope:"Solo arbitri dell'organico CAN 2026/27 presenti nello snapshot di confronto",espn:{matches:espnMatches,foulsPerMatch:weighted(espnRows,"espn","foulsPerMatch"),yellowCardsPerMatch:weighted(espnRows,"espn","yellowCardsPerMatch"),redCardsPerMatch:weighted(espnRows,"espn","redCardsPerMatch")},snapshot:{matches:snapshotMatches,foulsPerMatch:weighted(rows,"snapshot","foulsPerMatch"),yellowCardsPerMatch:weighted(rows,"snapshot","yellowCardsPerMatch"),redCardsPerMatch:weighted(rows,"snapshot","redCardsPerMatch")},differences:{matches:espnMatches-snapshotMatches,foulsPerMatch:null,yellowCardsPerMatch:null,redCardsPerMatch:null}}}).map(total=>{for(const field of ["foulsPerMatch","yellowCardsPerMatch","redCardsPerMatch"])total.differences[field]=total.espn[field]==null||total.snapshot[field]==null?null:round2(total.espn[field]-total.snapshot[field]);return total});
const historicalOnly=aggregateRows.filter(row=>!row.currentCan2026_27).map(row=>({competition:row.competition,referee:row.referee,refereeSlug:row.refereeSlug,matches:row.matches}));
const missing={matchday:[...regular["serie-a"],...regular["serie-b"]].filter(row=>row.matchday==null).length,referee:[...regular["serie-a"],...regular["serie-b"]].filter(row=>!row.referee.name).length};
const report={season:"2025-26",generatedAt:new Date().toISOString(),status:checks.every(row=>row.ok)?"validated-with-source-differences":"failed",checks,missingFields:missing,verifiedEspnFixtures:verifiedFixtures,sourceComparison:{note:"Le differenze sono conservate; nessuna fonte sovrascrive l'altra.",totals:comparisonTotals,rows:sourceComparison,historicalRefereesNotInCurrentCan:historicalOnly},sources:{espn:"Fixture, statistiche e pagine partita ESPN",soccerbase:snapshot.sources.serieA,sbancoBetSnapshot:snapshot.sources.serieB,calendarSerieA:"C.U. Lega Serie A n. 256; trascrizione strutturata usata per la join",calendarSerieB:"Calendario Lega B 2025/26; trascrizione strutturata usata per la join"}};
write("data/generated/referee-stats/2025-26/validation-report.json",report);console.log(JSON.stringify({status:report.status,checks:checks.map(row=>({name:row.name,ok:row.ok})),missing,historicalOnly:historicalOnly.length,sourceDifferences:sourceComparison.filter(row=>JSON.stringify(row.differences)!=="{}").length},null,2));
